package net.divinerpg.dimensions.arcana;

import net.divinerpg.utils.blocks.ArcanaBlocks;
import net.divinerpg.utils.config.ConfigurationHelper;
import net.divinerpg.utils.events.ArcanaPortalCoords;
import net.minecraft.block.Block;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.util.MathHelper;
import net.minecraft.world.Teleporter;
import net.minecraft.world.World;
import net.minecraft.world.WorldServer;

public class TeleporterArcana extends Teleporter {
	
	protected WorldServer myWorld;

	public TeleporterArcana(WorldServer var1) {
		super(var1);
		this.myWorld = var1;
	}

	@Override
	public boolean placeInExistingPortal(Entity entity, double notUsed_entityX, double notUsed_entityY, double notUsed_entityZ, float notUsed_entityRotation) {
        ArcanaPortalCoords props = ArcanaPortalCoords.getProperties((EntityPlayer)entity);
	    if (entity.dimension == ConfigurationHelper.arcana) {        
            int chunkX = (MathHelper.floor_double(entity.posX) & ~0xf);
            int chunkZ = (MathHelper.floor_double(entity.posZ) & ~0xf);
            int y;

            props.setReturnPortalX(entity.posX);
            props.setReturnPortalY(entity.posY);
            props.setReturnPortalZ(entity.posZ);

            // Find existing portal
            for (y = 9; y < 40; y += 8) {
                if (this.myWorld.getBlock(chunkX + 7, y, chunkZ + 7) == ArcanaBlocks.arcanaPortal) {
                    entity.setLocationAndAngles(chunkX + 7.5D, y + 0.5D, chunkZ + 7.5D, entity.rotationYaw, 0.0F);
                    entity.motionX = entity.motionY = entity.motionZ = 0.0D;            
                    return true;
                }
            }
            
            // Find a location to create a new portal room, avoiding double high rooms
            for (y = 8; y < 40; y += 8) {
                if (this.myWorld.getBlock(chunkX + 7, y, chunkZ + 7) != Blocks.air && this.myWorld.getBlock(chunkX + 7, y + 8, chunkZ + 7) != Blocks.air) {
                    generatePortalRoom(this.myWorld, chunkX, y, chunkZ);
                    entity.setLocationAndAngles(chunkX + 7.5D, y + 1.5D, chunkZ + 7.5D, entity.rotationYaw, 0.0F);
                    entity.motionX = entity.motionY = entity.motionZ = 0.0D;
                    return true;
                }
            }
	    } else {
            entity.setLocationAndAngles(props.getReturnPortalX(), props.getReturnPortalY(), props.getReturnPortalZ(), entity.rotationYaw, 0.0F);
            entity.motionX = entity.motionY = entity.motionZ = 0.0D;            
            return true;
	    }
	    
	    return false;
	}

	private void generatePortalRoom(World world, int x, int y, int z) {

        Block arcanaPortal = ArcanaBlocks.arcanaPortal;
        Block arcanaHardPortalFrame = ArcanaBlocks.arcanaHardPortalFrame;
        Block dungeonBricks = ArcanaBlocks.degradedBrick;
        Block ancientbricks = ArcanaBlocks.ancientBrick;
        Block ancientTile = ArcanaBlocks.ancientTile;
        Block arcanaPower = ArcanaBlocks.arcaniumPower;

        for(int n = 0; n < 16; n++) {
            for(int m = 0; m < 16; m++) {
                for(int o = 1; o < 8; o++) {
                    world.setBlock(x+n, y+o, z+m, Blocks.air);
                }
            }
        }

        world.setBlock(x + 0, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 1, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 2, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 3, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 12, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 13, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 14, ancientbricks);
        world.setBlock(x + 0, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 0, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 1, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 2, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 3, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 4, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 5, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 6, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 9, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 10, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 11, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 12, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 13, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 14, dungeonBricks);
        world.setBlock(x + 0, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 1, ancientTile);
        world.setBlock(x + 0, y + 2, z + 2, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 3, ancientTile);
        world.setBlock(x + 0, y + 2, z + 4, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 5, ancientTile);
        world.setBlock(x + 0, y + 2, z + 6, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 9, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 10, ancientTile);
        world.setBlock(x + 0, y + 2, z + 11, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 12, ancientTile);
        world.setBlock(x + 0, y + 2, z + 13, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 14, dungeonBricks);
        world.setBlock(x + 0, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 1, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 2, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 3, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 4, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 5, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 6, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 7, arcanaPower);
        world.setBlock(x + 0, y + 3, z + 8, arcanaPower);
        world.setBlock(x + 0, y + 3, z + 9, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 10, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 11, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 12, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 13, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 14, dungeonBricks);
        world.setBlock(x + 0, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 1, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 2, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 3, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 4, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 5, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 6, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 7, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 8, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 9, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 10, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 11, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 12, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 13, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 14, ancientbricks);
        world.setBlock(x + 0, y + 4, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 1, ancientTile);
        world.setBlock(x + 0, y + 5, z + 2, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 3, ancientTile);
        world.setBlock(x + 0, y + 5, z + 4, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 5, ancientTile);
        world.setBlock(x + 0, y + 5, z + 6, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 7, ancientTile);
        world.setBlock(x + 0, y + 5, z + 8, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 9, ancientTile);
        world.setBlock(x + 0, y + 5, z + 10, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 11, ancientTile);
        world.setBlock(x + 0, y + 5, z + 12, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 13, ancientTile);
        world.setBlock(x + 0, y + 5, z + 14, ancientbricks);
        world.setBlock(x + 0, y + 5, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 1, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 2, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 3, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 4, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 5, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 6, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 7, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 8, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 9, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 10, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 11, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 12, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 13, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 14, ancientbricks);
        world.setBlock(x + 0, y + 6, z + 15, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 1, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 2, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 3, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 4, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 5, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 6, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 7, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 8, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 9, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 10, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 11, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 12, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 13, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 14, dungeonBricks);
        world.setBlock(x + 0, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 1, y + 0, z + 1, ArcanaBlocks.dungenLamp);
        world.setBlock(x + 1, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 1, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 1, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 1, y + 0, z + 14, ArcanaBlocks.dungenLamp);
        world.setBlock(x + 1, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 1, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 1, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 1, y + 2, z + 0, ancientTile);
        world.setBlock(x + 1, y + 2, z + 15, ancientTile);
        world.setBlock(x + 1, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 1, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 1, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 1, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 1, y + 5, z + 0, ancientTile);
        world.setBlock(x + 1, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 1, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 1, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 1, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 1, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 2, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 2, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 2, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 2, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 2, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 2, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 2, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 2, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 2, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 2, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 2, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 2, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 2, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 2, y + 5, z + 15, ancientTile);
        world.setBlock(x + 2, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 2, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 2, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 2, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 3, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 3, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 3, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 3, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 3, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 3, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 3, y + 2, z + 0, ancientTile);
        world.setBlock(x + 3, y + 2, z + 15, ancientTile);
        world.setBlock(x + 3, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 3, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 3, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 3, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 3, y + 5, z + 0, ancientTile);
        world.setBlock(x + 3, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 3, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 3, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 3, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 3, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 4, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 4, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 4, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 4, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 4, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 4, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 4, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 4, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 4, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 4, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 4, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 4, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 4, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 4, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 4, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 4, y + 5, z + 15, ancientTile);
        world.setBlock(x + 4, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 4, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 4, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 4, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 5, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 5, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 5, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 5, y + 1, z + 6, arcanaHardPortalFrame);
        world.setBlock(x + 5, y + 1, z + 7, arcanaHardPortalFrame);
        world.setBlock(x + 5, y + 1, z + 8, arcanaHardPortalFrame);
        world.setBlock(x + 5, y + 1, z + 9, arcanaHardPortalFrame);
        world.setBlock(x + 5, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 5, y + 2, z + 0, ancientTile);
        world.setBlock(x + 5, y + 2, z + 15, ancientTile);
        world.setBlock(x + 5, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 5, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 5, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 5, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 5, y + 5, z + 0, ancientTile);
        world.setBlock(x + 5, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 5, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 5, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 5, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 5, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 6, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 6, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 6, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 6, y + 1, z + 5, arcanaHardPortalFrame);
        world.setBlock(x + 6, y + 1, z + 6, arcanaPortal);
        world.setBlock(x + 6, y + 1, z + 7, arcanaPortal);
        world.setBlock(x + 6, y + 1, z + 8, arcanaPortal);
        world.setBlock(x + 6, y + 1, z + 9, arcanaPortal);
        world.setBlock(x + 6, y + 1, z + 10, arcanaHardPortalFrame);
        world.setBlock(x + 6, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 6, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 6, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 6, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 6, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 6, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 6, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 6, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 6, y + 5, z + 15, ancientTile);
        world.setBlock(x + 6, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 6, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 6, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 6, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 7, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 1, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 2, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 3, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 12, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 13, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 14, ancientbricks);
        world.setBlock(x + 7, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 7, y + 1, z + 5, arcanaHardPortalFrame);
        world.setBlock(x + 7, y + 1, z + 6, arcanaPortal);
        world.setBlock(x + 7, y + 1, z + 7, arcanaPortal);
        world.setBlock(x + 7, y + 1, z + 8, arcanaPortal);
        world.setBlock(x + 7, y + 1, z + 9, arcanaPortal);
        world.setBlock(x + 7, y + 1, z + 10, arcanaHardPortalFrame);
        world.setBlock(x + 7, y + 3, z + 0, arcanaPower);
        world.setBlock(x + 7, y + 3, z + 15, arcanaPower);
        world.setBlock(x + 7, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 7, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 7, y + 5, z + 0, ancientTile);
        world.setBlock(x + 7, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 7, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 7, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 7, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 7, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 8, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 1, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 2, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 3, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 12, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 13, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 14, ancientbricks);
        world.setBlock(x + 8, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 8, y + 1, z + 5, arcanaHardPortalFrame);
        world.setBlock(x + 8, y + 1, z + 6, arcanaPortal);
        world.setBlock(x + 8, y + 1, z + 7, arcanaPortal);
        world.setBlock(x + 8, y + 1, z + 8, arcanaPortal);
        world.setBlock(x + 8, y + 1, z + 9, arcanaPortal);
        world.setBlock(x + 8, y + 1, z + 10, arcanaHardPortalFrame);
        world.setBlock(x + 8, y + 3, z + 0, arcanaPower);
        world.setBlock(x + 8, y + 3, z + 15, arcanaPower);
        world.setBlock(x + 8, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 8, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 8, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 8, y + 5, z + 15, ancientTile);
        world.setBlock(x + 8, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 8, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 8, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 8, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 9, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 9, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 9, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 9, y + 1, z + 5, arcanaHardPortalFrame);
        world.setBlock(x + 9, y + 1, z + 6, arcanaPortal);
        world.setBlock(x + 9, y + 1, z + 7, arcanaPortal);
        world.setBlock(x + 9, y + 1, z + 8, arcanaPortal);
        world.setBlock(x + 9, y + 1, z + 9, arcanaPortal);
        world.setBlock(x + 9, y + 1, z + 10, arcanaHardPortalFrame);
        world.setBlock(x + 9, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 9, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 9, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 9, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 9, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 9, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 9, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 9, y + 5, z + 0, ancientTile);
        world.setBlock(x + 9, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 9, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 9, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 9, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 9, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 10, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 10, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 10, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 10, y + 1, z + 6, arcanaHardPortalFrame);
        world.setBlock(x + 10, y + 1, z + 7, arcanaHardPortalFrame);
        world.setBlock(x + 10, y + 1, z + 8, arcanaHardPortalFrame);
        world.setBlock(x + 10, y + 1, z + 9, arcanaHardPortalFrame);
        world.setBlock(x + 10, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 10, y + 2, z + 0, ancientTile);
        world.setBlock(x + 10, y + 2, z + 15, ancientTile);
        world.setBlock(x + 10, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 10, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 10, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 10, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 10, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 10, y + 5, z + 15, ancientTile);
        world.setBlock(x + 10, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 10, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 10, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 10, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 11, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 11, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 11, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 11, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 11, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 11, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 11, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 11, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 11, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 11, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 11, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 11, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 11, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 11, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 11, y + 5, z + 0, ancientTile);
        world.setBlock(x + 11, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 11, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 11, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 11, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 11, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 12, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 12, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 12, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 12, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 12, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 12, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 12, y + 2, z + 0, ancientTile);
        world.setBlock(x + 12, y + 2, z + 15, ancientTile);
        world.setBlock(x + 12, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 12, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 12, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 12, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 12, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 12, y + 5, z + 15, ancientTile);
        world.setBlock(x + 12, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 12, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 12, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 12, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 13, y + 0, z + 1, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 13, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 13, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 13, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 13, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 13, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 13, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 13, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 13, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 13, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 13, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 13, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 13, y + 5, z + 0, ancientTile);
        world.setBlock(x + 13, y + 5, z + 15, ancientbricks);
        world.setBlock(x + 13, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 13, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 13, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 13, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 14, y + 0, z + 1, ArcanaBlocks.dungenLamp);
        world.setBlock(x + 14, y + 0, z + 2, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 3, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 4, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 5, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 6, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 14, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 14, y + 0, z + 9, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 10, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 11, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 12, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 13, dungeonBricks);
        world.setBlock(x + 14, y + 0, z + 14, ArcanaBlocks.dungenLamp);
        world.setBlock(x + 14, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 14, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 14, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 14, y + 2, z + 0, ancientTile);
        world.setBlock(x + 14, y + 2, z + 15, ancientTile);
        world.setBlock(x + 14, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 14, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 14, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 14, y + 4, z + 15, ancientbricks);
        world.setBlock(x + 14, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 14, y + 5, z + 15, ancientTile);
        world.setBlock(x + 14, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 14, y + 6, z + 15, ancientbricks);
        world.setBlock(x + 14, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 14, y + 7, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 0, z + 0, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 1, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 2, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 3, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 4, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 5, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 6, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 7, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 8, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 9, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 10, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 11, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 12, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 13, ancientbricks);
        world.setBlock(x + 15, y + 0, z + 14, dungeonBricks);
        world.setBlock(x + 15, y + 0, z + 15, ancientbricks);
        world.setBlock(x + 15, y + 1, z + 0, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 1, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 2, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 3, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 4, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 5, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 6, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 9, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 10, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 11, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 12, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 13, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 14, dungeonBricks);
        world.setBlock(x + 15, y + 1, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 0, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 1, ancientTile);
        world.setBlock(x + 15, y + 2, z + 2, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 3, ancientTile);
        world.setBlock(x + 15, y + 2, z + 4, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 5, ancientTile);
        world.setBlock(x + 15, y + 2, z + 6, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 9, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 10, ancientTile);
        world.setBlock(x + 15, y + 2, z + 11, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 12, ancientTile);
        world.setBlock(x + 15, y + 2, z + 13, dungeonBricks);
        world.setBlock(x + 15, y + 2, z + 14, ancientTile);
        world.setBlock(x + 15, y + 2, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 0, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 1, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 2, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 3, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 4, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 5, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 6, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 7, arcanaPower);
        world.setBlock(x + 15, y + 3, z + 8, arcanaPower);
        world.setBlock(x + 15, y + 3, z + 9, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 10, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 11, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 12, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 13, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 14, dungeonBricks);
        world.setBlock(x + 15, y + 3, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 4, z + 0, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 1, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 2, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 3, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 4, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 5, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 6, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 7, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 8, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 9, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 10, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 11, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 12, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 13, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 14, ancientbricks);
        world.setBlock(x + 15, y + 4, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 5, z + 0, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 1, ancientTile);
        world.setBlock(x + 15, y + 5, z + 2, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 3, ancientTile);
        world.setBlock(x + 15, y + 5, z + 4, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 5, ancientTile);
        world.setBlock(x + 15, y + 5, z + 6, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 7, ancientTile);
        world.setBlock(x + 15, y + 5, z + 8, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 9, ancientTile);
        world.setBlock(x + 15, y + 5, z + 10, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 11, ancientTile);
        world.setBlock(x + 15, y + 5, z + 12, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 13, ancientTile);
        world.setBlock(x + 15, y + 5, z + 14, ancientbricks);
        world.setBlock(x + 15, y + 5, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 6, z + 0, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 1, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 2, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 3, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 4, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 5, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 6, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 7, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 8, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 9, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 10, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 11, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 12, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 13, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 14, ancientbricks);
        world.setBlock(x + 15, y + 6, z + 15, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 0, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 1, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 2, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 3, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 4, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 5, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 6, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 7, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 8, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 9, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 10, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 11, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 12, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 13, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 14, dungeonBricks);
        world.setBlock(x + 15, y + 7, z + 15, dungeonBricks);
	}
	
	@Override
	public boolean makePortal(Entity entity) {
	    return false;
	}
}
	
