move acid.png acid.png
move advancedMushroomStew.png advanced_mushroom_stew.png
move amthirmisBacksword.png amthirmis_backsword.png
move amthirmisBow_0.png amthirmis_bow_0.png
move amthirmisBow_1.png amthirmis_bow_1.png
move amthirmisBow_2.png amthirmis_bow_2.png
move amthirmisBow_3.png amthirmis_bow_3.png
move amthirmisCannon.png amthirmis_cannon.png
move amthirmisClaw.png amthirmis_claw.png
move amthirmisDisk.png amthirmis_disk.png
move amthirmisHammer.png amthirmis_hammer.png
move amthirmisLump.png amthirmis_lump.png
move amthirmisStaff.png amthirmis_staff.png
move ancientKey.png ancient_key.png
move angelicBoots.png angelic_boots.png
move angelicChestplate.png angelic_chestplate.png
move angelicHelmet.png angelic_helmet.png
move angelicLeggings.png angelic_leggings.png
move apalachiaArrow.png apalachia_arrow.png
move apalachiaAxe.png apalachia_axe.png
move apalachiaBlade.png apalachia_blade.png
move apalachiaBlitz.png apalachia_blitz.png
move apalachiaBoots.png apalachia_boots.png
move apalachiaBow_0.png apalachia_bow_0.png
move apalachiaBow_1.png apalachia_bow_1.png
move apalachiaBow_2.png apalachia_bow_2.png
move apalachiaBow_3.png apalachia_bow_3.png
move apalachiaChestplate.png apalachia_chestplate.png
move apalachiaChunk.png apalachia_chunk.png
move apalachiaDust.png apalachia_dust.png
move apalachiaFragments.png apalachia_fragments.png
move apalachiaGem.png apalachia_gem.png
move apalachiaHelmet.png apalachia_helmet.png
move apalachiaLeggings.png apalachia_leggings.png
move apalachiaPhaser.png apalachia_phaser.png
move apalachiaPickaxe.png apalachia_pickaxe.png
move apalachiaShovel.png apalachia_shovel.png
move apalachiaSlicer.png apalachia_slicer.png
move apalachiaSoul.png apalachia_soul.png
move aquaBall.png aqua_ball.png
move aquamarine.png aquamarine.png
move aquamarineSeeds.png aquamarine_seeds.png
move aquaMaul.png aqua_maul.png
move aquastriveBoots.png aquastrive_boots.png
move aquastriveChestplate.png aquastrive_chestplate.png
move aquastriveHelmet.png aquastrive_helmet.png
move aquastriveLeggings.png aquastrive_leggings.png
move aquaticBlazeRod.png aquatic_blaze_rod.png
move aquaticDagger.png aquatic_dagger.png
move aquaticIngot.png aquatic_ingot.png
move aquaticPellets.png aquatic_pellets.png
move aquaticTrident.png aquatic_trident.png
move aquaton.png aquaton.png
move aquatoothMaul.png aquatooth_maul.png
move aquatoothSword.png aquatooth_sword.png
move arcanaSpawnEgg.png arcana_spawn_egg.png
move arcaniteBlade.png arcanite_blade.png
move arcaniteBlaster.png arcanite_blaster.png
move arcanium.png arcanium.png
move arcaniumAttractor.png arcanium_attractor.png
move arcaniumReflector.png arcanium_reflector.png
move arcaniumSaber.png arcanium_saber.png
move arksianeLump.png arksiane_lump.png
move arksianeWrathbow_0.png arksiane_wrathbow_0.png
move arksianeWrathbow_1.png arksiane_wrathbow_1.png
move arksianeWrathbow_2.png arksiane_wrathbow_2.png
move arksianeWrathbow_3.png arksiane_wrathbow_3.png
move arksianeWrathcannon.png arksiane_wrathcannon.png
move arksianeWrathclaw.png arksiane_wrathclaw.png
move arksianeWrathdisk.png arksiane_wrathdisk.png
move arksianeWrathhammer.png arksiane_wrathhammer.png
move arksianeWrathstaff.png arksiane_wrathstaff.png
move arksianeWrathsword.png arksiane_wrathsword.png
move arlemiteAxe.png arlemite_axe.png
move arlemiteBoots.png arlemite_boots.png
move arlemiteChestplate.png arlemite_chestplate.png
move arlemiteHelmet.png arlemite_helmet.png
move arlemiteHoe.png arlemite_hoe.png
move arlemiteIngot.png arlemite_ingot.png
move arlemiteLeggings.png arlemite_leggings.png
move arlemitePickaxe.png arlemite_pickaxe.png
move arlemiteShickaxe.png arlemite_shickaxe.png
move arlemiteShovel.png arlemite_shovel.png
move arlemiteStabber.png arlemite_stabber.png
move backswordTemplate.png backsword_template.png
move bacon.png bacon.png
move bandOfHeivaHunting.png band_of_heiva_hunting.png
move barredDoor.png barred_door.png
move baseSpawnCrystal.png base_spawn_crystal.png
move bed.png bed.png
move bedrockAxe.png bedrock_axe.png
move bedrockBoots.png bedrock_boots.png
move bedrockChestplate.png bedrock_chestplate.png
move bedrockHelmet.png bedrock_helmet.png
move bedrockLeggings.png bedrock_leggings.png
move bedrockMaul.png bedrock_maul.png
move bedrockPickaxe.png bedrock_pickaxe.png
move bedrockShovel.png bedrock_shovel.png
move bedrockSword.png bedrock_sword.png
move blackEnderSword.png black_ender_sword.png
move bloodgem.png bloodgem.png
move bloodgemSword.png bloodgem_sword.png
move blueDiamondChunk.png blue_diamond_chunk.png
move blueDivineSword.png blue_divine_sword.png
move blueEnderBoots.png blue_ender_boots.png
move blueEnderChestplate.png blue_ender_chestplate.png
move blueEnderHelmet.png blue_ender_helmet.png
move blueEnderLeggings.png blue_ender_leggings.png
move blueEnderSword.png blue_ender_sword.png
move bluefireBow_0.png bluefire_bow_0.png
move bluefireBow_1.png bluefire_bow_1.png
move bluefireBow_2.png bluefire_bow_2.png
move bluefireBow_3.png bluefire_bow_3.png
move bluefireStone.png bluefire_stone.png
move bluefireSword.png bluefire_sword.png
move blueRupeeBoots.png blue_rupee_boots.png
move blueRupeeChestplate.png blue_rupee_chestplate.png
move blueRupeeHelmet.png blue_rupee_helmet.png
move blueRupeeLeggings.png blue_rupee_leggings.png
move boiledEgg.png boiled_egg.png
move bowheadAnchor.png bowhead_anchor.png
move bowheadCannon.png bowhead_cannon.png
move bowTemplate.png bow_template.png
move bucketOfFrozenLava.png bucket_of_frozen_lava.png
move bucketOfTar.png bucket_of_tar.png
move callOfTheWatcher.png call_of_the_watcher.png
move cannonTemplate.png cannon_template.png
move captainsSparkler.png captains_sparkler.png
move cermileBacksword.png cermile_backsword.png
move cermileBow_0.png cermile_bow_0.png
move cermileBow_1.png cermile_bow_1.png
move cermileBow_2.png cermile_bow_2.png
move cermileBow_3.png cermile_bow_3.png
move cermileCannon.png cermile_cannon.png
move cermileClaw.png cermile_claw.png
move cermileDisk.png cermile_disk.png
move cermileHammer.png cermile_hammer.png
move cermileLump.png cermile_lump.png
move cermileStaff.png cermile_staff.png
move chargedCollector.png charged_collector.png
move cheese.png cheese.png
move chickenDinner.png chicken_dinner.png
move chocolateLog.png chocolate_log.png
move clawTemplate.png claw_template.png
move cleanPearls.png clean_pearls.png
move collector.png collector.png
move corruptedAxe.png corrupted_axe.png
move corruptedAxe.png.mcmeta corrupted_axe.png.mcmeta
move corruptedBoots.png corrupted_boots.png
move corruptedBullet.png corrupted_bullet.png
move corruptedCannon.png corrupted_cannon.png
move corruptedChestplate.png corrupted_chestplate.png
move corruptedHelmet.png corrupted_helmet.png
move corruptedLeggings.png corrupted_leggings.png
move corruptedMaul.png corrupted_maul.png
move corruptedMaul.png.mcmeta corrupted_maul.png.mcmeta
move corruptedPickaxe.png corrupted_pickaxe.png
move corruptedPickaxe.png.mcmeta corrupted_pickaxe.png.mcmeta
move corruptedShards.png corrupted_shards.png
move corruptedShovel.png corrupted_shovel.png
move corruptedShovel.png.mcmeta corrupted_shovel.png.mcmeta
move corruptedStone.png corrupted_stone.png
move crabAnchor.png crab_anchor.png
move crabClaw.png crab_claw.png
move crabclawCannon.png crabclaw_cannon.png
move crabclawMaul.png crabclaw_maul.png
move cyclopsEye.png cyclops_eye.png
move cyclopsEyeShards.png cyclops_eye_shards.png
move cyclopsianStaff.png cyclopsian_staff.png
move cyclopsianSword.png cyclopsian_sword.png
move darvenArrow.png darven_arrow.png
move darvenBacksword.png darven_backsword.png
move darvenBow_0.png darven_bow_0.png
move darvenBow_1.png darven_bow_1.png
move darvenBow_2.png darven_bow_2.png
move darvenBow_3.png darven_bow_3.png
move darvenCannon.png darven_cannon.png
move darvenClaw.png darven_claw.png
move darvenDisk.png darven_disk.png
move darvenHammer.png darven_hammer.png
move darvenLump.png darven_lump.png
move darvenStaff.png darven_staff.png
move deathBringer.png death_bringer.png
move deathBringer.png.mcmeta death_bringer.png.mcmeta
move degradedBoots.png degraded_boots.png
move degradedChestplate.png degraded_chestplate.png
move degradedHelmet.png degraded_helmet.png
move degradedHood.png degraded_hood.png
move degradedKey.png degraded_key.png
move degradedLeggings.png degraded_leggings.png
move degradedMask.png degraded_mask.png
move degradedTemplate.png degraded_template.png
move demonizedBoots.png demonized_boots.png
move demonizedChestplate.png demonized_chestplate.png
move demonizedHelmet.png demonized_helmet.png
move demonizedHood.png demonized_hood.png
move demonizedLeggings.png demonized_leggings.png
move demonizedMask.png demonized_mask.png
move demonizedTemplate.png demonized_template.png
move densosCrystal.png densos_crystal.png
move diamondBoots.png diamond_boots.png
move diamondChestplate.png diamond_chestplate.png
move diamondHelmet.png diamond_helmet.png
move diamondLeggings.png diamond_leggings.png
move dirtyPearls.png dirty_pearls.png
move diskTemplate.png disk_template.png
move divineAccumulator.png divine_accumulator.png
move divineAxe.png divine_axe.png
move divineBoots.png divine_boots.png
move divineChestplate.png divine_chestplate.png
move divineHelmet.png divine_helmet.png
move divineLeggings.png divine_leggings.png
move divinePickaxe.png divine_pickaxe.png
move divineShards.png divine_shards.png
move divineShickaxe.png divine_shickaxe.png
move divineShovel.png divine_shovel.png
move divineStone.png divine_stone.png
move divineSword.png divine_sword.png
move donatorSword.png donator_sword.png
move donut.png donut.png
move dreamCake.png dream_cake.png
move dreamCarrot.png dream_carrot.png
move dreamFlint.png dream_flint.png
move dreamMelon.png dream_melon.png
move dreamPie.png dream_pie.png
move dreamPowder.png dream_powder.png
move dreamSours.png dream_sours.png
move dreamSweets.png dream_sweets.png
move dualClaw.png dual_claw.png
move dungeonTokens.png dungeon_tokens.png
move edenArrow.png eden_arrow.png
move edenAxe.png eden_axe.png
move edenBlade.png eden_blade.png
move edenBlitz.png eden_blitz.png
move edenBoots.png eden_boots.png
move edenBow_0.png eden_bow_0.png
move edenBow_1.png eden_bow_1.png
move edenBow_2.png eden_bow_2.png
move edenBow_3.png eden_bow_3.png
move edenChestplate.png eden_chestplate.png
move edenChunk.png eden_chunk.png
move edenDust.png eden_dust.png
move edenFragments.png eden_fragments.png
move edenGem.png eden_gem.png
move edenHelmet.png eden_helmet.png
move edenLeggings.png eden_leggings.png
move edenPhaser.png eden_phaser.png
move edenPickaxe.png eden_pickaxe.png
move edenShovel.png eden_shovel.png
move edenSlicer.png eden_slicer.png
move edenSoul.png eden_soul.png
move edenSparkles.png eden_sparkles.png
move eggNog.png egg_nog.png
move eliteRealmiteBoots.png elite_realmite_boots.png
move eliteRealmiteChestplate.png elite_realmite_chestplate.png
move eliteRealmiteHelmet.png elite_realmite_helmet.png
move eliteRealmiteLeggings.png elite_realmite_leggings.png
move empoweredMeat.png empowered_meat.png
move enderBoots.png ender_boots.png
move enderBow_0.png ender_bow_0.png
move enderBow_1.png ender_bow_1.png
move enderBow_2.png ender_bow_2.png
move enderBow_3.png ender_bow_3.png
move enderChestplate.png ender_chestplate.png
move enderHelmet.png ender_helmet.png
move enderice.png enderice.png
move enderLeggings.png ender_leggings.png
move enderScepter.png ender_scepter.png
move enderShards.png ender_shards.png
move enderStone.png ender_stone.png
move enderSword.png ender_sword.png
move enrichedMagicMeat.png enriched_magic_meat.png
move eternalArcherCrystal.png eternal_archer_crystal.png
move eucalyptusRootSeeds.png eucalyptus_root_seeds.png
move everArrow.png ever_arrow.png
move everbright.png everbright.png
move everfright_0.png everfright_0.png
move everfright_1.png everfright_1.png
move everfright_2.png everfright_2.png
move everfright_3.png everfright_3.png
move everlight.png everlight.png
move evernight.png evernight.png
move eversight.png eversight.png
move finishedBoots.png finished_boots.png
move finishedChestplate.png finished_chestplate.png
move finishedHelmet.png finished_helmet.png
move finishedHood.png finished_hood.png
move finishedLeggings.png finished_leggings.png
move finishedMask.png finished_mask.png
move finishedTemplate.png finished_template.png
move firefly.png firefly.png
move firestock.png firestock.png
move firestockSeeds.png firestock_seeds.png
move flamingFury.png flaming_fury.png
move fractiteCannon.png fractite_cannon.png
move fractiteEye.png fractite_eye.png
move frossivence.png frossivence.png
move frostCannon.png frost_cannon.png
move frostclawCannon.png frostclaw_cannon.png
move frostkingSword.png frostking_sword.png
move frostSword.png frost_sword.png
move frozenBoots.png frozen_boots.png
move frozenChestplate.png frozen_chestplate.png
move frozenDoor.png frozen_door.png
move frozenHelmet.png frozen_helmet.png
move frozenLeggings.png frozen_leggings.png
move frozenMaul.png frozen_maul.png
move fruitCake.png fruit_cake.png
move furyArrow.png fury_arrow.png
move furyFire.png fury_fire.png
move furyMaul.png fury_maul.png
move general'sStaff.png general'sStaff.png
move ghastCannon.png ghast_cannon.png
move ghostbane.png ghostbane.png
move glacierSword.png glacier_sword.png
move glisteningBoots.png glistening_boots.png
move glisteningChestplate.png glistening_chestplate.png
move glisteningHelmet.png glistening_helmet.png
move glisteningHood.png glistening_hood.png
move glisteningLeggings.png glistening_leggings.png
move glisteningMask.png glistening_mask.png
move glisteningTemplate.png glistening_template.png
move glowingCollector.png glowing_collector.png
move goldBoots.png gold_boots.png
move goldChestplate.png gold_chestplate.png
move goldenFury.png golden_fury.png
move goldHelmet.png gold_helmet.png
move goldLeggings.png gold_leggings.png
move goldNugget.png gold_nugget.png
move grayDiamondChunk.png gray_diamond_chunk.png
move grayDivineSword.png gray_divine_sword.png
move grayEnderBoots.png gray_ender_boots.png
move grayEnderChestplate.png gray_ender_chestplate.png
move grayEnderHelmet.png gray_ender_helmet.png
move grayEnderLeggings.png gray_ender_leggings.png
move grayRupeeBoots.png gray_rupee_boots.png
move grayRupeeChestplate.png gray_rupee_chestplate.png
move grayRupeeHelmet.png gray_rupee_helmet.png
move grayRupeeLeggings.png gray_rupee_leggings.png
move greenDiamondChunk.png green_diamond_chunk.png
move greenDivineSword.png green_divine_sword.png
move greenEnderBoots.png green_ender_boots.png
move greenEnderChestplate.png green_ender_chestplate.png
move greenEnderHelmet.png green_ender_helmet.png
move greenEnderLeggings.png green_ender_leggings.png
move greenEnderSword.png green_ender_sword.png
move greenlightDagger.png greenlight_dagger.png
move greenRupeeBoots.png green_rupee_boots.png
move greenRupeeChestplate.png green_rupee_chestplate.png
move greenRupeeHelmet.png green_rupee_helmet.png
move greenRupeeLeggings.png green_rupee_leggings.png
move grenade.png grenade.png
move haliteArrow.png halite_arrow.png
move haliteBlade.png halite_blade.png
move haliteBlitz.png halite_blitz.png
move haliteBoots.png halite_boots.png
move haliteBow_0.png halite_bow_0.png
move haliteBow_1.png halite_bow_1.png
move haliteBow_2.png halite_bow_2.png
move haliteBow_3.png halite_bow_3.png
move haliteChestplate.png halite_chestplate.png
move haliteHelmet.png halite_helmet.png
move haliteLeggings.png halite_leggings.png
move halitePhaser.png halite_phaser.png
move haliteSlicer.png halite_slicer.png
move hammerTemplate.png hammer_template.png
move healingStone.png healing_stone.png
move heliosisLump.png heliosis_lump.png
move heliosisWrathbow_0.png heliosis_wrathbow_0.png
move heliosisWrathbow_1.png heliosis_wrathbow_1.png
move heliosisWrathbow_2.png heliosis_wrathbow_2.png
move heliosisWrathbow_3.png heliosis_wrathbow_3.png
move heliosisWrathcannon.png heliosis_wrathcannon.png
move heliosisWrathclaw.png heliosis_wrathclaw.png
move heliosisWrathdisk.png heliosis_wrathdisk.png
move heliosisWrathhammer.png heliosis_wrathhammer.png
move heliosisWrathstaff.png heliosis_wrathstaff.png
move heliosisWrathsword.png heliosis_wrathsword.png
move hellstoneIngot.png hellstone_ingot.png
move hitchak.png hitchak.png
move hitchakSeeds.png hitchak_seeds.png
move honeychunk.png honeychunk.png
move honeysuckle.png honeysuckle.png
move hordeHorn.png horde_horn.png
move hotPumpkinPie.png hot_pumpkin_pie.png
move hunterBow_0.png hunter_bow_0.png
move hunterBow_1.png hunter_bow_1.png
move hunterBow_2.png hunter_bow_2.png
move hunterBow_3.png hunter_bow_3.png
move iceShards.png ice_shards.png
move iceStone.png ice_stone.png
move icicleBane.png icicle_bane.png
move icicleBow_0.png icicle_bow_0.png
move icicleBow_1.png icicle_bow_1.png
move icicleBow_2.png icicle_bow_2.png
move icicleBow_3.png icicle_bow_3.png
move icineSword.png icine_sword.png
move infernalFlame.png infernal_flame.png
move infernoBoots.png inferno_boots.png
move infernoBow_0.png inferno_bow_0.png
move infernoBow_1.png inferno_bow_1.png
move infernoBow_2.png inferno_bow_2.png
move infernoBow_3.png inferno_bow_3.png
move infernoChestplate.png inferno_chestplate.png
move infernoHelmet.png inferno_helmet.png
move infernoLeggings.png inferno_leggings.png
move infernoSword.png inferno_sword.png
move ironBoots.png iron_boots.png
move ironChestplate.png iron_chestplate.png
move ironHelmet.png iron_helmet.png
move ironLeggings.png iron_leggings.png
move jackOManBoots.png jack_o_man_boots.png
move jackOManChestplate.png jack_o_man_chestplate.png
move jackOManHelmet.png jack_o_man_helmet.png
move jackOManLeggings.png jack_o_man_leggings.png
move jungleBoots.png jungle_boots.png
move jungleChestplate.png jungle_chestplate.png
move jungleHelmet.png jungle_helmet.png
move jungleKnife.png jungle_knife.png
move jungleLeggings.png jungle_leggings.png
move jungleRapier.png jungle_rapier.png
move jungleShards.png jungle_shards.png
move jungleStone.png jungle_stone.png
move karosArrow.png karos_arrow.png
move karosLump.png karos_lump.png
move karosRockmaul.png karos_rockmaul.png
move karosWarbow_0.png karos_warbow_0.png
move karosWarbow_1.png karos_warbow_1.png
move karosWarbow_2.png karos_warbow_2.png
move karosWarbow_3.png karos_warbow_3.png
move karosWarcannon.png karos_warcannon.png
move karosWarclaw.png karos_warclaw.png
move karosWardisk.png karos_wardisk.png
move karosWarhammer.png karos_warhammer.png
move karosWarstaff.png karos_warstaff.png
move karosWarsword.png karos_warsword.png
move karotCrystal.png karot_crystal.png
move kormaBoots.png korma_boots.png
move kormaChestplate.png korma_chestplate.png
move kormaHelmet.png korma_helmet.png
move kormaLeggings.png korma_leggings.png
move krakenBoots.png kraken_boots.png
move krakenChestplate.png kraken_chestplate.png
move krakenHelmet.png kraken_helmet.png
move krakenLeggings.png kraken_leggings.png
move krakenScale.png kraken_scale.png
move krakenSkin.png kraken_skin.png
move lamona.png lamona.png
move lamonaSeeds.png lamona_seeds.png
move laVekor.png la_vekor.png
move leatherBoots.png leather_boots.png
move leatherCap.png leather_cap.png
move leatherPants.png leather_pants.png
move leatherTunic.png leather_tunic.png
move legendaryEnderEye.png legendary_ender_eye.png
move liopleurodonAnchor.png liopleurodon_anchor.png
move liopleurodonSkull.png liopleurodon_skull.png
move liopleurodonTeeth.png liopleurodon_teeth.png
move liviciaSword.png livicia_sword.png
move longsword.png longsword.png
move maelstrom.png maelstrom.png
move magicMeat.png magic_meat.png
move marsine.png marsine.png
move marsineSeeds.png marsine_seeds.png
move massivence.png massivence.png
move meriksMissile_0.png meriks_missile_0.png
move meriksMissile_1.png meriks_missile_1.png
move meriksMissile_2.png meriks_missile_2.png
move meriksMissile_3.png meriks_missile_3.png
move meteorMash.png meteor_mash.png
move miner'sAmulet.png miner'sAmulet.png
move moltenShards.png molten_shards.png
move moltenStone.png molten_stone.png
move moltenSword.png molten_sword.png
move moonbulb.png moonbulb.png
move moonbulbSeeds.png moonbulb_seeds.png
move moonClock.png moon_clock.png
move mortumArrow.png mortum_arrow.png
move mortumAxe.png mortum_axe.png
move mortumBlade.png mortum_blade.png
move mortumBlitz.png mortum_blitz.png
move mortumBoots.png mortum_boots.png
move mortumBow_0.png mortum_bow_0.png
move mortumBow_1.png mortum_bow_1.png
move mortumBow_2.png mortum_bow_2.png
move mortumBow_3.png mortum_bow_3.png
move mortumChestplate.png mortum_chestplate.png
move mortumChunk.png mortum_chunk.png
move mortumDust.png mortum_dust.png
move mortumFragments.png mortum_fragments.png
move mortumGem.png mortum_gem.png
move mortumHelmet.png mortum_helmet.png
move mortumLeggings.png mortum_leggings.png
move mortumPhaser.png mortum_phaser.png
move mortumPickaxe.png mortum_pickaxe.png
move mortumShovel.png mortum_shovel.png
move mortumSlicer.png mortum_slicer.png
move mortumSoul.png mortum_soul.png
move mysteriousClock.png mysterious_clock.png
move netheriteBoots.png netherite_boots.png
move netheriteChestplate.png netherite_chestplate.png
move netheriteChunk.png netherite_chunk.png
move netheriteHelmet.png netherite_helmet.png
move netheriteIngot.png netherite_ingot.png
move netheriteLeggings.png netherite_leggings.png
move oceanKnife.png ocean_knife.png
move orbOfLight.png orb_of_light.png
move oreDoor1Item.png ore_door1Item.png
move oreDoor2Item.png ore_door2Item.png
move oreDoor3Item.png ore_door3Item.png
move oreDoor4Item.png ore_door4Item.png
move overworldSpawnEgg.png overworld_spawn_egg.png
move palavence.png palavence.png
move pardimalArrow.png pardimal_arrow.png
move pardimalBacksword.png pardimal_backsword.png
move pardimalBow_0.png pardimal_bow_0.png
move pardimalBow_1.png pardimal_bow_1.png
move pardimalBow_2.png pardimal_bow_2.png
move pardimalBow_3.png pardimal_bow_3.png
move pardimalCannon.png pardimal_cannon.png
move pardimalClaw.png pardimal_claw.png
move pardimalDisk.png pardimal_disk.png
move pardimalHammer.png pardimal_hammer.png
move pardimalLump.png pardimal_lump.png
move pardimalStaff.png pardimal_staff.png
move peppermints.png peppermints.png
move pinfly.png pinfly.png
move pinflySeeds.png pinfly_seeds.png
move pinkGlowbone.png pink_glowbone.png
move pinkGlowboneSeeds.png pink_glowbone_seeds.png
move poisonSaber.png poison_saber.png
move polishedPearls.png polished_pearls.png
move pureAquaticPellets.png pure_aquatic_pellets.png
move purpleBlaze.png purple_blaze.png
move purpleGlowbone.png purple_glowbone.png
move purpleGlowboneSeeds.png purple_glowbone_seeds.png
move quadroticLump.png quadrotic_lump.png
move quadroticWarbow_0.png quadrotic_warbow_0.png
move quadroticWarbow_1.png quadrotic_warbow_1.png
move quadroticWarbow_2.png quadrotic_warbow_2.png
move quadroticWarbow_3.png quadrotic_warbow_3.png
move quadroticWarcannon.png quadrotic_warcannon.png
move quadroticWarclaw.png quadrotic_warclaw.png
move quadroticWardisk.png quadrotic_wardisk.png
move quadroticWarhammer.png quadrotic_warhammer.png
move quadroticWarstaff.png quadrotic_warstaff.png
move quadroticWarsword.png quadrotic_warsword.png
move rawEmpoweredMeat.png raw_empowered_meat.png
move realmiteAxe.png realmite_axe.png
move realmiteBoots.png realmite_boots.png
move realmiteChestplate.png realmite_chestplate.png
move realmiteHelmet.png realmite_helmet.png
move realmiteHoe.png realmite_hoe.png
move realmiteIngot.png realmite_ingot.png
move realmiteLeggings.png realmite_leggings.png
move realmitePickaxe.png realmite_pickaxe.png
move realmiteShovel.png realmite_shovel.png
move realmiteSword.png realmite_sword.png
move redDiamondChunk.png red_diamond_chunk.png
move redDivineSword.png red_divine_sword.png
move redEnderBoots.png red_ender_boots.png
move redEnderChestplate.png red_ender_chestplate.png
move redEnderHelmet.png red_ender_helmet.png
move redEnderLeggings.png red_ender_leggings.png
move redEnderSword.png red_ender_sword.png
move redRupeeBoots.png red_rupee_boots.png
move redRupeeChestplate.png red_rupee_chestplate.png
move redRupeeHelmet.png red_rupee_helmet.png
move redRupeeLeggings.png red_rupee_leggings.png
move reyvorCrystal.png reyvor_crystal.png
move rockChunks.png rock_chunks.png
move rupeeAxe.png rupee_axe.png
move rupeeBoots.png rupee_boots.png
move rupeeChestplate.png rupee_chestplate.png
move rupeeHelmet.png rupee_helmet.png
move rupeeHoe.png rupee_hoe.png
move rupeeIngot.png rupee_ingot.png
move rupeeLeggings.png rupee_leggings.png
move rupeePickaxe.png rupee_pickaxe.png
move rupeeRapier.png rupee_rapier.png
move rupeeShickaxe.png rupee_shickaxe.png
move rupeeShovel.png rupee_shovel.png
move sandslash.png sandslash.png
move santaBoots.png santa_boots.png
move santaCap.png santa_cap.png
move santaPants.png santa_pants.png
move santaTunic.png santa_tunic.png
move scorchingSword.png scorching_sword.png
move scythe.png scythe.png
move scytheProjectile.png scythe_projectile.png
move serenadeOfDeath.png serenade_of_death.png
move serenadeOfHealth.png serenade_of_health.png
move serenadeOfIce.png serenade_of_ice.png
move serenadeOfInfusion.png serenade_of_infusion.png
move serenadeStriker.png serenade_striker.png
move shadowBar.png shadow_bar.png
move shadowBoots.png shadow_boots.png
move shadowBow_0.png shadow_bow_0.png
move shadowBow_1.png shadow_bow_1.png
move shadowBow_2.png shadow_bow_2.png
move shadowBow_3.png shadow_bow_3.png
move shadowChestplate.png shadow_chestplate.png
move shadowCoins.png shadow_coins.png
move shadowHelmet.png shadow_helmet.png
move shadowLeggings.png shadow_leggings.png
move shadowSaber.png shadow_saber.png
move shadowStone.png shadow_stone.png
move sharkAnchor.png shark_anchor.png
move sharkFin.png shark_fin.png
move sharkSword.png shark_sword.png
move shinyPearls.png shiny_pearls.png
move shuriken.png shuriken.png
move skelemanBoots.png skeleman_boots.png
move skelemanChestplate.png skeleman_chestplate.png
move skelemanHelmet.png skeleman_helmet.png
move skelemanLeggings.png skeleman_leggings.png
move skyFlower.png sky_flower.png
move skyPlantSeeds.png sky_plant_seeds.png
move skythernArrow.png skythern_arrow.png
move skythernAxe.png skythern_axe.png
move skythernBlade.png skythern_blade.png
move skythernBlitz.png skythern_blitz.png
move skythernBoots.png skythern_boots.png
move skythernBow_0.png skythern_bow_0.png
move skythernBow_1.png skythern_bow_1.png
move skythernBow_2.png skythern_bow_2.png
move skythernBow_3.png skythern_bow_3.png
move skythernChestplate.png skythern_chestplate.png
move skythernChunk.png skythern_chunk.png
move skythernDust.png skythern_dust.png
move skythernFragments.png skythern_fragments.png
move skythernGem.png skythern_gem.png
move skythernHelmet.png skythern_helmet.png
move skythernLeggings.png skythern_leggings.png
move skythernPhaser.png skythern_phaser.png
move skythernPickaxe.png skythern_pickaxe.png
move skythernShovel.png skythern_shovel.png
move skythernSlicer.png skythern_slicer.png
move skythernSoul.png skythern_soul.png
move slimeSword.png slime_sword.png
move sludgeKey.png sludge_key.png
move snowCones.png snow_cones.png
move snowflake.png snowflake.png
move snowflakeShuriken.png snowflake_shuriken.png
move snowGlobe.png snow_globe.png
move snowslash.png snowslash.png
move snowstormBow_0.png snowstorm_bow_0.png
move snowstormBow_1.png snowstorm_bow_1.png
move snowstormBow_2.png snowstorm_bow_2.png
move snowstormBow_3.png snowstorm_bow_3.png
move soulFiendCrystal.png soul_fiend_crystal.png
move soulKey.png soul_key.png
move soundOfCarols.png sound_of_carols.png
move soundOfMusic.png sound_of_music.png
move staffOfEnrichment.png staff_of_enrichment.png
move staffOfStarlight.png staff_of_starlight.png
move staffTemplate.png staff_template.png
move starlight.png starlight.png
move stormSword.png storm_sword.png
move strongArcanaPotion.png strong_arcana_potion.png
move teakerArrow.png teaker_arrow.png
move teakerBacksword.png teaker_backsword.png
move teakerBow_0.png teaker_bow_0.png
move teakerBow_1.png teaker_bow_1.png
move teakerBow_2.png teaker_bow_2.png
move teakerBow_3.png teaker_bow_3.png
move teakerCannon.png teaker_cannon.png
move teakerClaw.png teaker_claw.png
move teakerDisk.png teaker_disk.png
move teakerHammer.png teaker_hammer.png
move teakerLump.png teaker_lump.png
move teakerStaff.png teaker_staff.png
move teleportationCrystal.png teleportation_crystal.png
move terranBoots.png terran_boots.png
move terranChestplate.png terran_chestplate.png
move terranDagger.png terran_dagger.png
move terranHelmet.png terran_helmet.png
move terranKnife.png terran_knife.png
move terranLeggings.png terran_leggings.png
move terranMaul.png terran_maul.png
move terranShards.png terran_shards.png
move terranStone.png terran_stone.png
move Thumbs.db Thumbs.db
move tomato.png tomato.png
move tomatoSeeds.png tomato_seeds.png
move tormentedBoots.png tormented_boots.png
move tormentedChestplate.png tormented_chestplate.png
move tormentedHelmet.png tormented_helmet.png
move tormentedHood.png tormented_hood.png
move tormentedLeggings.png tormented_leggings.png
move tormentedMask.png tormented_mask.png
move tormentedTemplate.png tormented_template.png
move twilightBow_0.png twilight_bow_0.png
move twilightBow_1.png twilight_bow_1.png
move twilightBow_2.png twilight_bow_2.png
move twilightBow_3.png twilight_bow_3.png
move twilightClock.png twilight_clock.png
move twilightDemonCrystal.png twilight_demon_crystal.png
move vamacheronCrystal.png vamacheron_crystal.png
move veilo.png veilo.png
move veiloSeeds.png veilo_seeds.png
move vemosBoots.png vemos_boots.png
move vemosChestplate.png vemos_chestplate.png
move vemosHelmet.png vemos_helmet.png
move vemosLeggings.png vemos_leggings.png
move vileStorm.png vile_storm.png
move watchingEye.png watching_eye.png
move weakArcanaPotion.png weak_arcana_potion.png
move whaleFin.png whale_fin.png
move whiteMushroom.png white_mushroom.png
move whiteMushroomSeeds.png white_mushroom_seeds.png
move wildwoodArrow.png wildwood_arrow.png
move wildwoodAxe.png wildwood_axe.png
move wildwoodBlade.png wildwood_blade.png
move wildwoodBlitz.png wildwood_blitz.png
move wildwoodBoots.png wildwood_boots.png
move wildwoodBow_0.png wildwood_bow_0.png
move wildwoodBow_1.png wildwood_bow_1.png
move wildwoodBow_2.png wildwood_bow_2.png
move wildwoodBow_3.png wildwood_bow_3.png
move wildwoodChestplate.png wildwood_chestplate.png
move wildwoodChunk.png wildwood_chunk.png
move wildwoodDust.png wildwood_dust.png
move wildwoodFragments.png wildwood_fragments.png
move wildwoodGem.png wildwood_gem.png
move wildwoodHelmet.png wildwood_helmet.png
move wildwoodLeggings.png wildwood_leggings.png
move wildwoodPhaser.png wildwood_phaser.png
move wildwoodPickaxe.png wildwood_pickaxe.png
move wildwoodShovel.png wildwood_shovel.png
move wildwoodSlicer.png wildwood_slicer.png
move wildwoodSoul.png wildwood_soul.png
move winterberry.png winterberry.png
move witherReaperBoots.png wither_reaper_boots.png
move witherReaperChestplate.png wither_reaper_chestplate.png
move witherReaperHelmet.png wither_reaper_helmet.png
move witherReaperLeggings.png wither_reaper_leggings.png
move wizardsBook.png wizards_book.png
move yellowDiamondChunk.png yellow_diamond_chunk.png
move yellowDivineSword.png yellow_divine_sword.png
move yellowEnderBoots.png yellow_ender_boots.png
move yellowEnderChestplate.png yellow_ender_chestplate.png
move yellowEnderHelmet.png yellow_ender_helmet.png
move yellowEnderLeggings.png yellow_ender_leggings.png
move yellowEnderSword.png yellow_ender_sword.png
move yellowRupeeBoots.png yellow_rupee_boots.png
move yellowRupeeChestplate.png yellow_rupee_chestplate.png
move yellowRupeeHelmet.png yellow_rupee_helmet.png
move yellowRupeeLeggings.png yellow_rupee_leggings.png
move 