plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.21'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = "https://modmaven.dev"}
    maven { url = "https://www.cursemaven.com"}
    maven { url = "https://maven.octo-studios.com/releases"}
    maven { url = "https://modmaven.dev"}
    maven { url = uri("https://maven.blakesmods.com") }
    maven { url 'https://maven.blamejared.com'}
    maven { url 'https://maven.rover656.dev/releases' }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

     accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    //Libraries, etc.
    runtimeOnly "curse.maven:bookshelf-228525:${bookshelf_id}" //Bookshelf
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}" //Curios Continuation
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}" //Curios Continuation
    runtimeOnly "curse.maven:cyclops_core-232758:${cyclops_core_id}" //Cyclops Core
//    runtimeOnly "curse.maven:cucumber-272335:${cucumber_id}" //Cucumber
    runtimeOnly "curse.maven:selene-499980:${moonlight_id}" //Moonlight
//    runtimeOnly "curse.maven:owo-lib-532610:${owo_id}" //oωo
    runtimeOnly "curse.maven:prickle-1023259:${prickle_id}" //Prickle
    //JEI, JER and addons
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}" //Just Enough Items
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}" //Just Enough Items
    runtimeOnly "mezz.jei:jei-${minecraft_version}-common:${jei_version}" //Just Enough Items
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}" //Just Enough Items
    compileOnly "curse.maven:just-enough-resources-jer-240630:${jer_id}" //Just Enough Resources
    runtimeOnly "curse.maven:just-enough-resources-jer-240630:${jer_id}" //Just Enough Resources
    runtimeOnly "curse.maven:just-enough-effect-descriptions-jeed-532286:${jeed_id}" //Just Enough Effect Descriptions
    //Guide book
    compileOnly "vazkii.patchouli:Patchouli:1.21-${patchouli_version}-NEOFORGE-SNAPSHOT:api" //Patchouli
    runtimeOnly "vazkii.patchouli:Patchouli:1.21-${patchouli_version}-NEOFORGE-SNAPSHOT" //Patchouli
    //Compat
    //Advanced Mining Dimension isn't ported to 1.21.1
//    runtimeOnly "curse.maven:advent-of-ascension-nevermine-311054:${advent_of_ascension_id}" //Advent of Ascension
//    runtimeOnly "curse.maven:aether-255308:${aether_id}" //The Aether
    //TODO: to add woodcutter variants
    implementation "curse.maven:corail-woodcutter-331983:${corail_woodcutter_id}" //Corail Woodcutter
    runtimeOnly "curse.maven:enchantment-descriptions-250419:${enchantment_description_id}" //Enchantment Description
    //TODO: mob animations, fix hat placement, capabilities
//    runtimeOnly "curse.maven:epic-fight-mod-405076:${epic_fights_id}" //Epic Fights
    implementation "curse.maven:every-compat-628539:${every_compat_id}" //Every Compat
    //TODO: to make cabinet variant textures for Every Compat (and maybe crop blocks)
    implementation "curse.maven:farmers-delight-398521:${farmers_delight_id}" //Farmer's Delight
//    runtimeOnly "curse.maven:mystical-agriculture-246640:${mystical_agriculture_id}" //Mystical Agriculture
    runtimeOnly "curse.maven:productivebees-377897:${productivebees_id}" //Productive Bees
    compileOnly "curse.maven:projecte-226410:${projecte_id}" //ProjectE
    runtimeOnly "curse.maven:projecte-226410:${projecte_id}" //ProjectE
    runtimeOnly "curse.maven:resource-pandas-410681:${resource_pandas_id}" //Resource Pandas
    runtimeOnly "curse.maven:sawmill-964817:${sawmill_id}" //Sawmill
    //TODO: to add raked frozen gravel, cannon boat variants, soup fluids for jars support, way posts in Iceika
    runtimeOnly "curse.maven:supplementaries-412082:${supplementaries_id}" //Supplementaries
    //Traveler's Titles don't have NeoForge version up until 1.21.4
    //Tech mods compat
    //TODO: to make window+pane variant textures for Every Compat
    runtimeOnly "curse.maven:create-328085:${create_id}" //Create
    runtimeOnly "com.enderio:enderio-base:${ender_io_version}" //EnderIO
    runtimeOnly "com.enderio:enderio-conduits:${ender_io_version}" //EnderIO Conduits
    runtimeOnly "com.enderio:enderio-machines:${ender_io_version}" //EnderIO Machines
    implementation "blusunrize.immersiveengineering:ImmersiveEngineering:${immersive_engineering_version}" //Immersive Engineering
    runtimeOnly "curse.maven:industrial-foregoing-266515:${industrial_foregoing_id}" //Industrial Foregoing
    runtimeOnly "curse.maven:integrated_dynamics-236307:${integrated_dynamics_id}" //Integrated Dynamics
    runtimeOnly "curse.maven:common_capabilities-247007:${common_capabilities_id}" //Common Capabilities
//    runtimeOnly "curse.maven:iron-jetpacks-284497:${iron_jetpacks_id}" //Iron Jetpacks
    compileOnly "mekanism:Mekanism:${mekanism_version}:api" //Mekanism
    runtimeOnly "mekanism:Mekanism:${mekanism_version}" //Mekanism
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:additions" //Mekanism: Additions
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:generators" //Mekanism: Generators
    runtimeOnly "mekanism:Mekanism:${mekanism_version}:tools" //Mekanism: Tools
    runtimeOnly "curse.maven:pneumaticcraft-repressurized-281849:${pneumaticcraft_id}" //Pneumaticcraft
    runtimeOnly "curse.maven:titanium-287342:${titanium_id}" //Titanium
    //Helpful
    runtimeOnly "curse.maven:appleskin-248787:${apple_skin_id}" //Apple Skin
    runtimeOnly "curse.maven:not-enough-crashes-forge-442354:${not_enough_crashes_id}" //Not Enough Crashes
    runtimeOnly "curse.maven:mmmmmmmmmmmm-225738:${target_dummy_id}" //Target Dummy
    runtimeOnly "curse.maven:tslatentitystatus-tes-830420:${tes_id}" //TslatEntityStatus
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}