org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#neogradle.subsystems.parchment.minecraftVersion=1.21
#neogradle.subsystems.parchment.mappingsVersion=2024.07.28

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.213
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=divinerpg
mod_name=DivineRPG
mod_license=All Rights Reserved
mod_version=1.10.9.2
mod_group_id=TeamDivineRPG.divinerpg
mod_authors=https://github.com/DivineRPG/DivineRPG-Assets/blob/main/credits.md
mod_description=Adds various dimensions, weapons, and mobs.

## Mod Versions
curios_version=9.5.1+1.21.1
jei_version=19.25.0.323
patchouli_version=88
ender_io_version=7.1.8-alpha
immersive_engineering_version=1.21.1-12.4.2-194
mekanism_version=1.21.1-10.7.17.83

## Mod File ID
bookshelf_id=7115412
cyclops_core_id=7076266
cucumber_id=7180790
moonlight_id=7155864
owo_id=6785734
prickle_id=6961457
jer_id=6506298
jeed_id=7035045
aether_id=7043502
#advanced_mining_dimension_id=4688892
corail_woodcutter_id=5749639
enchantment_description_id=7039849
every_compat_id=7132313
farmers_delight_id=6917256
mystical_agriculture_id=7180808
productivebees_id=6966608
projecte_id=6611984
resource_pandas_id=5505741
sawmill_id=7130272
supplementaries_id=7141234
common_capabilities_id=7117034
industrial_foregoing_id=7073719
integrated_dynamics_id=7102002
iron_jetpacks_id=7105279
pneumaticcraft_id=6817362
titanium_id=6875285
apple_skin_id=6616291
not_enough_crashes_id=6598103
target_dummy_id=6826533
tes_id=7115952
