org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#neogradle.subsystems.parchment.minecraftVersion=1.21
#neogradle.subsystems.parchment.mappingsVersion=2024.07.28

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.176
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=divinerpg
mod_name=DivineRPG
mod_license=All Rights Reserved
mod_version=1.10.9.1
mod_group_id=TeamDivineRPG.divinerpg
mod_authors=https://github.com/DivineRPG/DivineRPG-Assets/blob/main/credits.md
mod_description=Adds various dimensions, weapons, and mobs.

## Mod Versions
patchouli_version=88
curios_version=9.5.1+1.21.1
jei_version=19.21.2.313
immersive_engineering_version=1.21.1-12.3.1-189
mekanism_version=1.21.1-10.7.14.79
ender_io_version=7.1.8-alpha

## Mod File ID
jer_id=6506298
jep_version=6231254
projecte_version=6611984
resource_pandas_id=5505741
advanced_mining_dimension_id=4688892
productivebees_id=6621891
common_capabilities_id=6602359
cyclops_core_id=6602344
integrated_dynamics_id=6636764
industrial_foregoing_id=6626624
titanium_id=6443608
pneumaticcraft_id=6288626
not_enough_crashes_id=6598103
