org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#neogradle.subsystems.parchment.minecraftVersion=1.21
#neogradle.subsystems.parchment.mappingsVersion=2024.07.28

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.148
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=divinerpg
mod_name=DivineRPG
mod_license=All Rights Reserved
mod_version=1.10.8.4.2
mod_group_id=TeamDivineRPG.divinerpg
mod_authors=https://github.com/DivineRPG/DivineRPG-Assets/blob/main/credits.md
mod_description=Adds various dimensions, weapons, and mobs.

## Mod Versions
patchouli_version=88
curios_version=9.4.2+1.21.1
jei_version=19.21.0.247
immersive_engineering_version=1.21.1-12.1.1-186
mekanism_version=1.21.1-10.7.13.78
ender_io_version=7.1.8-alpha

## Mod File ID
jer_id=6190140
jep_version=6231254
projecte_version=6323142
resource_pandas_id=5505741
advanced_mining_dimension_id=4688892
productivebees_id=6419769
common_capabilities_id=6384335
cyclops_core_id=6414678
integrated_dynamics_id=6418767
industrial_foregoing_id=6418862
titanium_id=6337206
pneumaticcraft_id=6288626
