package divinerpg.utils;

import net.minecraft.item.Item;
import net.minecraftforge.common.util.EnumHelper;

public class DivineRPGMaterials {
	// name, harvestLevel, maxUses, efficiency, damage, enchantability
	public static final Item.ToolMaterial arlemiteSwordMaterial = EnumHelper.addToolMaterial("ARLEMITE", 2, 250, 6.0F, 2.0F, 14);
	public static final Item.ToolMaterial amthrimisSwordMaterial = EnumHelper.addToolMaterial("AMTHRIMIS", 2, 250, 3.0F, 7.0F, 1);
	public static final Item.ToolMaterial aquatoothSwordMaterial = EnumHelper.addToolMaterial("AQUATOOTH", 2, 250, 10.0F, 6.0F, 10);
	public static final Item.ToolMaterial arksianeSwordMaterial = EnumHelper.addToolMaterial("ARKSIANE", 2, 250, 14.0F, 38.0F, 14);
	public static final Item.ToolMaterial bedrockSwordMaterial = EnumHelper.addToolMaterial("BEDROCK", 2, 0, 14.0F, 10.0F, 14);
	public static final Item.ToolMaterial enderSwordMaterial = EnumHelper.addToolMaterial("ENDER", 2, 250, 16.0F, 12.0F, 16);
	public static final Item.ToolMaterial bloodgemSwordMaterial = EnumHelper.addToolMaterial("BLOODGEM", 2, 250, 15.0F, 11.0F, 15);
	public static final Item.ToolMaterial divineSwordMaterial = EnumHelper.addToolMaterial("DIVINE", 2, 250, 22.0F, 18.0F, 22);
	public static final Item.ToolMaterial stormSwordMaterial = EnumHelper.addToolMaterial("STORM", 2, 250, 5.0F, 1.0F, 5);
	public static final Item.ToolMaterial rupeeSwordMaterial = EnumHelper.addToolMaterial("RUPEE", 2, 250, 5.0F, 1.0F, 5);
	public static final Item.ToolMaterial teakerSwordMaterial = EnumHelper.addToolMaterial("TEAKER", 1, 250, 3.0F, 5.0F, 1);
	public static final Item.ToolMaterial darvenSwordMaterial = EnumHelper.addToolMaterial("DARVEN", 3, 250, 3.0F, 10.0F, 1);
	public static final Item.ToolMaterial cermileSwordMaterial = EnumHelper.addToolMaterial("CERMILE", 4, 250, 3.0F, 14.0F, 1);
	public static final Item.ToolMaterial pardimalSwordMaterial = EnumHelper.addToolMaterial("PARDIMAL", 5, 250, 3.0F, 17.0F, 1);
	public static final Item.ToolMaterial quadroticSwordMaterial = EnumHelper.addToolMaterial("QUADROTIC", 6, 250, 3.0F, 21.0F, 1);
	public static final Item.ToolMaterial karosSwordMaterial = EnumHelper.addToolMaterial("KAROS", 7, 250, 3.0F, 23.0F, 1);
	public static final Item.ToolMaterial heliosisSwordMaterial = EnumHelper.addToolMaterial("HELIOSIS", 8, 250, 3.0F, 30.0F, 1);
	public static final Item.ToolMaterial sharkSwordMaterial = EnumHelper.addToolMaterial("SHARK", 8, 250, 3.0F, 14.0F, 1);
	public static final Item.ToolMaterial slimeSwordMaterial = EnumHelper.addToolMaterial("SLIME", 8, 250, 3.0F, 11.0F, 1);
	public static final Item.ToolMaterial infernoSwordMaterial = EnumHelper.addToolMaterial("INFERNO", 8, 250, 3.0F, 12.0F, 1);
	public static final Item.ToolMaterial moltenSwordMaterial = EnumHelper.addToolMaterial("MOLTEN", 8, 250, 3.0F, 10.0F, 1);
	public static final Item.ToolMaterial scorchingSwordMaterial = EnumHelper.addToolMaterial("SCORCHING", 8, 250, 3.0F, 20.0F, 1);
	public static final Item.ToolMaterial bluefireSwordMaterial = EnumHelper.addToolMaterial("BLUEFIRE", 8, 250, 3.0F, 20.0F, 1);
	public static final Item.ToolMaterial icineSwordMaterial = EnumHelper.addToolMaterial("ICINE", 8, 250, 3.0F, 22.0F, 1);
	public static final Item.ToolMaterial glacierSwordMaterial = EnumHelper.addToolMaterial("GLACIER", 8, 250, 3.0F, 18.0F, 1);
	public static final Item.ToolMaterial frostKingSwordMaterial = EnumHelper.addToolMaterial("FROSTKING", 8, 250, 3.0F, 16.0F, 1);
	public static final Item.ToolMaterial realmiteSwordMaterial = EnumHelper.addToolMaterial("REALMITE", 8, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial cyclopsianSwordMaterial = EnumHelper.addToolMaterial("CYCLOPSIAN", 8, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial edenSwordMaterial = EnumHelper.addToolMaterial("EDEN", 100, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial wildwoodSwordMaterial = EnumHelper.addToolMaterial("WILDWOOD", 100, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial apalachiaSwordMaterial = EnumHelper.addToolMaterial("APALACHIA", 100, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial skythernSwordMaterial = EnumHelper.addToolMaterial("SKYTHERN", 100, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial mortumSwordMaterial = EnumHelper.addToolMaterial("MORTUM", 100, 250, 3.0F, 6.0F, 1);
	public static final Item.ToolMaterial everlightSwordMaterial = EnumHelper.addToolMaterial("EVERLIGHT", 100, 250, 3.0F, 45.0F, 1);
	public static final Item.ToolMaterial everbrightSwordMaterial = EnumHelper.addToolMaterial("EVERBRIGHT", 100, 250, 3.0F, 4.0F, 1);

	public static final Item.ToolMaterial corruptedPickMaterial = EnumHelper.addToolMaterial("pick_corrupted", 3, 6000, 16.0F, 6.0F, 1);
	public static final Item.ToolMaterial edenPickMaterial = EnumHelper.addToolMaterial("pick_eden", 100, 6000, 20.0F, 4.0F, 1);
	public static final Item.ToolMaterial wildPickMaterial = EnumHelper.addToolMaterial("pick_wild", 100, 6000, 28.0F, 5.0F, 1);
	public static final Item.ToolMaterial apalachiaPickMaterial = EnumHelper.addToolMaterial("pick_apalachia", 100, 6000, 40.0F, 6.0F, 1);
	public static final Item.ToolMaterial skythernPickMaterial = EnumHelper.addToolMaterial("pick_skythern", 100, 6000, 48.0F, 7.0F, 1);
	public static final Item.ToolMaterial mortumPickMaterial = EnumHelper.addToolMaterial("pick_mortum", 100, 6000, 55.0F, 8.0F, 1);
	public static final Item.ToolMaterial divinePickMaterial = EnumHelper.addToolMaterial("pick_divine", 8, 35000, 20.0F, 5.0F, 1);
	public static final Item.ToolMaterial rupeePickMaterial = EnumHelper.addToolMaterial("pick_rupee", 6, 2500, 16.0F, 4.0F, 1);
	public static final Item.ToolMaterial arlemitePickMaterial = EnumHelper.addToolMaterial("pick_arlemite", 3, 2000, 13.0F, 4.0F, 1);
	public static final Item.ToolMaterial realmitePickMaterial = EnumHelper.addToolMaterial("pick_realmite", 3, 4000, 12.0F, 3.0F, 1);
	public static final Item.ToolMaterial bedrockPickMaterial = EnumHelper.addToolMaterial("pick_bedrock", 3, 0, 9.0F, 3.0F, 1);
	public static final Item.ToolMaterial cyclopsPickMaterial = EnumHelper.addToolMaterial("pick_cyclops", 0, 0, 9.0F, 3.0F, 1);
	public static final Item.ToolMaterial corruptedAxeMaterial = EnumHelper.addToolMaterial("axe_corrupted", 2, 6000, 16.0F, 6.0F, 1);
	public static final Item.ToolMaterial edenAxeMaterial = EnumHelper.addToolMaterial("axe_eden", 2, 6000, 20.0F, 6.0F, 1);
	public static final Item.ToolMaterial wildAxeMaterial = EnumHelper.addToolMaterial("axe_wild", 2, 6000, 28.0F, 7.0F, 1);
	public static final Item.ToolMaterial apalachiaAxeMaterial = EnumHelper.addToolMaterial("axe_apalachia", 2, 6000, 40.0F, 8.0F, 1);
	public static final Item.ToolMaterial skythernAxeMaterial = EnumHelper.addToolMaterial("axe_skythern", 2, 6000, 48.0F, 9.0F, 1);
	public static final Item.ToolMaterial mortumAxeMaterial = EnumHelper.addToolMaterial("axe_mortum", 2, 6000, 55.0F, 10.0F, 1);
	public static final Item.ToolMaterial divineAxeMaterial = EnumHelper.addToolMaterial("axe_divine", 2, 35000, 20.0F, 7.0F, 1);
	public static final Item.ToolMaterial rupeeAxeMaterial = EnumHelper.addToolMaterial("axe_rupee", 1, 2500, 16.0F, 6.0F, 1);
	public static final Item.ToolMaterial arlemiteAxeMaterial = EnumHelper.addToolMaterial("axe_arlemite", 1, 2000, 13.0F, 6.0F, 1);
	public static final Item.ToolMaterial realmiteAxeMaterial = EnumHelper.addToolMaterial("axe_realmite", 1, 4000, 12.0F, 5.0F, 1);
	public static final Item.ToolMaterial bedrockAxeMaterial = EnumHelper.addToolMaterial("axe_bedrock", 1, 0, 9.0F, 5.0F, 1);
	public static final Item.ToolMaterial corruptedShovelMaterial = EnumHelper.addToolMaterial("shovel_corrupted", 2, 6000, 16.0F, 4.0F - 2.5F, 1);
	public static final Item.ToolMaterial edenShovelMaterial = EnumHelper.addToolMaterial("shovel_eden", 2, 6000, 20.0F, 4.0F - 2.5F, 1);
	public static final Item.ToolMaterial wildShovelMaterial = EnumHelper.addToolMaterial("shovel_wild", 2, 6000, 28.0F, 5.0F - 2.5F, 1);
	public static final Item.ToolMaterial apalachiaShovelMaterial = EnumHelper.addToolMaterial("shovel_apalachia", 2, 6000, 40.0F, 6.0F - 2.5F, 1);
	public static final Item.ToolMaterial skythernShovelMaterial = EnumHelper.addToolMaterial("shovel_skythern", 2, 6000, 48.0F, 7.0F - 2.5F, 1);
	public static final Item.ToolMaterial mortumShovelMaterial = EnumHelper.addToolMaterial("shovel_mortum", 2, 6000, 55.0F, 8.0F - 2.5F, 1);
	public static final Item.ToolMaterial divineShovelMaterial = EnumHelper.addToolMaterial("shovel_divine", 2, 35000, 20.0F, 5.0F - 2.5F, 1);
	public static final Item.ToolMaterial rupeeShovelMaterial = EnumHelper.addToolMaterial("shovel_rupee", 1, 2500, 16.0F, 4.0F - 2.5F, 1);
	public static final Item.ToolMaterial arlemiteShovelMaterial = EnumHelper.addToolMaterial("shovel_arlemite", 1, 2000, 13.0F, 4.0F - 2.5F, 1);
	public static final Item.ToolMaterial realmiteShovelMaterial = EnumHelper.addToolMaterial("shovel_realmite", 1, 4000, 12.0F, 3.0F - 2.5F, 1);
	public static final Item.ToolMaterial bedrockShovelMaterial = EnumHelper.addToolMaterial("shovel_bedrock", 1, 0, 9.0F, 3.0F - 2.5F, 1);
	public static final Item.ToolMaterial rupeeHoeMaterial = EnumHelper.addToolMaterial("hoe_rupee", 1, 2500, 3.0F, 2.0F, 1);
	public static final Item.ToolMaterial arlemiteHoeMaterial = EnumHelper.addToolMaterial("hoe_arlemite", 1, 3000, 4.0F, 3.0F, 1);
	public static final Item.ToolMaterial realmiteHoeMaterial = EnumHelper.addToolMaterial("hoe_realmite", 1, 4000, 5.0F, 4.0F, 1);
	public static final Item.ToolMaterial rupeeShickaxeMaterial = EnumHelper.addToolMaterial("shickaxe_rupee", 6, 0, 16.0F, 8.0F, 15);
	public static final Item.ToolMaterial arlemiteShickaxeMaterial = EnumHelper.addToolMaterial("shickaxe_arlemite", 6, 12000, 13.0F, 8.0F, 15);//.setRepairItem(new ItemStack(ModItems.ingotArlemite));
	public static final Item.ToolMaterial divineShickaxeMaterial = EnumHelper.addToolMaterial("shickaxe_divine", 8, 0, 20.0F, 9.0F, 10);

}
