modLoader = "javafml" #mandatory
loaderVersion = "[${loader_version_range},)"
license = "https://www.curseforge.com/project/363543/license"
issueTrackerURL = "https://github.com/DivineRPG/DivineRPG/issues" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG-Assets/main/divinerpg_update.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/official-divinerpg" #optional
logoFile = "logo.png" #optional
credits = "https://github.com/DivineRPG/DivineRPG-Assets/blob/main/credits.md" #optional
description = '''Adds various dimensions, weapons, and mobs'''

[[dependencies.divinerpg]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

