modLoader = "javafml"
loaderVersion = "[${loader_version_range},)"
license = "https://www.curseforge.com/project/363543/license"
issueTrackerURL = "https://github.com/DivineRPG/DivineRPG/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/DivineRPG/DivineRPG-Assets/main/divinerpg_update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/official-divinerpg"
logoFile = "logo.png"
credits = "https://github.com/DivineRPG/DivineRPG-Assets/blob/main/credits.md"
description = '''Adds various dimensions, weapons, and mobs'''

[[dependencies.divinerpg]]
modId="neoforge"
required=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
