package net.divinerpg.dimensions.arcana.components;
import java.util.Random;

import net.divinerpg.dimensions.arcana.ArcanaChunk;
import net.divinerpg.utils.blocks.ArcanaBlocks;
import net.minecraft.block.Block;

public class DungeonCeiling extends DungeonComponentBase {

    @Override
    public boolean generate(ArcanaChunk arcanaChunk, Random rand, int x, int y, int z) {

        Block dungeonBricks = ArcanaBlocks.degradedBrick;

        arcanaChunk.setBlock(x, y, z, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 1, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 2, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 3, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 4, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 5, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 6, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 7, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 8, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 9, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 10, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 11, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 12, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 13, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 14, y, z + 15, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 1, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 2, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 3, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 4, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 5, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 6, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 7, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 8, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 9, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 10, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 11, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 12, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 13, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 14, dungeonBricks);
        arcanaChunk.setBlock(x + 15, y, z + 15, dungeonBricks);
        return true;
    }
}
