package naturix.divinerpg.registry;

import naturix.divinerpg.utils.Reference;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

public class DRPGSoundHandler {

    public static SoundEvent ACID_HAG;
    public static SoundEvent ACID_HAG_HURT;
    public static SoundEvent ALICANTO;
    public static SoundEvent ALICANTO_HURT;
    public static SoundEvent ARCANIUM_SABER;
    public static SoundEvent ARCHER;
    public static SoundEvent ARID_WARRIOR;
    public static SoundEvent ARID_WARRIOR_HURT;
    public static SoundEvent AYERACO;
    public static SoundEvent AYERACO_HALF_HEALTH;
    public static SoundEvent AYERACO_HURT;
    public static SoundEvent AYERACO_PILLAR;
    public static SoundEvent AYERACO_SPAWN;
    public static SoundEvent AYERACO_TELEPORT;
    public static SoundEvent BIPHRON;
    public static SoundEvent BIPHRON_HURT;
    public static SoundEvent BLITZ;
    public static SoundEvent BOHEMITE;
    public static SoundEvent BOHEMITE_HURT;
    public static SoundEvent BUNNY;
    public static SoundEvent BUNNY_HURT;
    public static SoundEvent CADILLION;
    public static SoundEvent CEILING_EXPLOSIONS;
    public static SoundEvent CONSTRUCTOR_HURT;
    public static SoundEvent CONSTRUCTOR_PUNCH;
    public static SoundEvent CORI;
    public static SoundEvent CORI_HURT;
    public static SoundEvent CORI_IDLE;
    public static SoundEvent CORI_SHOOT;
    public static SoundEvent CRAB;
    public static SoundEvent CRAB_HURT;
    public static SoundEvent CRAWLER;
    public static SoundEvent CRAWLER_HURT;
    public static SoundEvent CROAK;
    public static SoundEvent CYCLOPS;
    public static SoundEvent CYCLOPS_HURT;
    public static SoundEvent CYMESOID;
    public static SoundEvent CYMESOID_HURT;
    public static SoundEvent DEATHCRYX;
    public static SoundEvent DEATHCRYX_HURT;
    public static SoundEvent DEATH_HOUND;
    public static SoundEvent DEATH_HOUND_HURT;
    public static SoundEvent DEEP_LAUGH;
    public static SoundEvent DEMON_DARKNESS;
    public static SoundEvent DENSOS;
    public static SoundEvent DENSOS_HURT;
    public static SoundEvent DESERT;
    public static SoundEvent DISSIMENT;
    public static SoundEvent DISSIMENT_HURT;
    public static SoundEvent DIVINE_ACCUMULATOR;
    public static SoundEvent DRAMCRYX;
    public static SoundEvent DRAMCRYX_HURT;
    public static SoundEvent DRAMIX;
    public static SoundEvent DRAMIX_HURT;
    public static SoundEvent DREAM_WRECKER;
    public static SoundEvent DREAM_WRECKER_HURT;
    public static SoundEvent DUNGEON_PRISONER;
    public static SoundEvent DUNGEON_PRISONER_CHANGE;
    public static SoundEvent DUNGEON_PRISONER_HURT;
    public static SoundEvent DUO;
    public static SoundEvent DUO_HURT;
    public static SoundEvent END;
    public static SoundEvent ENDIKU;
    public static SoundEvent ENDIKU_HURT;
    public static SoundEvent ENT;
    public static SoundEvent ENT_HURT;
    public static SoundEvent EXPLOSIONS;
    public static SoundEvent FEEL_SOUL_ARKSIANE;
    public static SoundEvent FIREFLY;
    public static SoundEvent FRACTITE;
    public static SoundEvent FRACTITE_ATTACK;
    public static SoundEvent FRACTITE_CANNON;
    public static SoundEvent FRACTITE_HURT;
    public static SoundEvent FROST;
    public static SoundEvent FROSTCLAW_CANNON;
    public static SoundEvent FROSTY;
    public static SoundEvent FROSTY_HURT;
    public static SoundEvent FROST_CANNON;
    public static SoundEvent GALROID;
    public static SoundEvent GALROID_HURT;
    public static SoundEvent GHAST_CANNON;
    public static SoundEvent GLACIDE;
    public static SoundEvent GLACIDE_HURT;
    public static SoundEvent GOLEM;
    public static SoundEvent GORGOSION;
    public static SoundEvent GORGOSION_HURT;
    public static SoundEvent GRASS;
    public static SoundEvent GRIZZLE;
    public static SoundEvent GRIZZLE_HURT;
    public static SoundEvent EHU;
    public static SoundEvent EHU_HURT;
    public static SoundEvent HASTREUS;
    public static SoundEvent HASTREUS_HURT;
    public static SoundEvent HEAL;
    public static SoundEvent HELIO;
    public static SoundEvent HELIO_HURT;
    public static SoundEvent HELL_SPIDER;
    public static SoundEvent HERBOMANCER;
    public static SoundEvent HERBOMANCER_HURT;
    public static SoundEvent HIGH_HIT;
    public static SoundEvent HISS;
    public static SoundEvent HIVE_QUEEN;
    public static SoundEvent HIVE_QUEEN_HURT;
    public static SoundEvent HOVER_STINGER;
    public static SoundEvent HOVER_STINGER_HURT;
    public static SoundEvent ICEMAN;
    public static SoundEvent ICEMAN_HURT;
    public static SoundEvent INSECT;
    public static SoundEvent JACKOMAN;
    public static SoundEvent JUNGLE;
    public static SoundEvent JUNGLE_SPIDER;
    public static SoundEvent KAROS_INTRO;
    public static SoundEvent KAROS_LAUGH;
    public static SoundEvent KAZROTIC;
    public static SoundEvent KAZROTIC_HURT;
    public static SoundEvent KING_OF_SCORCHERS;
    public static SoundEvent KING_OF_SCORCHERS_HURT;
    public static SoundEvent KOBBLIN;
    public static SoundEvent LADY_LUNA1;
    public static SoundEvent LADY_LUNA2;
    public static SoundEvent LADY_LUNA3;
    public static SoundEvent LADY_LUNA_HURT;
    public static SoundEvent LA_VEKOR;
    public static SoundEvent LHEVIA;
    public static SoundEvent LHEVIA_HURT;
    public static SoundEvent LIOPLEURODON;
    public static SoundEvent LIOPLEURODON_HURT;
    public static SoundEvent LIVESTOCK_MERCHANT;
    public static SoundEvent LIVESTOCK_MERCHANT_HURT;
    public static SoundEvent LORGA;
    public static SoundEvent LORGA_FLIGHT;
    public static SoundEvent LORGA_FLIGHT_HURT;
    public static SoundEvent LORGA_HURT;
    public static SoundEvent MADIVEL;
    public static SoundEvent MADIVEL_HURT;
    public static SoundEvent MAGE_FIRE;
    public static SoundEvent MANDRAGORA;
    public static SoundEvent MEET_DOOM;
    public static SoundEvent MEGALITH;
    public static SoundEvent MEGALITH_HURT;
    public static SoundEvent MUCKY;
    public static SoundEvent NESRO;
    public static SoundEvent NESRO_HURT;
    public static SoundEvent NOBODY_CAN_DEFEAT;
    public static SoundEvent OCEAN;
    public static SoundEvent PARASECTA;
    public static SoundEvent PARASECTA_HURT;
    public static SoundEvent PHASER;
    public static SoundEvent QUADRO_DIE_BEFORE;
    public static SoundEvent QUADRO_ENOUGH;
    public static SoundEvent QUADRO_INCOMING_PUNCH;
    public static SoundEvent QUADRO_IS_NEXT;
    public static SoundEvent QUADRO_KILL_MINE;
    public static SoundEvent QUADRO_MY_KILL;
    public static SoundEvent QUADRO_NO_DIE;
    public static SoundEvent QUADRO_SIT_DOWN;
    public static SoundEvent QUADRO_TASTE_FIST;
    public static SoundEvent RAGLOK_AVENGE;
    public static SoundEvent RAGLOK_AWAKEN;
    public static SoundEvent RAGLOK_DARK;
    public static SoundEvent RAGLOK_GUARDIAN;
    public static SoundEvent RAGLOK_NOTHING;
    public static SoundEvent RAGLOK_RAIN;
    public static SoundEvent RAINBOUR;
    public static SoundEvent RAINBOUR_HURT;
    public static SoundEvent RAZORBACK;
    public static SoundEvent RAZORBACK_HURT;
    public static SoundEvent REFLECTOR;
    public static SoundEvent REYVOR;
    public static SoundEvent REYVOR_HURT;
    public static SoundEvent ROAMER;
    public static SoundEvent ROAMER_HURT;
    public static SoundEvent ROAR;
    public static SoundEvent ROLLUM;
    public static SoundEvent ROLLUM_HURT;
    public static SoundEvent ROTATICK;
    public static SoundEvent ROTATICK_HURT;
    public static SoundEvent SAGUARO_WORM;
    public static SoundEvent SCORCHER;
    public static SoundEvent SERENADE;
    public static SoundEvent SHADAHIER;
    public static SoundEvent SHADAHIER_HURT;
    public static SoundEvent SHADOW_SABER;
    public static SoundEvent SHARK;
    public static SoundEvent SHARK_HURT;
    public static SoundEvent SOUND_OF_CAROLS;
    public static SoundEvent SOUND_OF_MUSIC;
    public static SoundEvent SPARKLER;
    public static SoundEvent STAFF;
    public static SoundEvent STARLIGHT;
    public static SoundEvent STOP_AT_ONCE;
    public static SoundEvent THE_EYE;
    public static SoundEvent THE_EYE_HURT;
    public static SoundEvent TOCAXIN;
    public static SoundEvent TOCAXIN_HURT;
    public static SoundEvent TRY_YOUR_BEST;
    public static SoundEvent VARAAK;
    public static SoundEvent VARAAK_HURT;
    public static SoundEvent VEREK;
    public static SoundEvent VEREK_HURT;
    public static SoundEvent VERMENOUS;
    public static SoundEvent VERMENOUS_HURT;
    public static SoundEvent VETHEA_BOW;
    public static SoundEvent WHALE;
    public static SoundEvent WHALE_HURT;
    public static SoundEvent WILDFIRE;
    public static SoundEvent WILDFIRE_HURT;
    public static SoundEvent WRAITH;
    public static SoundEvent WRAITH_HURT;
    public static SoundEvent WRECK_INTRO;
    public static SoundEvent WRECK_SPEED;
    public static SoundEvent WRECK_STRENGTH;
    public static SoundEvent YOU_CANT_KILL_ME;
    public static SoundEvent ZONE;
    public static SoundEvent ZONE_HURT;
    public static SoundEvent ZORAGON;
    public static SoundEvent ZORAGON_HURT;

    //Music
    public static SoundEvent ICEIKA_MUSIC;

	public static void init() {
		ACID_HAG = registerSounds("acid_hag");
        ACID_HAG_HURT = registerSounds("acid_hag_hurt");
        ALICANTO = registerSounds("alicanto");
        ALICANTO_HURT = registerSounds("alicanto_hurt");
        ARCANIUM_SABER = registerSounds("arcanium_saber");
        ARCHER = registerSounds("archer");
        ARID_WARRIOR = registerSounds("arid_warrior");
        ARID_WARRIOR_HURT = registerSounds("arid_warrior_hurt");
        AYERACO = registerSounds("ayeraco");
        AYERACO_HALF_HEALTH = registerSounds("ayeraco_half_health");
        AYERACO_HURT = registerSounds("ayeraco_hurt");
        AYERACO_PILLAR = registerSounds("ayeraco_pillar");
        AYERACO_SPAWN = registerSounds("ayeraco_spawn");
        AYERACO_TELEPORT = registerSounds("ayeraco_teleport");
        BIPHRON = registerSounds("biphron");
        BIPHRON_HURT = registerSounds("biphron_hurt");
        BLITZ = registerSounds("blitz");
        BOHEMITE = registerSounds("bohemite");
        BOHEMITE_HURT = registerSounds("bohemite_hurt");
        BUNNY = registerSounds("bunny");
        BUNNY_HURT = registerSounds("bunny_hurt");
        CADILLION = registerSounds("cadillion");
        CEILING_EXPLOSIONS = registerSounds("ceiling_explosions");
        CONSTRUCTOR_HURT = registerSounds("constructor_hurt");
        CONSTRUCTOR_PUNCH = registerSounds("constructor_punch");
        CORI = registerSounds("cori");
        CORI_HURT = registerSounds("cori_hurt");
        CORI_IDLE = registerSounds("cori_idle");
        CORI_SHOOT = registerSounds("cori_shoot");
        CRAB = registerSounds("crab");
        CRAB_HURT = registerSounds("crab_hurt");
        CRAWLER = registerSounds("crawler");
        CRAWLER_HURT = registerSounds("crawler_hurt");
        CROAK = registerSounds("croak");
        CYCLOPS = registerSounds("cyclops");
        CYCLOPS_HURT = registerSounds("cyclops_hurt");
        CYMESOID = registerSounds("cymesoid");
        CYMESOID_HURT = registerSounds("cymesoid_hurt");
        DEATHCRYX = registerSounds("deathcryx");
        DEATHCRYX_HURT = registerSounds("deathcryx_hurt");
        DEATH_HOUND = registerSounds("death_hound");
        DEATH_HOUND_HURT = registerSounds("death_hound_hurt");
        DEEP_LAUGH = registerSounds("deep_laugh");
        DEMON_DARKNESS = registerSounds("demon_darkness");
        DENSOS = registerSounds("densos");
        DENSOS_HURT = registerSounds("densos_hurt");
        DESERT = registerSounds("desert");
        DISSIMENT = registerSounds("dissiment");
        DISSIMENT_HURT = registerSounds("dissiment_hurt");
        DIVINE_ACCUMULATOR = registerSounds("divine_accumulator");
        DRAMCRYX = registerSounds("dramcryx");
        DRAMCRYX_HURT = registerSounds("dramcryx_hurt");
        DRAMIX = registerSounds("dramix");
        DRAMIX_HURT = registerSounds("dramix_hurt");
        DREAM_WRECKER = registerSounds("dream_wrecker");
        DREAM_WRECKER_HURT = registerSounds("dream_wrecker_hurt");
        DUNGEON_PRISONER = registerSounds("dungeon_prisoner");
        DUNGEON_PRISONER_CHANGE = registerSounds("dungeon_prisoner_change");
        DUNGEON_PRISONER_HURT = registerSounds("dungeon_prisoner_hurt");
        DUO = registerSounds("duo");
        DUO_HURT = registerSounds("duo_hurt");
        END = registerSounds("end");
        ENDIKU = registerSounds("endiku");
        ENDIKU_HURT = registerSounds("endiku_hurt");
        ENT = registerSounds("ent");
        ENT_HURT = registerSounds("ent_hurt");
        EXPLOSIONS = registerSounds("explosions");
        FEEL_SOUL_ARKSIANE = registerSounds("feel_soul_arksiane");
        FIREFLY = registerSounds("firefly");
        FRACTITE = registerSounds("fractite");
        FRACTITE_ATTACK = registerSounds("fractite_attack");
        FRACTITE_CANNON = registerSounds("fractite_cannon");
        FRACTITE_HURT = registerSounds("fractite_hurt");
        FROST = registerSounds("frost");
        FROSTCLAW_CANNON = registerSounds("frostclaw_cannon");
        FROSTY = registerSounds("frosty");
        FROSTY_HURT = registerSounds("frosty_hurt");
        FROST_CANNON = registerSounds("frost_cannon");
        GALROID = registerSounds("galroid");
        GALROID_HURT = registerSounds("galroid_hurt");
        GHAST_CANNON = registerSounds("ghast_cannon");
        GLACIDE = registerSounds("glacide");
        GLACIDE_HURT = registerSounds("glacide_hurt");
        GOLEM = registerSounds("golem");
        GORGOSION = registerSounds("gorgosion");
        GORGOSION_HURT = registerSounds("gorgosion_hurt");
        GRASS = registerSounds("grass");
        GRIZZLE = registerSounds("grizzle");
        GRIZZLE_HURT = registerSounds("grizzle_hurt");
        EHU = registerSounds("ehu");
        EHU_HURT = registerSounds("ehu_hurt");
        HASTREUS = registerSounds("hastreus");
        HASTREUS_HURT = registerSounds("hastreus_hurt");
        HEAL = registerSounds("heal");
        HELIO = registerSounds("helio");
        HELIO_HURT = registerSounds("helio_hurt");
        HELL_SPIDER = registerSounds("hell_spider");
        HERBOMANCER = registerSounds("herbomancer");
        HERBOMANCER_HURT = registerSounds("herbomancer_hurt");
        HIGH_HIT = registerSounds("high_hit");
        HISS = registerSounds("hiss");
        HIVE_QUEEN = registerSounds("hive_queen");
        HIVE_QUEEN_HURT = registerSounds("hive_queen_hurt");
        HOVER_STINGER = registerSounds("hover_stinger");
        HOVER_STINGER_HURT = registerSounds("hover_stinger_hurt");
        ICEMAN = registerSounds("iceman");
        ICEMAN_HURT = registerSounds("iceman_hurt");
        INSECT = registerSounds("insect");
        JACKOMAN = registerSounds("jackoman");
        JUNGLE = registerSounds("jungle");
        JUNGLE_SPIDER = registerSounds("jungle_spider");
        KAROS_INTRO = registerSounds("karos_intro");
        KAROS_LAUGH = registerSounds("karos_laugh");
        KAZROTIC = registerSounds("kazrotic");
        KAZROTIC_HURT = registerSounds("kazrotic_hurt");
        KING_OF_SCORCHERS = registerSounds("king_of_scorchers");
        KING_OF_SCORCHERS_HURT = registerSounds("king_of_scorchers_hurt");
        KOBBLIN = registerSounds("kobblin");
        LADY_LUNA1 = registerSounds("lady_luna1");
        LADY_LUNA2 = registerSounds("lady_luna2");
        LADY_LUNA3 = registerSounds("lady_luna3");
        LADY_LUNA_HURT = registerSounds("lady_luna_hurt");
        LA_VEKOR = registerSounds("la_vekor");
        LHEVIA = registerSounds("lhevia");
        LHEVIA_HURT = registerSounds("lhevia_hurt");
        LIOPLEURODON = registerSounds("liopleurodon");
        LIOPLEURODON_HURT = registerSounds("liopleurodon_hurt");
        LIVESTOCK_MERCHANT = registerSounds("livestock_merchant");
        LIVESTOCK_MERCHANT_HURT = registerSounds("livestock_merchant_hurt");
        LORGA = registerSounds("lorga");
        LORGA_FLIGHT = registerSounds("lorga_flight");
        LORGA_FLIGHT_HURT = registerSounds("lorga_flight_hurt");
        LORGA_HURT = registerSounds("lorga_hurt");
        MADIVEL = registerSounds("madivel");
        MADIVEL_HURT = registerSounds("madivel_hurt");
        MAGE_FIRE = registerSounds("mage_fire");
        MANDRAGORA = registerSounds("mandragora");
        MEET_DOOM = registerSounds("meet_doom");
        MEGALITH = registerSounds("megalith");
        MEGALITH_HURT = registerSounds("megalith_hurt");
        MUCKY = registerSounds("mucky");
        NESRO = registerSounds("nesro");
        NESRO_HURT = registerSounds("nesro_hurt");
        NOBODY_CAN_DEFEAT = registerSounds("nobody_can_defeat");
        OCEAN = registerSounds("ocean");
        PARASECTA = registerSounds("parasecta");
        PARASECTA_HURT = registerSounds("parasecta_hurt");
        PHASER = registerSounds("phaser");
        QUADRO_DIE_BEFORE = registerSounds("quadro_die_before");
        QUADRO_ENOUGH = registerSounds("quadro_enough");
        QUADRO_INCOMING_PUNCH = registerSounds("quadro_incoming_punch");
        QUADRO_IS_NEXT = registerSounds("quadro_is_next");
        QUADRO_KILL_MINE = registerSounds("quadro_kill_mine");
        QUADRO_MY_KILL = registerSounds("quadro_my_kill");
        QUADRO_NO_DIE = registerSounds("quadro_no_die");
        QUADRO_SIT_DOWN = registerSounds("quadro_sit_down");
        QUADRO_TASTE_FIST = registerSounds("quadro_taste_fist");
        RAGLOK_AVENGE = registerSounds("raglok_avenge");
        RAGLOK_AWAKEN = registerSounds("raglok_awaken");
        RAGLOK_DARK = registerSounds("raglok_dark");
        RAGLOK_GUARDIAN = registerSounds("raglok_guardian");
        RAGLOK_NOTHING = registerSounds("raglok_nothing");
        RAGLOK_RAIN = registerSounds("raglok_rain");
        RAINBOUR = registerSounds("rainbour");
        RAINBOUR_HURT = registerSounds("rainbour_hurt");
        RAZORBACK = registerSounds("razorback");
        RAZORBACK_HURT = registerSounds("razorback_hurt");
        REFLECTOR = registerSounds("reflector");
        REYVOR = registerSounds("reyvor");
        REYVOR_HURT = registerSounds("reyvor_hurt");
        ROAMER = registerSounds("roamer");
        ROAMER_HURT = registerSounds("roamer_hurt");
        ROAR = registerSounds("roar");
        ROLLUM = registerSounds("rollum");
        ROLLUM_HURT = registerSounds("rollum_hurt");
        ROTATICK = registerSounds("rotatick");
        ROTATICK_HURT = registerSounds("rotatick_hurt");
        SAGUARO_WORM = registerSounds("saguaro_worm");
        SCORCHER = registerSounds("scorcher");
        SERENADE = registerSounds("serenade");
        SHADAHIER = registerSounds("shadahier");
        SHADAHIER_HURT = registerSounds("shadahier_hurt");
        SHADOW_SABER = registerSounds("shadow_saber");
        SHARK = registerSounds("shark");
        SHARK_HURT = registerSounds("shark_hurt");
        SOUND_OF_CAROLS = registerSounds("sound_of_carols");
        SOUND_OF_MUSIC = registerSounds("sound_of_music");
        SPARKLER = registerSounds("sparkler");
        STAFF = registerSounds("staff");
        STARLIGHT = registerSounds("starlight");
        STOP_AT_ONCE = registerSounds("stop_at_once");
        THE_EYE = registerSounds("the_eye");
        THE_EYE_HURT = registerSounds("the_eye_hurt");
        TOCAXIN = registerSounds("tocaxin");
        TOCAXIN_HURT = registerSounds("tocaxin_hurt");
        TRY_YOUR_BEST = registerSounds("try_your_best");
        VARAAK = registerSounds("varaak");
        VARAAK_HURT = registerSounds("varaak_hurt");
        VEREK = registerSounds("verek");
        VEREK_HURT = registerSounds("verek_hurt");
        VERMENOUS = registerSounds("vermenous");
        VERMENOUS_HURT = registerSounds("vermenous_hurt");
        VETHEA_BOW = registerSounds("vethea_bow");
        WHALE = registerSounds("whale");
        WHALE_HURT = registerSounds("whale_hurt");
        WILDFIRE = registerSounds("wildfire");
        WILDFIRE_HURT = registerSounds("wildfire_hurt");
        WRAITH = registerSounds("wraith");
        WRAITH_HURT = registerSounds("wraith_hurt");
        WRECK_INTRO = registerSounds("wreck_intro");
        WRECK_SPEED = registerSounds("wreck_speed");
        WRECK_STRENGTH = registerSounds("wreck_strength");
        YOU_CANT_KILL_ME = registerSounds("you_cant_kill_me");
        ZONE = registerSounds("zone");
        ZONE_HURT = registerSounds("zone_hurt");
        ZORAGON = registerSounds("zoragon");
        ZORAGON_HURT = registerSounds("zoragon_hurt");

        ICEIKA_MUSIC = registerSounds("iceika_music");
	}

    private static SoundEvent registerSounds(String name){
        ResourceLocation location = new ResourceLocation(Reference.MODID, name);
        SoundEvent e = new SoundEvent(location);
        e.setRegistryName(name);
        ForgeRegistries.SOUND_EVENTS.register(e);
        return e;
    }
}