package naturix.divinerpg.registry;

import java.util.ArrayList;
import java.util.List;

import naturix.divinerpg.objects.blocks.BaseStatue;
import naturix.divinerpg.objects.blocks.BeaconBaseBase;
import naturix.divinerpg.objects.blocks.BedBase;
import naturix.divinerpg.objects.blocks.BlockBase;
import naturix.divinerpg.objects.blocks.BlockModSpawner;
import naturix.divinerpg.objects.blocks.BlockOre;
import naturix.divinerpg.objects.blocks.DirtBase;
import naturix.divinerpg.objects.blocks.FireBase;
import naturix.divinerpg.objects.blocks.FrostedGlass;
import naturix.divinerpg.objects.blocks.GrassBase;
import naturix.divinerpg.objects.blocks.LampBase;
import naturix.divinerpg.objects.blocks.LeavesBase;
import naturix.divinerpg.objects.blocks.LogBase;
import naturix.divinerpg.objects.blocks.Spike;
import naturix.divinerpg.objects.blocks.SteelDoor;
import naturix.divinerpg.objects.blocks.TorchBase;
import naturix.divinerpg.objects.blocks.VineBase;
import naturix.divinerpg.objects.blocks.arcana.Acceleron;
import naturix.divinerpg.objects.blocks.arcana.BlockElevantium;
import naturix.divinerpg.objects.blocks.arcana.DemonFurnace;
import naturix.divinerpg.objects.blocks.arcana.HeatTrap;
import naturix.divinerpg.objects.blocks.arcana.MoltenFurnace;
import naturix.divinerpg.objects.blocks.arcana.OceanfireFurnace;
import naturix.divinerpg.objects.blocks.arcana.StarBridge;
import naturix.divinerpg.objects.blocks.arcana.StarBridgeOn;
import naturix.divinerpg.objects.blocks.arcana.WhitefireFurnace;
import naturix.divinerpg.objects.blocks.fluid.BlockTar;
import naturix.divinerpg.objects.blocks.iceika.CandyCane;
import naturix.divinerpg.objects.blocks.iceika.CoalstoneFurnace;
import naturix.divinerpg.objects.blocks.iceika.IceikaChest;
import naturix.divinerpg.objects.blocks.iceika.WorkshopCarpet;
import naturix.divinerpg.objects.blocks.iceika.XMasLights;
import naturix.divinerpg.objects.blocks.portal.ApalachiaPortal;
import naturix.divinerpg.objects.blocks.portal.EdenBlock;
import naturix.divinerpg.objects.blocks.portal.IceikaPortal;
import naturix.divinerpg.objects.blocks.portal.MortumPortal;
import naturix.divinerpg.objects.blocks.portal.SkythernPortal;
import naturix.divinerpg.objects.blocks.portal.WildWoodPortal;
import naturix.divinerpg.objects.blocks.sapling.SaplingApalachia;
import naturix.divinerpg.objects.blocks.sapling.SaplingEden;
import naturix.divinerpg.objects.blocks.sapling.SaplingMortum;
import naturix.divinerpg.objects.blocks.sapling.SaplingSkythern;
import naturix.divinerpg.objects.blocks.sapling.SaplingWildwood;
import naturix.divinerpg.objects.blocks.tile.block.AltarDramix;
import naturix.divinerpg.objects.blocks.tile.block.AltarParasecta;
import naturix.divinerpg.objects.blocks.tile.block.BlockAyeracoBeam;
import naturix.divinerpg.objects.blocks.tile.block.BlockAyeracoSpawn;
import naturix.divinerpg.objects.blocks.vethia.Acid;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;

public class ModBlocks {
	public static final List<Block> BLOCKS = new ArrayList<Block>();

	public static final Block oreArlemite = new BlockOre("ore_arlemite");
	public static final Block oreapalachia = new BlockBase("ore_apalachia");
	public static final Block orebloodgem = new BlockBase("ore_bloodgem");
	public static final Block oreMortum = new BlockBase("ore_mortum");
	public static final Block oreNetherite = new BlockBase("ore_netherite");
	public static final Block oreRupee = new BlockOre("ore_rupee");
	public static final Block oreSkythern = new BlockBase("ore_skythern");
	public static final Block oreWildwood = new BlockBase("ore_wildwood");
	public static final Block oreRealmite = new BlockOre("ore_realmite");
	public static final Block oreEden = new BlockBase("ore_eden");
	public static final Block blockArlemite = new BeaconBaseBase("block_arlemite");
	public static final Block blockApalachia = new BeaconBaseBase("block_apalachia");
	public static final Block blockMortum = new BeaconBaseBase("block_mortum");
	public static final Block blockRupee = new BeaconBaseBase("block_rupee");
	public static final Block blockSkythern = new BeaconBaseBase("block_skythern");
	public static final Block blockWildWood = new BeaconBaseBase("block_wildwood");
	public static final Block blockRealmite = new BeaconBaseBase("block_realmite");
	public static final Block blockEden = new BeaconBaseBase("block_eden");
	public static final Block blockBloodGem = new BeaconBaseBase("block_bloodgem");
	public static final Block blockNetherite = new BeaconBaseBase("block_netherite");
	public static final Block oreArcanium = new BlockBase("ore_arcanium");
	public static final Block blockAquaLamp = new LampBase(Material.ICE, "block_aqua_lamp");
	public static final Block blockArlemiteLamp = new LampBase(Material.ICE, "block_arlemite_lamp");
	public static final Block blockBlazeLamp = new LampBase(Material.ICE, "block_blaze_lamp");
	public static final Block blockCellLamp = new LampBase(Material.ICE, "block_cell_lamp");
	public static final Block blockDiamondLamp = new LampBase(Material.ICE, "block_diamond_lamp");
	public static final Block blockDivineLamp = new LampBase(Material.ICE, "block_divine_lamp");
	public static final Block blockDrakenLamp = new LampBase(Material.ICE, "block_draken_lamp");
	public static final Block blockDreamLamp = new LampBase(Material.ICE, "block_dream_lamp");
	public static final Block blockDungeonLamp = new LampBase(Material.ICE, "block_dungeon_lamp");
	public static final Block blockEdenLamp = new LampBase(Material.ICE, "block_eden_lamp");
	public static final Block blockEnderLamp = new LampBase(Material.ICE, "block_ender_lamp");
	public static final Block blockGoldLamp = new LampBase(Material.ICE, "block_gold_lamp");
	public static final Block blockIceLamp = new LampBase(Material.ICE, "block_ice_lamp");
	public static final Block blockJungleLamp = new LampBase(Material.ICE, "block_jungle_lamp");
	public static final Block blockKrakenLamp = new LampBase(Material.ICE, "block_kraken_lamp");
	public static final Block blockLapisLazuliLamp = new LampBase(Material.ICE, "block_lapis_lazuli_lamp");
	public static final Block blockLavaLamp = new LampBase(Material.ICE, "block_lava_lamp");
	public static final Block blockMilkyLamp = new LampBase(Material.ICE, "block_milky_lamp");
	public static final Block blockMoltenLamp = new LampBase(Material.ICE, "block_molten_lamp");
	public static final Block blockNetheriteLamp = new LampBase(Material.ICE, "block_netherite_lamp");
	public static final Block blockRealmiteLamp = new LampBase(Material.ICE, "block_realmite_lamp");
	public static final Block blockRedstoneLamp = new LampBase(Material.ICE, "block_redstone_lamp");
	public static final Block blockRupeeLamp = new LampBase(Material.ICE, "block_rupee_lamp");
	public static final Block blockSlimeLamp = new LampBase(Material.ICE, "block_slime_lamp");
	public static final Block blockTerranLamp = new LampBase(Material.ICE, "block_terran_lamp");
	public static final Block blockVillageLamp = new LampBase(Material.ICE, "block_village_lamp");
	public static final Block blockWorkshopLamp = new LampBase(Material.ICE, "block_workshop_lamp");
	public static final Block divineLog = new LogBase("log_divine");
	public static final Block dreamLog = new LogBase("log_dream");
	public static final Block frozenLog = new LogBase("log_frozen");
	public static final Block hyreLog = new LogBase("log_hyre");
	public static final Block mintLog = new LogBase("log_mint");
	public static final Block edenLog = new LogBase("log_eden");
	public static final Block fireLog = new LogBase("log_fire");
	public static final Block wildwoodLog = new LogBase("log_wildwood");
	public static final Block apalachiaLog = new LogBase("log_apalachia");
	public static final Block skythernLog = new LogBase("log_skythern");
	public static final Block mortumLog = new LogBase("log_mortum");
	public static final Block divineLeaves = new LeavesBase("leaves_divine");
	public static final Block dreamLeaves = new LeavesBase("leaves_dream");
	public static final Block hyreLeaves = new LeavesBase("leaves_hyre");
	public static final Block mintLeaves = new LeavesBase("leaves_mint");
	public static final Block edenLeaves = new LeavesBase("leaves_eden", ModBlocks.edenSapling);
	public static final Block fireLeaves = new LeavesBase("leaves_fire");
	public static final Block wildwoodLeaves = new LeavesBase("leaves_wildwood", ModBlocks.wildwoodSapling);
	public static final Block apalachiaLeaves = new LeavesBase("leaves_apalachia", ModBlocks.apalachiaSapling);
	public static final Block skythernLeaves = new LeavesBase("leaves_skythern", ModBlocks.skythernSapling);
	public static final Block mortumLeaves = new LeavesBase("leaves_mortum", ModBlocks.mortumSapling);
	public static final Block torchSkeleton = new TorchBase(Material.CIRCUITS, "torch_skeleton");
	public static final Block torchAqua = new TorchBase(Material.CIRCUITS, "torch_aqua");
	public static final Block torchEden = new TorchBase(Material.CIRCUITS, "torch_eden");
	public static final Block torchArcanium = new TorchBase(Material.CIRCUITS, "torch_arcanium");
	public static final Block apalachiaSapling = new SaplingApalachia("sapling_apalachia");
	public static final Block edenSapling = new SaplingEden("sapling_eden");
	public static final Block wildwoodSapling = new SaplingWildwood("sapling_wildwood");
	public static final Block skythernSapling = new SaplingSkythern("sapling_skythern");
	public static final Block mortumSapling = new SaplingMortum("sapling_mortum");
	public static final Block watcherStatue = new BaseStatue("statue_watcher");
	public static final Block ancientEntityStatue = new BaseStatue("statue_anciententity");
	public static final Block ayeracoHordeStatue = new BaseStatue("statue_ayeracohorde");
	public static final Block densosStatue = new BaseStatue("statue_densos");
	public static final Block dexZichileStatue = new BaseStatue("statue_dexzichile");
	public static final Block dramixStatue = new BaseStatue("statue_dramix");
	public static final Block kingScorcherStatue = new BaseStatue("statue_kingscorcher");
	public static final Block reyvorStatue = new BaseStatue("statue_reyvor");
	public static final Block soulFiendStatue = new BaseStatue("statue_soulfiend");
	public static final Block twilightDemonStatue = new BaseStatue("statue_twilightdemon");
	public static final Block vamacheronStatue = new BaseStatue("statue_vamacheron");
	// public static BedBase nightmarebed = new BedBase("bed_nightmare");
	public static final Block altarDramix = new AltarDramix("altar_dramix");
	public static final Block altarParasecta = new AltarParasecta("altar_parasecta");
	public static final Block heatTrap = new HeatTrap("heat_trap");
	public static final Block heatTrapOn = new HeatTrap("heat_trap_on");
	public static final Block spikeCold = new Spike("spike_cold");
	public static final Block spikeHot = new Spike("spike_hot");
	public static final Block acidBacteria = new Acid("acid_bacterial", false, true);
	public static final Block acidBlock = new Acid("acid_block", true, false);
	public static final Block acidLunic = new Acid("acid_lunic", true, true);
	public static final Block acceleron = new Acceleron("acceleron");
	public static final Block grassArcana = new GrassBase("grass_arcana");
	public static final EdenBlock portalEden = new EdenBlock("portal_eden", ModBlocks.blueFire);
	public static final Block blueFire = new FireBase("fire_blue");
	public static final Block rockDivine = new BlockBase("rock_divine");
	public static final Block rockTwilight = new BlockBase("rock_twilight");
	public static final Block dirtEden = new DirtBase("dirt_eden");
	public static final Block grassEden = new GrassBase("grass_eden");
	public static final Block bedDream = new BedBase("bed_dream");
	public static final Block grassWild = new GrassBase("grass_wildwood");
	public static final Block dirtWild = new BlockBase("dirt_wild");
	public static final WildWoodPortal portalWild = new WildWoodPortal("portal_wild", ModBlocks.blueFire);
	public static final Block vineWild = new VineBase("vine_wildwood");
	public static final Block grassApalachia = new GrassBase("grass_apalachia");
	public static final Block dirtApalachia = new BlockBase(Material.GROUND, "dirt_apalachia");
	public static final ApalachiaPortal portalApalachia = new ApalachiaPortal("portal_apalachia", ModBlocks.blueFire);
	public static final Block grassSkythern = new GrassBase("grass_skythern");
	public static final Block dirtSkythern = new BlockBase("dirt_skythern");
	public static final SkythernPortal portalSkythern = new SkythernPortal("portal_skythern", ModBlocks.blueFire);
	public static final Block grassMortum = new GrassBase("grass_mortum");
	public static final Block dirtMortum = new BlockBase("dirt_mortum");
	public static final MortumPortal portalMortum = new MortumPortal("portal_mortum", ModBlocks.blueFire);
	public static final Block grassIceika = new GrassBase("grass_iceika");
	public static final IceikaPortal portalIceika = new IceikaPortal("portal_iceika", ModBlocks.blueFire);
	public static final Block stoneFrozen = new BlockBase(Material.ROCK, "stone_frozen");
	public static final Block stoneIcy = new BlockBase("stone_icy");
	public static final Block bricksIceika = new BlockBase("bricks_iceika");
	public static final Block brittleLeaves = new LeavesBase("leaves_brittle");
	public static final Block spawnerArcher = new BlockModSpawner("spawner_archer", "frost_archer");
	public static final Block spawnerRollum = new BlockModSpawner("spawner_rollum", "rollum");
	public static final Block tar = new BlockTar();
	public static final Block coalStone = new BlockBase("coalstone");
	public static final Block snowBricks = new BlockBase("snow_bricks");
	public static final Block workshopBookcase = new BlockBase("workshop_bookcase");
	public static final Block frostedGlass = new FrostedGlass("frosted_glass");
	public static final Block workshopCarpet = new WorkshopCarpet("workshop_carpet");
	public static final Block coalstoneFurnace = new CoalstoneFurnace("coalstone_furnace", false);
	public static final Block coalstoneFurnaceOn = new CoalstoneFurnace("coalstone_furnace_on", true);
	public static final Block moltenFurnace = new MoltenFurnace("molten_furnace", false);
	public static final Block moltenFurnaceOn = new MoltenFurnace("molten_furnace_on", true);
	public static final Block oceanfireFurnace = new OceanfireFurnace("oceanfire_furnace", false);
	public static final Block oceanfireFurnaceOn = new OceanfireFurnace("oceanfire_furnace_on", true);
	public static final Block whitefireFurnace = new WhitefireFurnace("whitefire_furnace", false);
	public static final Block whitefireFurnaceOn = new WhitefireFurnace("whitefire_furnace_on", true);
	public static final Block demonFurnace = new DemonFurnace("demon_furnace", false);
	public static final Block demonFurnaceOn = new DemonFurnace("demon_furnace_on", true);
	public static final Block iceikaChest = new IceikaChest("iceika_chest", true);
	public static final Block decorativeIceikaChest = new IceikaChest("decorative_iceika_chest", false);
	public static final Block spawnerSeimer = new BlockModSpawner("spawner_seimer", "seimer");
	public static final Block spawnerFyracryx = new BlockModSpawner("spawner_fyracryx", "fyracryx");
	public static final Block spawnerParatiku = new BlockModSpawner("spawner_paratiku", "paratiku");
	public static final Block spawnerRejuvGolem = new BlockModSpawner("spawner_rejuv", "rejuv_golem");
	public static final Block dirtArcana = new BlockBase("dirt_arcana");
	public static final Block railsArcana = new BlockBase("rails_arcana");
	public static final Block tubesArcana = new BlockBase("tube_arcana");
	public static final Block greenlightFurnace = new BlockBase("greenlight_furnace");
	public static final Block moonlightFurnace = new BlockBase("moonlight_furnace");
	public static final Block elevantium = new BlockElevantium("elevantium");
	public static final Block divineMossStone = new BlockBase("divine_moss_stone");
	public static final Block barredDoor = new BlockBase("barred_door");
	public static final Block bricksDreamLight = new BlockBase("bricks_dream_light");
	public static final Block bricksDreamDark = new BlockBase("bricks_dream_dark");
	public static final Block bricksDreamRed = new BlockBase("bricks_dream_red");
	public static final Block dirtDream = new BlockBase("dirt_dream");
	public static final Block glassSmooth = new FrostedGlass("glass_smooth");
	public static final Block firelight = new BlockBase("firelight");
	public static final Block starBridge = new StarBridge("star_bridge");
	public static final Block starBridgeOn = new StarBridgeOn("star_bridge_on");
	public static final Block greenXMasLights = new XMasLights("green_xmas_lights");
	public static final Block redXMasLights = new XMasLights("red_xmas_lights");
	public static final Block yellowXMasLights = new XMasLights("yellow_xmas_lights");
	public static final Block blueXMasLights = new XMasLights("blue_xmas_lights");
	public static final Block purpleXMasLights = new XMasLights("purple_xmas_lights");
	public static final Block candyCane = new CandyCane("candy_cane");

	// Has a unique class because i dont have a method for universal itemblocks for
	// doors - LiteWolf101
	public static final Block steelDoor = new SteelDoor("steel_door", Material.ANVIL);

	public static final Block ayeracoBeamBlue = new BlockAyeracoBeam("ayeracoBeamBlue", "blue");
	public static final Block ayeracoBeamGreen = new BlockAyeracoBeam("ayeracoBeamGreen", "green");
	public static final Block ayeracoBeamRed = new BlockAyeracoBeam("ayeracoBeamRed", "red");
	public static final Block ayeracoBeamYellow = new BlockAyeracoBeam("ayeracoBeamYellow", "yellow");
	public static final Block ayeracoBeamPurple = new BlockAyeracoBeam("ayeracoBeamPurple", "purple");
	public static final Block ayeracoSpawn = new BlockAyeracoSpawn();
}