package net.divinerpg.utils.entities;

import net.divinerpg.entities.twilight.EntityAngryBunny;
import net.divinerpg.entities.twilight.EntityApalachiaArcher;
import net.divinerpg.entities.twilight.EntityApalachiaCadillion;
import net.divinerpg.entities.twilight.EntityApalachiaGolem;
import net.divinerpg.entities.twilight.EntityApalachiaTomo;
import net.divinerpg.entities.twilight.EntityApalachiaWarrior;
import net.divinerpg.entities.twilight.EntityBaslisk;
import net.divinerpg.entities.twilight.EntityBunny;
import net.divinerpg.entities.twilight.EntityDensos;
import net.divinerpg.entities.twilight.EntityEdenCadillion;
import net.divinerpg.entities.twilight.EntityEdenCori;
import net.divinerpg.entities.twilight.EntityEdenTomo;
import net.divinerpg.entities.twilight.EntityKarot;
import net.divinerpg.entities.twilight.EntityMadivel;
import net.divinerpg.entities.twilight.EntityMoonWolf;
import net.divinerpg.entities.twilight.EntityMortumCadillion;
import net.divinerpg.entities.twilight.EntityMortumDemon;
import net.divinerpg.entities.twilight.EntityNesro;
import net.divinerpg.entities.twilight.EntityReyvor;
import net.divinerpg.entities.twilight.EntitySamek;
import net.divinerpg.entities.twilight.EntitySkythernArcher;
import net.divinerpg.entities.twilight.EntitySkythernCori;
import net.divinerpg.entities.twilight.EntitySkythernFiend;
import net.divinerpg.entities.twilight.EntitySkythernGolem;
import net.divinerpg.entities.twilight.EntitySoulFiend;
import net.divinerpg.entities.twilight.EntitySoulStealer;
import net.divinerpg.entities.twilight.EntityTwilightDemon;
import net.divinerpg.entities.twilight.EntityVamacheron;
import net.divinerpg.entities.twilight.EntityVerek;
import net.divinerpg.entities.twilight.EntityWildWoodGolem;
import net.divinerpg.entities.twilight.EntityWildWoodTomo;
import net.divinerpg.entities.twilight.projectile.EntityApalachiaArrow;
import net.divinerpg.entities.twilight.projectile.EntityCoriShot;
import net.divinerpg.entities.twilight.projectile.EntityEdenArrow;
import net.divinerpg.entities.twilight.projectile.EntityHaliteArrow;
import net.divinerpg.entities.twilight.projectile.EntityMortumArrow;
import net.divinerpg.entities.twilight.projectile.EntityPhaserApalachia;
import net.divinerpg.entities.twilight.projectile.EntityPhaserEden;
import net.divinerpg.entities.twilight.projectile.EntityPhaserHalite;
import net.divinerpg.entities.twilight.projectile.EntityPhaserMortum;
import net.divinerpg.entities.twilight.projectile.EntityPhaserSkythern;
import net.divinerpg.entities.twilight.projectile.EntityPhaserWildWood;
import net.divinerpg.entities.twilight.projectile.EntitySkythernArrow;
import net.divinerpg.entities.twilight.projectile.EntitySlicerApalachia;
import net.divinerpg.entities.twilight.projectile.EntitySlicerEden;
import net.divinerpg.entities.twilight.projectile.EntitySlicerHalite;
import net.divinerpg.entities.twilight.projectile.EntitySlicerMortum;
import net.divinerpg.entities.twilight.projectile.EntitySlicerSkythern;
import net.divinerpg.entities.twilight.projectile.EntitySlicerWildWoods;
import net.divinerpg.entities.twilight.projectile.EntityWildWoodArrow;
import net.divinerpg.utils.Util;

public class TwilightEntityRegistry {
	
	public static void init(){	
	    Util.registerProjectile(EntitySlicerEden.class, "edenSlicer");
	    Util.registerProjectile(EntitySlicerWildWoods.class, "wildSlicer");
        Util.registerProjectile(EntitySlicerApalachia.class, "apalachiaSlicer");
        Util.registerProjectile(EntitySlicerSkythern.class, "skythernSlicer");
        Util.registerProjectile(EntitySlicerMortum.class, "mortumSlicer");
        Util.registerProjectile(EntitySlicerHalite.class, "haliteSlicer");
        Util.registerProjectile(EntityPhaserEden.class, "edenPhaser");
        Util.registerProjectile(EntityPhaserWildWood.class, "wildPhaser");
        Util.registerProjectile(EntityPhaserApalachia.class, "apalachiaPhaser");
        Util.registerProjectile(EntityPhaserSkythern.class, "skythernPhaser");
        Util.registerProjectile(EntityPhaserMortum.class, "mortumPhaser");
        Util.registerProjectile(EntityPhaserHalite.class, "halitePhaser");
        Util.registerProjectile(EntityCoriShot.class, "weakCoriShot");
        
        Util.registerDivineRPGMob(EntityEdenCadillion.class, "Eden Cadillion", Util.mobID++);
        Util.registerDivineRPGMob(EntityEdenTomo.class, "Eden Tomo", Util.mobID++);
        Util.registerDivineRPGMob(EntityBunny.class, "Bunny", Util.mobID++);
        Util.registerDivineRPGMob(EntityAngryBunny.class, "Angry Bunny", Util.mobID++);
        Util.registerDivineRPGMob(EntityEdenCori.class, "Eden Cori", Util.mobID++);
        Util.registerDivineRPGMob(EntityMadivel.class, "Madivel", Util.mobID++);
        Util.registerDivineRPGMob(EntityNesro.class, "Nesro", Util.mobID++);
        Util.registerDivineRPGMob(EntityWildWoodGolem.class, "WildWood Golem", Util.mobID++);
        Util.registerDivineRPGMob(EntityWildWoodTomo.class, "WildWood Tomo", Util.mobID++);
        Util.registerDivineRPGMob(EntityVerek.class, "Verek", Util.mobID++);
        Util.registerDivineRPGMob(EntityMoonWolf.class, "Moon Wolf", Util.mobID++);
        Util.registerDivineRPGMob(EntityApalachiaCadillion.class, "Apalachia Cadillion", Util.mobID++);
        Util.registerDivineRPGMob(EntityApalachiaTomo.class, "Apalachia Tomo", Util.mobID++);
        Util.registerDivineRPGMob(EntityApalachiaGolem.class, "Apalachia Golem", Util.mobID++);
        Util.registerDivineRPGMob(EntityApalachiaWarrior.class, "Enchant Warrior", Util.mobID++);
        Util.registerDivineRPGMob(EntitySkythernArcher.class, "Skythern Archer", Util.mobID++);
        Util.registerDivineRPGMob(EntityApalachiaArcher.class, "Twilight Archer", Util.mobID++);
        Util.registerDivineRPGMob(EntitySamek.class, "Samek", Util.mobID++);
        Util.registerDivineRPGMob(EntitySkythernGolem.class, "Skythern Golem", Util.mobID++);
        Util.registerDivineRPGMob(EntitySkythernCori.class, "Skythern Cori", Util.mobID++);
        Util.registerDivineRPGMob(EntitySkythernFiend.class, "Skythern Fiend", Util.mobID++);
        Util.registerDivineRPGMob(EntityMortumCadillion.class, "Mortum Cadillion", Util.mobID++);
        Util.registerDivineRPGMob(EntityMortumDemon.class, "Mortum Demon", Util.mobID++);
        Util.registerDivineRPGMob(EntityBaslisk.class, "Baslisk", Util.mobID++);
        Util.registerDivineRPGMob(EntitySoulStealer.class, "Soul Stealer", Util.mobID++);
        Util.registerDivineRPGMob(EntityDensos.class, "Densos", Util.mobID++);
        Util.registerDivineRPGMob(EntityReyvor.class, "Reyvor", Util.mobID++);
        Util.registerDivineRPGMob(EntityTwilightDemon.class, "Twilight Demon", Util.mobID++);
        Util.registerDivineRPGMob(EntitySoulFiend.class, "Soul Fiend", Util.mobID++);
        Util.registerDivineRPGMob(EntityVamacheron.class, "Vamacheron", Util.mobID++);
        Util.registerDivineRPGMob(EntityKarot.class, "Karot", Util.mobID++);
        
        Util.registerProjectile(EntityEdenArrow.class, "Eden Arrow");
        Util.registerProjectile(EntityWildWoodArrow.class, "Wild Arrow");
        Util.registerProjectile(EntityApalachiaArrow.class, "Apalachia Arrow");
        Util.registerProjectile(EntitySkythernArrow.class, "Skythern Arrow");
        Util.registerProjectile(EntityMortumArrow.class, "Mortum Arrow");
        Util.registerProjectile(EntityHaliteArrow.class, "Halite Arrow");
	}
}