package divinerpg.registries;

import divinerpg.*;
import divinerpg.enums.*;
import divinerpg.items.arcana.*;
import divinerpg.items.base.*;
import divinerpg.items.iceika.*;
import divinerpg.items.twilight.*;
import divinerpg.items.vanilla.*;
import divinerpg.items.vethea.*;
import divinerpg.util.*;
import net.minecraft.ChatFormatting;
import net.minecraft.core.Direction;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.*;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.*;

import java.util.*;
import java.util.function.*;

import static divinerpg.DivineRPG.MODID;

public class ItemRegistry {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MODID);

    // Armor information
    // Vanilla dimensions
    private static ArmorInfo angelicInfo = new ArmorInfo(getArmorAbility("no_fall"), getArmorAbility("fly"));
    private static ArmorInfo aquastriveInfo = new ArmorInfo(getArmorAbility("underwater"), getArmorAbility("swim"));
    private static ArmorInfo arlemiteInfo = new ArmorInfo(getArmorAbility("ranged_protection", 85));
    private static ArmorInfo bedrockInfo = new ArmorInfo(getArmorAbility("fire_protection"), getArmorAbility("explosion_protection"));
    private static ArmorInfo corruptedInfo = new ArmorInfo(getArmorAbility("ranged_damage", 50));
    private static ArmorInfo divineInfo = new ArmorInfo(getArmorAbility("melee_damage", 6),
            getArmorAbility("jump_height", 2),
            getArmorAbility("no_fall"));
    private static ArmorInfo eliteRealmiteInfo = new ArmorInfo(getArmorAbility("no_fall"));
    private static ArmorInfo enderInfo = new ArmorInfo(getArmorAbility("explosion_protection"));
    private static ArmorInfo frozenInfo = new ArmorInfo(getArmorAbility("freeze", 6));
    private static ArmorInfo infernoInfo = new ArmorInfo(getArmorAbility("fire_protection"));
    private static ArmorInfo jackomanInfo = new ArmorInfo(getArmorAbility("scythe_damage", 3));
    private static ArmorInfo jungleInfo = new ArmorInfo(getArmorAbility("poison_protection"));
    private static ArmorInfo krakenInfo = new ArmorInfo(getArmorAbility("underwater"));
    private static ArmorInfo torriditeInfo = new ArmorInfo(getArmorAbility("fire_protection"));
    private static ArmorInfo rupeeInfo = new ArmorInfo(getArmorAbility("melee_protection", 85));
    private static ArmorInfo shadowInfo = new ArmorInfo(getArmorAbility("speed", 3), getArmorAbility("step_assist"));
    private static ArmorInfo skelemanInfo = new ArmorInfo(getArmorAbility("hunger"));
    private static ArmorInfo terranInfo = new ArmorInfo(getArmorAbility("haste"));
    private static ArmorInfo witherReaperInfo = new ArmorInfo(getArmorAbility("wither_protection"));
    private static ArmorInfo kingInfo = new ArmorInfo(Component.translatable("Absorbs super-power from other sets"));

    // Iceika
    private static ArmorInfo sengFurInfo = new ArmorInfo(Component.translatable("tooltip.armor_info.massive_buff"),
            getArmorAbility("speed", 2),
            getArmorAbility("melee_damage", 2),
            getArmorAbility("hunger"),
            getArmorAbility("melee_protection", 30))
            .withDimension(Component.translatable("tooltip.armor_info.iceika"), x -> Objects.equals(x, LevelRegistry.ICEIKA));

    // Twilight
    private static ArmorInfo edenInfo = new ArmorInfo(getArmorAbility("ore_drops", 3));
    private static ArmorInfo wildInfo = new ArmorInfo(getArmorAbility("underwater_health_regen"));
    private static ArmorInfo apInfo = new ArmorInfo(getArmorAbility("block_protection"));
    private static ArmorInfo skyInfo = new ArmorInfo(getArmorAbility("jump_height", 5), getArmorAbility("no_fall"));
    private static ArmorInfo mortInfo = new ArmorInfo(getArmorAbility("night_vision"));
    private static ArmorInfo halInfo = new ArmorInfo(getArmorAbility("melee_damage", 16));
    private static ArmorInfo awakened_halInfo = new ArmorInfo(getArmorAbility("melee_damage", 20),
            getArmorAbility("ranged_damage", 50));

    // Arcana
    private static ArmorInfo kormInfo = new ArmorInfo(getArmorAbility("arcana_regen"));
    private static ArmorInfo vemInfo = new ArmorInfo(getArmorAbility("health_regen"));

    // Vethea
    private static ArmorInfo basicHelmInfo = new ArmorInfo(getArmorAbility("melee_protection", 15));
    private static ArmorInfo basicMaskInfo = new ArmorInfo(getArmorAbility("ranged_protection", 15));
    private static ArmorInfo basicHoodInfo = new ArmorInfo(getArmorAbility("arcana_protection", 15));

    private static ArmorInfo glisteningHelmInfo = new ArmorInfo(getArmorAbility("melee_protection", 15), getArmorAbility("melee_damage", 3));
    private static ArmorInfo glisteningMaskInfo = new ArmorInfo(getArmorAbility("ranged_protection", 15), getArmorAbility("speed", 1));
    private static ArmorInfo glisteningHoodInfo = new ArmorInfo(getArmorAbility("arcana_protection", 15), getArmorAbility("jump_height", 2), getArmorAbility("no_fall"));

    private static ArmorInfo demonizedHelmInfo = new ArmorInfo(getArmorAbility("melee_protection", 15), getArmorAbility("melee_damage", 6));
    private static ArmorInfo demonizedMaskInfo = new ArmorInfo(getArmorAbility("ranged_protection", 15), getArmorAbility("speed", 2));
    private static ArmorInfo demonizedHoodInfo = new ArmorInfo(getArmorAbility("arcana_protection", 15), getArmorAbility("jump_height", 3), getArmorAbility("no_fall"));

    private static ArmorInfo tormentedHelmInfo = new ArmorInfo(getArmorAbility("melee_protection", 15), getArmorAbility("melee_damage", 9));
    private static ArmorInfo tormentedMaskInfo = new ArmorInfo(getArmorAbility("ranged_protection", 15), getArmorAbility("speed", 3));
    private static ArmorInfo tormentedHoodInfo = new ArmorInfo(getArmorAbility("arcana_protection", 15), getArmorAbility("jump_height", 4), getArmorAbility("no_fall"));

    public static final RegistryObject<Item>
            apalachia_chunk = registerItem("apalachia_chunk", () -> new ItemMod()),
            apalachia_dust = registerItem("apalachia_dust", () -> new ItemMod()),
            apalachia_fragments = registerItem("apalachia_fragments", () -> new ItemMod()),
            apalachia_gem = registerItem("apalachia_gem", () -> new ItemMod()),
            apalachia_heart = registerItem("apalachia_heart", () -> new ItemMod()),
            apalachia_soul = registerItem("apalachia_soul", () -> new ItemMod()),
            aqua_ball = registerItem("aqua_ball", () -> new ItemMod()),
            aquatic_blaze_rod = registerItem("aquatic_blaze_rod", () -> new ItemMod()),
            aquatic_ingot = registerItem("aquatic_ingot", () -> new ItemMod()),
            aquatic_pellets = registerItem("aquatic_pellets", () -> new ItemMod()),
            arcanium = registerItem("arcanium", () -> new ItemMod()),
            pieceOfRawArcanium = registerItem("piece_of_raw_arcanium", () -> new ItemMod()),
            arlemite_ingot = registerItem("arlemite_ingot", () -> new ItemMod()),
            arlemite_nugget = registerItem("arlemite_nugget", () -> new ItemMod()),
            base_spawn_crystal = registerItem("base_spawn_crystal", () -> new ItemMod()),
            bedrock_chunk = registerItem("bedrock_chunk", () -> new ItemMod(new Item.Properties().fireResistant())),
            bloodgem = registerItem("bloodgem", () -> new ItemMod()),
            blue_diamond_chunk = registerItem("blue_diamond_chunk", () -> new ItemMod()),
            soulfire_stone = registerItem("soulfire_stone", () -> new ItemMod()),
            collector_fragments = registerItem("collector_fragments", () -> new ItemMod()),
            corrupted_bullet = registerItem("corrupted_bullet", () -> new ItemMod()),
            corrupted_shards = registerItem("corrupted_shards", () -> new ItemMod()),
            corrupted_stone = registerItem("corrupted_stone", () -> new ItemMod()),
            crab_claw = registerItem("crab_claw", () -> new ItemMod()),
            cyclops_eye = registerItem("cyclops_eye", () -> new ItemMod()),
            cyclops_eye_shards = registerItem("cyclops_eye_shards", () -> new ItemMod()),
            divine_shards = registerItem("divine_shards", () -> new ItemMod()),
            divine_stone = registerItem("divine_stone", () -> new ItemMod()),
            dungeon_tokens = registerItem("dungeon_tokens", () -> new ItemMod()),
            eden_arrow = registerItem("eden_arrow", () -> new ItemMod()),
            eden_chunk = registerItem("eden_chunk", () -> new ItemMod()),
            eden_dust = registerItem("eden_dust", () -> new ItemMod()),
            eden_fragments = registerItem("eden_fragments", () -> new ItemMod()),
            eden_gem = registerItem("eden_gem", () -> new ItemMod()),
            eden_heart = registerItem("eden_heart", () -> new ItemMod()),
            eden_soul = registerItem("eden_soul", () -> new ItemMod()),
            eden_sparkles = registerItem("eden_sparkles", () -> new ItemMod()),
            ender_shards = registerItem("ender_shards", () -> new ItemMod()),
            ender_stone = registerItem("ender_stone", () -> new ItemMod()),
            firestock = registerItem("firestock", () -> new ItemMod()),
            fury_arrow = registerItem("fury_arrow", () -> new ItemMod()),
            fury_fire = registerItem("fury_fire", () -> new ItemMod()),
            gray_diamond_chunk = registerItem("gray_diamond_chunk", () -> new ItemMod()),
            green_diamond_chunk = registerItem("green_diamond_chunk", () -> new ItemMod()),
            hellstone_ingot = registerItem("hellstone_ingot", () -> new ItemMod()),
            ice_shards = registerItem("ice_shards", () -> new ItemMod()),
            ice_stone = registerItem("ice_stone", () -> new ItemMod()),
            jungle_shards = registerItem("jungle_shards", () -> new ItemMod()),
            jungle_stone = registerItem("jungle_stone", () -> new ItemMod()),
            kraken_scale = registerItem("kraken_scale", () -> new ItemMod()),
            kraken_skin = registerItem("kraken_skin", () -> new ItemMod()),
            lamona = registerItem("lamona", () -> new ItemMod()),
            legendary_ender_eye = registerItem("legendary_ender_eye", () -> new ItemMod()),
            liopleurodon_skull = registerItem("liopleurodon_skull", () -> new ItemMod()),
            liopleurodon_teeth = registerItem("liopleurodon_teeth", () -> new ItemMod()),
            marsine = registerItem("marsine", () -> new ItemMod()),
            molten_shards = registerItem("molten_shards", () -> new ItemMod(new Item.Properties().fireResistant())),
            molten_stone = registerItem("molten_stone", () -> new ItemMod(new Item.Properties().fireResistant())),
            mortum_chunk = registerItem("mortum_chunk", () -> new ItemMod()),
            mortum_dust = registerItem("mortum_dust", () -> new ItemMod()),
            mortum_fragments = registerItem("mortum_fragments", () -> new ItemMod()),
            mortum_gem = registerItem("mortum_gem", () -> new ItemMod()),
            mortum_heart = registerItem("mortum_heart", () -> new ItemMod()),
            mortum_soul = registerItem("mortum_soul", () -> new ItemMod()),
            orb_of_light = registerItem("orb_of_light", () -> new ItemMod()),
            pure_aquatic_pellets = registerItem("pure_aquatic_pellets", () -> new ItemMod()),
            purple_blaze = registerItem("purple_blaze", () -> new ItemMod()),
            raw_arlemite = registerItem("raw_arlemite", () -> new ItemMod()),
            raw_realmite = registerItem("raw_realmite", () -> new ItemMod()),
            raw_rupee = registerItem("raw_rupee", () -> new ItemMod()),
            realmite_ingot = registerItem("realmite_ingot", () -> new ItemMod()),
            realmite_nugget = registerItem("realmite_nugget", () -> new ItemMod()),
            red_diamond_chunk = registerItem("red_diamond_chunk", () -> new ItemMod()),
            rupee_ingot = registerItem("rupee_ingot", () -> new ItemMod()),
            rupee_nugget = registerItem("rupee_nugget", () -> new ItemMod()),
            shadow_bar = registerItem("shadow_bar", () -> new ItemMod()),
            shadow_coins = registerItem("shadow_coins", () -> new ItemMod()),
            shadow_stone = registerItem("shadow_stone", () -> new ItemMod()),
            shark_fin = registerItem("shark_fin", () -> new ItemMod()),
            skythern_chunk = registerItem("skythern_chunk", () -> new ItemMod()),
            skythern_dust = registerItem("skythern_dust", () -> new ItemMod()),
            skythern_fragments = registerItem("skythern_fragments", () -> new ItemMod()),
            skythern_gem = registerItem("skythern_gem", () -> new ItemMod()),
            skythern_heart = registerItem("skythern_heart", () -> new ItemMod()),
            skythern_soul = registerItem("skythern_soul", () -> new ItemMod()),
            snowflake = registerItem("snowflake", () -> new ItemMod()),
            terran_shards = registerItem("terran_shards", () -> new ItemMod()),
            terran_stone = registerItem("terran_stone", () -> new ItemMod()),
            raw_torridite = registerItem("raw_torridite", () -> new ItemMod()),
            torridite_chunk = registerItem("torridite_chunk", () -> new ItemMod(new Item.Properties().fireResistant())),
            torridite_ingot = registerItem("torridite_ingot", () -> new ItemMod(new Item.Properties().fireResistant())),
            torridite_nugget = registerItem("torridite_nugget", () -> new ItemMod(new Item.Properties().fireResistant())),
            veilo = registerItem("veilo", () -> new ItemMod()),
            watching_eye = registerItem("watching_eye", () -> new ItemMod()),
            whale_fin = registerItem("whale_fin", () -> new ItemMod()),
            wildwood_arrow = registerItem("wildwood_arrow", () -> new ItemMod()),
            wildwood_chunk = registerItem("wildwood_chunk", () -> new ItemMod()),
            wildwood_dust = registerItem("wildwood_dust", () -> new ItemMod()),
            wildwood_fragments = registerItem("wildwood_fragments", () -> new ItemMod()),
            wildwood_gem = registerItem("wildwood_gem", () -> new ItemMod()),
            wildwood_heart = registerItem("wildwood_heart", () -> new ItemMod()),
            wildwood_soul = registerItem("wildwood_soul", () -> new ItemMod()),
            yellow_diamond_chunk = registerItem("yellow_diamond_chunk", () -> new ItemMod()),
            ancient_key = registerItem("ancient_key", () -> new ItemMod()),
            degraded_key = registerItem("degraded_key", () -> new ItemMod()),
            sludge_key = registerItem("sludge_key", () -> new ItemMod()),
            soul_key = registerItem("soul_key", () -> new ItemMod()),
            arcanium_attractor = registerItem("arcanium_attractor", () -> new ItemAttractor()),
            call_of_the_watcher = registerItem("call_of_the_watcher", () -> new ItemBossSpawner("message.watcher", Level.NETHER, () -> EntityRegistry.THE_WATCHER.get())),
            densos_crystal = registerItem("densos_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.REYVOR.get(), () -> EntityRegistry.DENSOS.get())),
            infernal_flame = registerItem("infernal_flame", () -> new ItemBossSpawner("message.king_of_scorchers", Level.NETHER, () -> EntityRegistry.KING_OF_SCORCHERS.get())),
            karot_crystal = registerItem("karot_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.KAROT.get())),
            mysterious_clock = registerItem("mysterious_clock", () -> new ItemBossSpawner("message.ancient_entity", Level.OVERWORLD, () -> EntityRegistry.ANCIENT_ENTITY.get())),
            reyvor_crystal = registerItem("reyvor_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.REYVOR.get(), () -> EntityRegistry.DENSOS.get())),
            soul_fiend_crystal = registerItem("soul_fiend_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.SOUL_FIEND.get())),
            twilight_demon_crystal = registerItem("twilight_demon_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.TWILIGHT_DEMON.get())),
            vamacheron_crystal = registerItem("vamacheron_crystal", () -> new ItemBossSpawner("tooltip.mortum_only", LevelRegistry.MORTUM, () -> EntityRegistry.VAMACHERON.get())),
            collector = registerItem("collector", () -> new ItemCollector()),
            dream_sweets = registerItem("dream_sweets", () -> new ItemHealingFood(FoodList.DREAM_SWEETS)),
            dream_sours = registerItem("dream_sours", () -> new ItemHealingFood(FoodList.DREAM_SOURS)),
            healing_stone = registerItem("healing_stone", () -> new ItemHealingStone(20)),
            miners_amulet = registerItem("miners_amulet", () -> new ItemMinersAmulet()),
            arcanium_reflector = registerItem("arcanium_reflector", () -> new ItemReflector()),
            sky_flower = registerItem("sky_flower", () -> new ItemSkyFlower()),
            snow_globe = registerItem("snow_globe", () -> new ItemSnowGlobe()),
            staff_of_enrichment = registerItem("staff_of_enrichment", () -> new ItemStaffEnrichment()),
            wizards_book = registerItem("wizards_book", () -> new ItemWizardsBook()),
            bowhead_anchor = registerItem("bowhead_anchor", () -> new ItemAnchor(BulletType.BOWHEAD_ANCHOR_SHOT)),
            crab_anchor = registerItem("crab_anchor", () -> new ItemAnchor(BulletType.CRAB_ANCHOR_SHOT)),
            liopleurodon_anchor = registerItem("liopleurodon_anchor", () -> new ItemAnchor(BulletType.LIOPLEURODON_ANCHOR_SHOT)),
            shark_anchor = registerItem("shark_anchor", () -> new ItemAnchor(BulletType.SHARK_ANCHOR_SHOT)),
            arcanite_blade = registerItem("arcanite_blade", () -> new ItemArcanaPoweredSword(ToolStats.ARCANITE_BLADE, 30, 6.0F)),
            arcanium_saber = registerItem("arcanium_saber", () -> new ItemArcanaPoweredSword(ToolStats.ARCANIUM_SABER, 25, 5.0F)),
            arcanite_blaster = registerItem("arcanite_blaster", () -> new ItemArcaniteBlaster()),
            flaming_fury = registerItem("flaming_fury", () -> new ItemBurningSword(ToolStats.FLAMING_FURY, 15)),
            inferno_sword = registerItem("inferno_sword", () -> new ItemBurningSword(ToolStats.INFERNO_SWORD, 12)),
            molten_sword = registerItem("molten_sword", () -> new ItemBurningSword(ToolStats.MOLTEN_SWORD, 5)),
            captains_sparkler = registerItem("captains_sparkler", () -> new ItemCaptainsSparkler()),
            corrupted_cannon = registerItem("corrupted_cannon", () -> new ItemCorruptedCannon()),
            ender_scepter = registerItem("ender_scepter", () -> new ItemEnderScepter()),
            evernight = registerItem("evernight", () -> new ItemEvernight(115, 80)),
            firefly = registerItem("firefly", () -> new ItemFirefly()),
            generals_staff = registerItem("generals_staff", () -> new ItemGeneralsStaff()),
            grenade = registerItem("grenade", () -> new ItemGrenade()),
            frossivence = registerItem("frossivence", () -> new ItemHealingSword(ToolStats.FROSSIVENCE, 1F)),
            massivence = registerItem("massivence", () -> new ItemHealingSword(ToolStats.PALAVENCE, 1F)),
            palavence = registerItem("palavence", () -> new ItemHealingSword(ToolStats.PALAVENCE, 0.5F)),
            la_vekor = registerItem("la_vekor", () -> new ItemLaVekor()),
            meriks_missile = registerItem("meriks_missile", () -> new ItemMeriksMissile()),
            meteor_mash = registerItem("meteor_mash", () -> new ItemMeteorMash()),
            sound_of_carols = registerItem("sound_of_carols", () -> new ItemMusicShooter(() -> SoundRegistry.SOUND_OF_CAROLS.get(), "sound_of_carols")),
            sound_of_music = registerItem("sound_of_music", () -> new ItemMusicShooter(() -> SoundRegistry.SOUND_OF_MUSIC.get(), "sound_of_music")),
            jungle_knife = registerItem("jungle_knife", () -> new ItemPoisonousSword(ToolStats.JUNGLE_KNIFE, 2.5f)),
            jungle_rapier = registerItem("jungle_rapier", () -> new ItemPoisonousSword(ToolStats.JUNGLE_RAPIER, 4f)),
            poison_saber = registerItem("poison_saber", () -> new ItemPoisonousSword(ToolStats.POISON_SABER, 5)),
            scythe = registerItem("scythe", () -> new ItemScythe()),
            serenade_of_death = registerItem("serenade_of_death", () -> new ItemSerenadeOfDeath()),
            serenade_of_health = registerItem("serenade_of_health", () -> new ItemSerenadeOfHealth()),
            serenade_of_ice = registerItem("serenade_of_ice", () -> new ItemSerenadeOfIce()),
            serenade_of_infusion = registerItem("serenade_of_infusion", () -> new ItemSerenadeOfInfusion()),
            serenade_striker = registerItem("serenade_striker", () -> new ItemSerenadeStriker()),
            shadow_saber = registerItem("shadow_saber", () -> new ItemShadowSaber(ToolStats.SHADOW_SABER)),
            enderice = registerItem("enderice", () -> new ItemSlowingSword(ToolStats.ENDERICE)),
            frost_sword = registerItem("frost_sword", () -> new ItemSlowingSword(ToolStats.FROST_SWORD)),
            frostking_sword = registerItem("frostking_sword", () -> new ItemSlowingSword(ToolStats.FROSTKING_SWORD)),
            frozen_maul = registerItem("frozen_maul", () -> new ItemSlowingSword(ToolStats.FROZEN_MAUL)),
            glacier_sword = registerItem("glacier_sword", () -> new ItemSlowingSword(ToolStats.GLACIER_SWORD)),
            icicle_bane = registerItem("icicle_bane", () -> new ItemSlowingSword(ToolStats.ICICLE_BANE)),
            icine_sword = registerItem("icine_sword", () -> new ItemSlowingSword(ToolStats.ICINE_SWORD)),
            snowslash = registerItem("snowslash", () -> new ItemSlowingSword(ToolStats.SNOWSLASH)),
            teaker_staff = registerItem("teaker_staff", () -> new ItemStaff(3, 10)),
            amthirmis_staff = registerItem("amthirmis_staff", () -> new ItemStaff(5, 10)),
            darven_staff = registerItem("darven_staff", () -> new ItemStaff(8, 10)),
            cermile_staff = registerItem("cermile_staff", () -> new ItemStaff(12, 10)),
            pardimal_staff = registerItem("pardimal_staff", () -> new ItemStaff(15, 10)),
            quadrotic_staff = registerItem("quadrotic_staff", () -> new ItemStaff(19, 10)),
            karos_staff = registerItem("karos_staff", () -> new ItemStaff(21, 10)),
            heliosis_staff = registerItem("heliosis_staff", () -> new ItemStaff(28, 10)),
            arksiane_staff = registerItem("arksiane_staff", () -> new ItemStaff(36, 10)),
            staff_of_starlight = registerItem("staff_of_starlight", () -> new ItemStaffStarlight(25, 8)),
            starlight = registerItem("starlight", () -> new ItemStaffStarlight(5, 1)),
            storm_sword = registerItem("storm_sword", () -> new ItemStormSword(ToolStats.STORM_SWORD)),
            eden_slicer = registerItem("eden_slicer", () -> new ItemModThrowable(RarityList.EDEN, BulletType.EDEN_SLICER_SHOT)),
            wildwood_slicer = registerItem("wildwood_slicer", () -> new ItemModThrowable(RarityList.WILDWOOD, BulletType.WILDWOOD_SLICER_SHOT)),
            apalachia_slicer = registerItem("apalachia_slicer", () -> new ItemModThrowable(RarityList.APALACHIA, BulletType.APALACHIA_SLICER_SHOT)),
            skythern_slicer = registerItem("skythern_slicer", () -> new ItemModThrowable(RarityList.SKYTHERN, BulletType.SKYTHERN_SLICER_SHOT)),
            mortum_slicer = registerItem("mortum_slicer", () -> new ItemModThrowable(RarityList.MORTUM, BulletType.MORTUM_SLICER_SHOT)),
            halite_slicer = registerItem("halite_slicer", () -> new ItemModThrowable(RarityList.HALITE, BulletType.HALITE_SLICER_SHOT)),
            shuriken = registerItem("shuriken", () -> new ItemThrowingStar()),
            snowflake_shuriken = registerItem("snowflake_shuriken", () -> new ItemThrowingStar()),
            eden_blitz = registerItem("eden_blitz", () -> new ItemTwilightBlitz(RarityList.EDEN, BulletType.EDEN_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "eden_dust"))),
            wildwood_blitz = registerItem("wildwood_blitz", () -> new ItemTwilightBlitz(RarityList.WILDWOOD, BulletType.WILDWOOD_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "wildwood_dust"))),
            apalachia_blitz = registerItem("apalachia_blitz", () -> new ItemTwilightBlitz(RarityList.APALACHIA, BulletType.APALACHIA_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "apalachia_dust"))),
            skythern_blitz = registerItem("skythern_blitz", () -> new ItemTwilightBlitz(RarityList.SKYTHERN, BulletType.SKYTHERN_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "skythern_dust"))),
            mortum_blitz = registerItem("mortum_blitz", () -> new ItemTwilightBlitz(RarityList.MORTUM, BulletType.MORTUM_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "mortum_dust"))),
            halite_blitz = registerItem("halite_blitz", () -> new ItemTwilightBlitz(RarityList.HALITE, BulletType.HALITE_BLITZ_SHOT, new ResourceLocation(DivineRPG.MODID, "mortum_dust"))),
            amthirmis_bow = registerItem("amthirmis_bow", () -> new ItemVetheanBow(ArrowType.AMTHIRMIS_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "teaker_arrow"))),
            arksiane_bow = registerItem("arksiane_bow", () -> new ItemVetheanBow(ArrowType.ARKSIANE_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "karos_arrow"))),
            cermile_bow = registerItem("cermile_bow", () -> new ItemVetheanBow(ArrowType.CERMILE_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "darven_arrow"))),
            darven_bow = registerItem("darven_bow", () -> new ItemVetheanBow(ArrowType.DARVEN_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "darven_arrow"))),
            everfright = registerItem("everfright", () -> new ItemVetheanBow(ArrowType.EVERFRIGHT, -1, new ResourceLocation(DivineRPG.MODID, "ever_arrow"))),
            heliosis_bow = registerItem("heliosis_bow", () -> new ItemVetheanBow(ArrowType.HELIOSIS_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "karos_arrow"))),
            karos_bow = registerItem("karos_bow", () -> new ItemVetheanBow(ArrowType.KAROS_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "karos_arrow"))),
            pardimal_bow = registerItem("pardimal_bow", () -> new ItemVetheanBow(ArrowType.PARDIMAL_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "pardimal_arrow"))),
            quadrotic_bow = registerItem("quadrotic_bow", () -> new ItemVetheanBow(ArrowType.QUADROTIC_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "pardimal_arrow"))),
            teaker_bow = registerItem("teaker_bow", () -> new ItemVetheanBow(ArrowType.TEAKER_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "teaker_arrow"))),
            amthirmis_cannon = registerItem("amthirmis_cannon", () -> new ItemVetheanCannon(BulletType.AMTHIRMIS_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            arksiane_cannon = registerItem("arksiane_cannon", () -> new ItemVetheanCannon(BulletType.ARKSIANE_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            cermile_cannon = registerItem("cermile_cannon", () -> new ItemVetheanCannon(BulletType.CERMILE_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            darven_cannon = registerItem("darven_cannon", () -> new ItemVetheanCannon(BulletType.DARVEN_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            eversight = registerItem("eversight", () -> new ItemVetheanCannon(BulletType.EVERSIGHT_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            heliosis_cannon = registerItem("heliosis_cannon", () -> new ItemVetheanCannon(BulletType.HELIOSIS_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            karos_cannon = registerItem("karos_cannon", () -> new ItemVetheanCannon(BulletType.KAROS_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            pardimal_cannon = registerItem("pardimal_cannon", () -> new ItemVetheanCannon(BulletType.PARDIMAL_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            quadrotic_cannon = registerItem("quadrotic_cannon", () -> new ItemVetheanCannon(BulletType.QUADROTIC_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            teaker_cannon = registerItem("teaker_cannon", () -> new ItemVetheanCannon(BulletType.TEAKER_CANNON_SHOT, new ResourceLocation(DivineRPG.MODID, "acid"))),
            amthirmis_disk = registerItem("amthirmis_disk", () -> new ItemVetheanDisk(DiskType.AMTHRIMIS_DISK)),
            arksiane_disk = registerItem("arksiane_disk", () -> new ItemVetheanDisk(DiskType.ARKSIANE_DISK)),
            cermile_disk = registerItem("cermile_disk", () -> new ItemVetheanDisk(DiskType.CERMILE_DISK)),
            darven_disk = registerItem("darven_disk", () -> new ItemVetheanDisk(DiskType.DARVEN_DISK)),
            heliosis_disk = registerItem("heliosis_disk", () -> new ItemVetheanDisk(DiskType.HELIOSIS_DISK)),
            karos_disk = registerItem("karos_disk", () -> new ItemVetheanDisk(DiskType.KAROS_DISK)),
            pardimal_disk = registerItem("pardimal_disk", () -> new ItemVetheanDisk(DiskType.PARDIMAL_DISK)),
            quadrotic_disk = registerItem("quadrotic_disk", () -> new ItemVetheanDisk(DiskType.QUADROTIC_DISK)),
            teaker_disk = registerItem("teaker_disk", () -> new ItemVetheanDisk(DiskType.TEAKER_DISK)),
            amthirmis_dissipator = registerItem("amthirmis_dissipator", () -> new ItemVetheanDissipator(DiskType.AMTHRIMIS_DISK)),
            arksiane_dissipator = registerItem("arksiane_dissipator", () -> new ItemVetheanDissipator(DiskType.ARKSIANE_DISK)),
            cermile_dissipator = registerItem("cermile_dissipator", () -> new ItemVetheanDissipator(DiskType.CERMILE_DISK)),
            darven_dissipator = registerItem("darven_dissipator", () -> new ItemVetheanDissipator(DiskType.DARVEN_DISK)),
            heliosis_dissipator = registerItem("heliosis_dissipator", () -> new ItemVetheanDissipator(DiskType.HELIOSIS_DISK)),
            karos_dissipator = registerItem("karos_dissipator", () -> new ItemVetheanDissipator(DiskType.KAROS_DISK)),
            pardimal_dissipator = registerItem("pardimal_dissipator", () -> new ItemVetheanDissipator(DiskType.PARDIMAL_DISK)),
            quadrotic_dissipator = registerItem("quadrotic_dissipator", () -> new ItemVetheanDissipator(DiskType.QUADROTIC_DISK)),
            teaker_dissipator = registerItem("teaker_dissipator", () -> new ItemVetheanDissipator(DiskType.TEAKER_DISK)),
            amthirmis_backsword = registerItem("amthirmis_backsword", () -> new ItemVetheanSword(ToolStats.AMTHIRMIS_BACKSWORD)),
            amthirmis_claw = registerItem("amthirmis_claw", () -> new ItemVetheanSword(ToolStats.AMTHIRMIS_CLAW)),
            amthirmis_hammer = registerItem("amthirmis_hammer", () -> new ItemVetheanSword(ToolStats.AMTHIRMIS_HAMMER)),
            arksiane_backsword = registerItem("arksiane_backsword", () -> new ItemVetheanSword(ToolStats.ARKSIANE_BACKSWORD)),
            arksiane_claw = registerItem("arksiane_claw", () -> new ItemVetheanSword(ToolStats.ARKSIANE_CLAW)),
            arksiane_hammer = registerItem("arksiane_hammer", () -> new ItemVetheanSword(ToolStats.ARKSIANE_HAMMER)),
            cermile_backsword = registerItem("cermile_backsword", () -> new ItemVetheanSword(ToolStats.CERMILE_BACKSWORD)),
            cermile_claw = registerItem("cermile_claw", () -> new ItemVetheanSword(ToolStats.CERMILE_CLAW)),
            cermile_hammer = registerItem("cermile_hammer", () -> new ItemVetheanSword(ToolStats.CERMILE_HAMMER)),
            darven_backsword = registerItem("darven_backsword", () -> new ItemVetheanSword(ToolStats.DARVEN_BACKSWORD)),
            darven_claw = registerItem("darven_claw", () -> new ItemVetheanSword(ToolStats.DARVEN_CLAW)),
            darven_hammer = registerItem("darven_hammer", () -> new ItemVetheanSword(ToolStats.DARVEN_HAMMER)),
            everbright = registerItem("everbright", () -> new ItemVetheanSword(ToolStats.EVERBRIGHT)),
            everlight = registerItem("everlight", () -> new ItemVetheanSword(ToolStats.EVERLIGHT)),
            heliosis_backsword = registerItem("heliosis_backsword", () -> new ItemVetheanSword(ToolStats.HELIOSIS_BACKSWORD)),
            heliosis_claw = registerItem("heliosis_claw", () -> new ItemVetheanSword(ToolStats.HELIOSIS_CLAW)),
            heliosis_hammer = registerItem("heliosis_hammer", () -> new ItemVetheanSword(ToolStats.HELIOSIS_HAMMER)),
            karos_backsword = registerItem("karos_backsword", () -> new ItemVetheanSword(ToolStats.KAROS_BACKSWORD)),
            karos_claw = registerItem("karos_claw", () -> new ItemVetheanSword(ToolStats.KAROS_CLAW)),
            karos_hammer = registerItem("karos_hammer", () -> new ItemVetheanSword(ToolStats.KAROS_HAMMER)),
            karos_rockmaul = registerItem("karos_rockmaul", () -> new ItemVetheanSword(ToolStats.KAROS_ROCKMAUL)),
            pardimal_backsword = registerItem("pardimal_backsword", () -> new ItemVetheanSword(ToolStats.PARDIMAL_BACKSWORD)),
            pardimal_claw = registerItem("pardimal_claw", () -> new ItemVetheanSword(ToolStats.PARDIMAL_CLAW)),
            pardimal_hammer = registerItem("pardimal_hammer", () -> new ItemVetheanSword(ToolStats.PARDIMAL_HAMMER)),
            quadrotic_backsword = registerItem("quadrotic_backsword", () -> new ItemVetheanSword(ToolStats.QUADROTIC_BACKSWORD)),
            quadrotic_claw = registerItem("quadrotic_claw", () -> new ItemVetheanSword(ToolStats.QUADROTIC_CLAW)),
            quadrotic_hammer = registerItem("quadrotic_hammer", () -> new ItemVetheanSword(ToolStats.QUADROTIC_HAMMER)),
            teaker_backsword = registerItem("teaker_backsword", () -> new ItemVetheanSword(ToolStats.TEAKER_BACKSWORD)),
            teaker_claw = registerItem("teaker_claw", () -> new ItemVetheanSword(ToolStats.TEAKER_CLAW)),
            teaker_hammer = registerItem("teaker_hammer", () -> new ItemVetheanSword(ToolStats.TEAKER_HAMMER)),
            vile_storm = registerItem("vile_storm", () -> new ItemThrowingStar()),
            teleportation_crystal = registerItem("teleportation_crystal", () -> new ItemTeleportationCrystal()),
            teleportation_star = registerItem("teleportation_star", () -> new ItemTeleportationStar()),
            realmite_shield = registerItem("realmite_shield", () -> new DivineShield(new ResourceLocation(DivineRPG.MODID, "realmite_ingot"), 1200, "realmite_shield")),
            arlemite_shield = registerItem("arlemite_shield", () -> new DivineShield(new ResourceLocation(DivineRPG.MODID, "arlemite_ingot"), 1200, "arlemite_shield")),
            rupee_shield = registerItem("rupee_shield", () -> new DivineShield(new ResourceLocation(DivineRPG.MODID, "rupee_ingot"), 1200, "rupee_shield")),
            eden_shield = registerItem("eden_shield", () -> new DivineShield(RarityList.EDEN, new ResourceLocation(DivineRPG.MODID, "eden_chunk"), 1200, "eden_shield")),
            wildwood_shield = registerItem("wildwood_shield", () -> new DivineShield(RarityList.WILDWOOD, new ResourceLocation(DivineRPG.MODID, "wildwood_chunk"), 2400, "wildwood_shield")),
            apalachia_shield = registerItem("apalachia_shield", () -> new DivineShield(RarityList.APALACHIA, new ResourceLocation(DivineRPG.MODID, "apalachia_chunk"), 4800, "apalachia_shield")),
            skythern_shield = registerItem("skythern_shield", () -> new DivineShield(RarityList.SKYTHERN, new ResourceLocation(DivineRPG.MODID, "skythern_chunk"), 9600, "skythern_shield")),
            mortum_shield = registerItem("mortum_shield", () -> new DivineShield(RarityList.MORTUM, new ResourceLocation(DivineRPG.MODID, "mortum_chunk"), 19200, "mortum_shield")),
            halite_shield = registerItem("halite_shield", () -> new DivineShield(RarityList.HALITE, new ResourceLocation("air") , 0, "halite_shield")),
            aquamarine = registerItem("aquamarine", () -> new ItemAquamarine()),
            strong_arcana_potion = registerItem("strong_arcana_potion", () -> new ItemArcanaPotion(200)),
            weak_arcana_potion = registerItem("weak_arcana_potion", () -> new ItemArcanaPotion(100)),
            divine_accumulator = registerItem("divine_accumulator", () -> new ItemDivineAccumulator()),
            egg_nog = registerItem("egg_nog", () -> new ItemEggNog()),
            moonbulb = registerItem("moonbulb", () -> new ItemModFood(FoodList.MOONBULB, true)),
            pink_glowbone = registerItem("pink_glowbone", () -> new ItemModFood(FoodList.PINK_GLOWBONE, true)),
            purple_glowbone = registerItem("purple_glowbone", () -> new ItemModFood(FoodList.PURPLE_GLOWBONE, true)),
            magic_meat = registerItem("magic_meat", () -> new ItemModFood(FoodList.MAGIC_MEAT, true)),
            enriched_magic_meat = registerItem("enriched_magic_meat", () -> new ItemModFood(FoodList.ENRICHED_MAGIC_MEAT, true)),
            forbidden_fruit = registerItem("forbidden_fruit", () -> new ItemForbiddenFruit()),
            ghostbane = registerItem("ghostbane", () -> new ItemGhostbane()),
            horde_horn = registerItem("horde_horn", () -> new ItemHordeHorn()),
            white_mushroom = registerItem("white_mushroom", () -> new ItemModFood(FoodList.WHITE_MUSHROOM)),
            honeychunk = registerItem("honeychunk", () -> new ItemModFood(FoodList.HONEYCHUNK)),
            honeysuckle = registerItem("honeysuckle", () -> new ItemModFood(FoodList.HONEYSUCKLE)),
            peppermints = registerItem("peppermints", () -> new ItemModFood(FoodList.PEPPERMINTS)),
            cheese = registerItem("cheese", () -> new ItemModFood(FoodList.CHEESE)),
            pinfly = registerItem("pinfly", () -> new ItemModFood(FoodList.PINFLY)),
            snow_cones = registerItem("snow_cones", () -> new ItemModFood(FoodList.SNOW_CONES)),
            bacon = registerItem("bacon", () -> new ItemModFood(FoodList.BACON)),
            hitchak = registerItem("hitchak", () -> new ItemModFood(FoodList.HITCHAK)),
            dream_carrot = registerItem("dream_carrot", () -> new ItemModFood(FoodList.DREAM_CARROT)),
            tomato = registerItem("tomato", () -> new ItemTomato(FoodList.TOMATO)),
            boiled_egg = registerItem("boiled_egg", () -> new ItemModFood(FoodList.BOILED_EGG)),
            dream_pie = registerItem("dream_pie", () -> new ItemModFood(FoodList.DREAM_PIE)),
            chocolate_log = registerItem("chocolate_log", () -> new ItemModFood(FoodList.CHOCOLATE_LOG)),
            winterberry = registerItem("winterberry", () -> new ItemModFood(FoodList.WINTERBERRY)),
            raw_empowered_meat = registerItem("raw_empowered_meat", () -> new ItemModFood(FoodList.RAW_EMPOWERED_MEAT)),
            dream_melon = registerItem("dream_melon", () -> new ItemModFood(FoodList.DREAM_MELON)),
            dream_cake = registerItem("dream_cake", () -> new ItemModFood(FoodList.DREAM_CAKE)),
            hot_pumpkin_pie = registerItem("hot_pumpkin_pie", () -> new ItemModFood(FoodList.HOT_PUMPKIN_PIE)),
            advanced_mushroom_stew = registerItem("advanced_mushroom_stew", () -> new ItemModFood(FoodList.ADVANCED_MUSHROOM_STEW)),
            empowered_meat = registerItem("empowered_meat", () -> new ItemModFood(FoodList.EMPOWERED_MEAT)),
            fruit_cake = registerItem("fruit_cake", () -> new ItemModFood(FoodList.FRUIT_CAKE)),
            donut = registerItem("donut", () -> new ItemModFood(FoodList.DONUT)),
            chicken_dinner = registerItem("chicken_dinner", () -> new ItemModFood(FoodList.CHICKEN_DINNER)),
            aquamarine_seeds = registerItem("aquamarine_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "aquamarine_plant")))),
            eucalyptus_root_seeds = registerItem("eucalyptus_root_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "eucalyptus_plant")))),
            firestock_seeds = registerItem("firestock_seeds", () -> new ItemNameBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "firestock_plant")), new Item.Properties())),
            hitchak_seeds = registerItem("hitchak_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "hitchak_plant")))),
            lamona_seeds = registerItem("lamona_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "lamona_plant")))),
            marsine_seeds = registerItem("marsine_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "marsine_plant")))),
            moonbulb_seeds = registerItem("moonbulb_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "moonbulb_plant")), () -> Blocks.GRASS_BLOCK)),
            pinfly_seeds = registerItem("pinfly_seeds", () -> new ItemNameBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "pinfly_plant")), new Item.Properties())),
            pink_glowbone_seeds = registerItem("pink_glowbone_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "pink_glowbone_plant")), () -> Blocks.GRASS_BLOCK)),
            purple_glowbone_seeds = registerItem("purple_glowbone_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "purple_glowbone_plant")), () -> Blocks.GRASS_BLOCK)),
            sky_plant_seeds = registerItem("sky_plant_seeds", () -> new ItemNameBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "sky_plant")), new Item.Properties())),
            tomato_seeds = registerItem("tomato_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "tomato_plant")))),
            veilo_seeds = registerItem("veilo_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "veilo_plant")))),
            white_mushroom_seeds = registerItem("white_mushroom_seeds", () -> new ItemModSeeds(() -> ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "white_mushroom_plant")))),
            brown_grizzle_egg = registerItem("brown_grizzle_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.BROWN_GRIZZLE.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            ehu_egg = registerItem("ehu_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.EHU.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            fyracryx_egg = registerItem("fyracryx_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.FYRACRYX.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            golem_of_rejuvenation_egg = registerItem("golem_of_rejuvenation_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.GOLEM_OF_REJUVENATION.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            husk_egg = registerItem("husk_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.HUSK.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            paratiku_egg = registerItem("paratiku_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.PARATIKU.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            seimer_egg = registerItem("seimer_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.SEIMER.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            smelter_egg = registerItem("smelter_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.SMELTER.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            snapper_egg = registerItem("snapper_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.SNAPPER.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            stone_golem_egg = registerItem("stone_golem_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.STONE_GOLEM.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            white_grizzle_egg = registerItem("white_grizzle_spawn_egg", () -> new ForgeSpawnEggItem(() -> EntityRegistry.WHITE_GRIZZLE.get(), 0xFFFFFF, 0xFFFFFF, new Item.Properties())),
            twilight_clock = registerItem("twilight_clock", () -> new ItemTwilightClock()),
            acid = registerItem("acid", () -> new ItemVethean()),
            amthirmis_lump = registerItem("amthirmis_lump", () -> new ItemVethean()),
            arksiane_lump = registerItem("arksiane_lump", () -> new ItemVethean()),
            backsword_template = registerItem("backsword_template", () -> new ItemVethean()),
            band_of_heiva_hunting = registerItem("band_of_heiva_hunting", () -> new ItemVethean()),
            bow_template = registerItem("bow_template", () -> new ItemVethean()),
            cannon_template = registerItem("cannon_template", () -> new ItemVethean()),
            cermile_lump = registerItem("cermile_lump", () -> new ItemVethean()),
            claw_template = registerItem("claw_template", () -> new ItemVethean()),
            clean_pearls = registerItem("clean_pearls", () -> new ItemVethean()),
            darven_arrow = registerItem("darven_arrow", () -> new ItemVethean()),
            darven_lump = registerItem("darven_lump", () -> new ItemVethean()),
            degraded_template = registerItem("degraded_template", () -> new ItemVethean()),
            demonized_template = registerItem("demonized_template", () -> new ItemVethean()),
            dirty_pearls = registerItem("dirty_pearls", () -> new ItemVethean()),
            disk_template = registerItem("disk_template", () -> new ItemVethean()),
            dissipator_template = registerItem("dissipator_template", () -> new ItemVethean()),
            dream_flint = registerItem("dream_flint", () -> new ItemDreamFlint()),
            ever_arrow = registerItem("ever_arrow", () -> new ItemVethean()),
            finished_template = registerItem("finished_template", () -> new ItemVethean()),
            glistening_template = registerItem("glistening_template", () -> new ItemVethean()),
            hammer_template = registerItem("hammer_template", () -> new ItemVethean()),
            heliosis_lump = registerItem("heliosis_lump", () -> new ItemVethean()),
            karos_arrow = registerItem("karos_arrow", () -> new ItemVethean()),
            karos_lump = registerItem("karos_lump", () -> new ItemVethean()),
            moon_clock = registerItem("moon_clock", () -> new ItemVethean()),
            pardimal_arrow = registerItem("pardimal_arrow", () -> new ItemVethean()),
            pardimal_lump = registerItem("pardimal_lump", () -> new ItemVethean()),
            polished_pearls = registerItem("polished_pearls", () -> new ItemVethean()),
            quadrotic_lump = registerItem("quadrotic_lump", () -> new ItemVethean()),
            rock_chunks = registerItem("rock_chunks", () -> new ItemVethean()),
            shiny_pearls = registerItem("shiny_pearls", () -> new ItemVethean()),
            staff_template = registerItem("staff_template", () -> new ItemVethean()),
            teaker_arrow = registerItem("teaker_arrow", () -> new ItemVethean()),
            teaker_lump = registerItem("teaker_lump", () -> new ItemVethean()),
            tormented_template = registerItem("tormented_template", () -> new ItemVethean()),
            nightmare_bed = registerItem("nightmare_bed", () -> new ItemNightmareBed()),
            realmite_axe = registerItem("realmite_axe", () -> new ItemModAxe(ToolStats.REALMITE_AXE)),
            arlemite_axe = registerItem("arlemite_axe", () -> new ItemModAxe(ToolStats.ARLEMITE_AXE)),
            rupee_axe = registerItem("rupee_axe", () -> new ItemModAxe(ToolStats.RUPEE_AXE)),
            terran_axe = registerItem("terran_axe", () -> new ItemModAxe(ToolStats.TERRAN_AXE)),
            bedrock_axe = registerItem("bedrock_axe", () -> new ItemModAxe(ToolStats.BEDROCK_AXE, new Item.Properties().fireResistant())),
            corrupted_axe = registerItem("corrupted_axe", () -> new ItemModAxe(ToolStats.CORRUPTED_AXE)),
            eden_axe = registerItem("eden_axe", () -> new ItemModAxe(ToolStats.EDEN_AXE, RarityList.EDEN)),
            wildwood_axe = registerItem("wildwood_axe", () -> new ItemModAxe(ToolStats.WILDWOOD_AXE, RarityList.WILDWOOD)),
            apalachia_axe = registerItem("apalachia_axe", () -> new ItemModAxe(ToolStats.APALACHIA_AXE, RarityList.APALACHIA)),
            skythern_axe = registerItem("skythern_axe", () -> new ItemModAxe(ToolStats.SKYTHERN_AXE, RarityList.SKYTHERN)),
            mortum_axe = registerItem("mortum_axe", () -> new ItemModAxe(ToolStats.MORTUM_AXE, RarityList.MORTUM)),
            divine_axe = registerItem("divine_axe", () -> new ItemModAxe(ToolStats.DIVINE_AXE, RarityList.DIVINE)),
            dream_axe = registerItem("dream_axe", () -> new ItemModAxe(ToolStats.DREAM_AXE)),
            apalachia_bow = registerItem("apalachia_bow", () -> new ItemModBow(RarityList.APALACHIA, ArrowType.GREATER_WILDWOOD_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "wildwood_arrow"))),
            soulfire_bow = registerItem("soulfire_bow", () -> new ItemModBow(ArrowType.SOULFIRE_ARROW, -1)),
            eden_bow = registerItem("eden_bow", () -> new ItemModBow(RarityList.EDEN, ArrowType.EDEN_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "eden_arrow"))),
            ender_bow = registerItem("ender_bow", () -> new ItemModBow(RarityList.ENDER, ArrowType.ENDER_ARROW, -1)),
            halite_bow = registerItem("halite_bow", () -> new ItemModBow(RarityList.HALITE, ArrowType.FURY_ARROW, -1, 36000, new ResourceLocation(DivineRPG.MODID, "fury_arrow"))),
            hunter_bow = registerItem("hunter_bow", () -> new ItemModBow(ArrowType.HUNTER_ARROW, 2500, new ResourceLocation("arrow"))),
            icicle_bow = registerItem("icicle_bow", () -> new ItemModBow(ArrowType.ICICLE_ARROW, 10000, 24000, new ResourceLocation("arrow"))),
            inferno_bow = registerItem("inferno_bow", () -> new ItemModBow(ArrowType.INFERNO_ARROW, 10000, ItemModBow.DEFAULT_MAX_USE_DURATION, null, new Item.Properties().durability(10000).fireResistant())),
            mortum_bow = registerItem("mortum_bow", () -> new ItemModBow(RarityList.MORTUM, ArrowType.FURY_ARROW, -1, new ResourceLocation(DivineRPG.MODID, "fury_arrow"))),
            shadow_bow = registerItem("shadow_bow", () -> new ItemModBow(ArrowType.SHADOW_ARROW, 10000, 36000, new ResourceLocation("arrow"))),
            skythern_bow = registerItem("skythern_bow", () -> new ItemModBow(RarityList.SKYTHERN, ArrowType.GREATER_WILDWOOD_ARROW, -1, 36000, new ResourceLocation(DivineRPG.MODID, "wildwood_arrow"))),
            snowstorm_bow = registerItem("snowstorm_bow", () -> new ItemModBow(ArrowType.SNOWSTORM_ARROW, -1)),
            twilight_bow = registerItem("twilight_bow", () -> new ItemModBow(ArrowType.FURY_ARROW, -1, 14400, new ResourceLocation(DivineRPG.MODID, "fury_arrow"))),
            wildwood_bow = registerItem("wildwood_bow", () -> new ItemModBow(RarityList.WILDWOOD, ArrowType.LESSER_WILDWOOD_ARROW, -1, 36000, new ResourceLocation(DivineRPG.MODID, "wildwood_arrow"))),
            apalachia_hoe = registerItem("apalachia_hoe", () -> new ItemModHoe(ToolStats.ARLEMITE_PICKAXE)),
            realmite_hoe = registerItem("realmite_hoe", () -> new ItemModHoe(ToolStats.REALMITE_PICKAXE)),
            arlemite_hoe = registerItem("arlemite_hoe", () -> new ItemModHoe(ToolStats.ARLEMITE_PICKAXE)),
            bedrock_hoe = registerItem("bedrock_hoe", () -> new ItemModHoe(ToolStats.BEDROCK_PICKAXE, new Item.Properties().fireResistant())),
            corrupted_hoe = registerItem("corrupted_hoe", () -> new ItemModHoe(ToolStats.CORRUPTED_PICKAXE)),
            divine_hoe = registerItem("divine_hoe", () -> new ItemModHoe(ToolStats.DIVINE_PICKAXE)),
            eden_hoe = registerItem("eden_hoe", () -> new ItemModHoe(ToolStats.EDEN_PICKAXE)),
            mortum_hoe = registerItem("mortum_hoe", () -> new ItemModHoe(ToolStats.MORTUM_PICKAXE)),
            rupee_hoe = registerItem("rupee_hoe", () -> new ItemModHoe(ToolStats.RUPEE_PICKAXE)),
            skythern_hoe = registerItem("skythern_hoe", () -> new ItemModHoe(ToolStats.SKYTHERN_PICKAXE)),
            terran_hoe = registerItem("terran_hoe", () -> new ItemModHoe(ToolStats.TERRAN_PICKAXE)),
            wildwood_hoe = registerItem("wildwood_hoe", () -> new ItemModHoe(ToolStats.WILDWOOD_PICKAXE)),
            realmite_pickaxe = registerItem("realmite_pickaxe", () -> new ItemModPickaxe(ToolStats.REALMITE_PICKAXE)),
            arlemite_pickaxe = registerItem("arlemite_pickaxe", () -> new ItemModPickaxe(ToolStats.ARLEMITE_PICKAXE)),
            rupee_pickaxe = registerItem("rupee_pickaxe", () -> new ItemModPickaxe(ToolStats.RUPEE_PICKAXE)),
            terran_pickaxe = registerItem("terran_pickaxe", () -> new ItemModPickaxe(ToolStats.TERRAN_PICKAXE)),
            bedrock_pickaxe = registerItem("bedrock_pickaxe", () -> new ItemModPickaxe(ToolStats.BEDROCK_PICKAXE, new Item.Properties().fireResistant())),
            corrupted_pickaxe = registerItem("corrupted_pickaxe", () -> new ItemModPickaxe(ToolStats.CORRUPTED_PICKAXE)),
            eden_pickaxe = registerItem("eden_pickaxe", () -> new ItemModPickaxe(ToolStats.EDEN_PICKAXE, RarityList.EDEN)),
            wildwood_pickaxe = registerItem("wildwood_pickaxe", () -> new ItemModPickaxe(ToolStats.WILDWOOD_PICKAXE, RarityList.WILDWOOD)),
            apalachia_pickaxe = registerItem("apalachia_pickaxe", () -> new ItemModPickaxe(ToolStats.APALACHIA_PICKAXE, RarityList.APALACHIA)),
            skythern_pickaxe = registerItem("skythern_pickaxe", () -> new ItemModPickaxe(ToolStats.SKYTHERN_PICKAXE, RarityList.SKYTHERN)),
            mortum_pickaxe = registerItem("mortum_pickaxe", () -> new ItemModPickaxe(ToolStats.MORTUM_PICKAXE, RarityList.MORTUM)),
            divine_pickaxe = registerItem("divine_pickaxe", () -> new ItemModPickaxe(ToolStats.DIVINE_PICKAXE, RarityList.DIVINE)),
            dream_pickaxe = registerItem("dream_pickaxe", () -> new ItemModPickaxe(ToolStats.DREAM_PICKAXE)),
            realmite_shovel = registerItem("realmite_shovel", () -> new ItemModShovel(ToolStats.REALMITE_SHOVEL)),
            arlemite_shovel = registerItem("arlemite_shovel", () -> new ItemModShovel(ToolStats.ARLEMITE_SHOVEL)),
            rupee_shovel = registerItem("rupee_shovel", () -> new ItemModShovel(ToolStats.RUPEE_SHOVEL)),
            terran_shovel = registerItem("terran_shovel", () -> new ItemModShovel(ToolStats.TERRAN_SHOVEL)),
            bedrock_shovel = registerItem("bedrock_shovel", () -> new ItemModShovel(ToolStats.BEDROCK_SHOVEL, new Item.Properties().fireResistant())),
            corrupted_shovel = registerItem("corrupted_shovel", () -> new ItemModShovel(ToolStats.CORRUPTED_SHOVEL)),
            eden_shovel = registerItem("eden_shovel", () -> new ItemModShovel(ToolStats.EDEN_SHOVEL, RarityList.EDEN)),
            wildwood_shovel = registerItem("wildwood_shovel", () -> new ItemModShovel(ToolStats.WILDWOOD_SHOVEL, RarityList.WILDWOOD)),
            apalachia_shovel = registerItem("apalachia_shovel", () -> new ItemModShovel(ToolStats.APALACHIA_SHOVEL, RarityList.APALACHIA)),
            skythern_shovel = registerItem("skythern_shovel", () -> new ItemModShovel(ToolStats.SKYTHERN_SHOVEL, RarityList.SKYTHERN)),
            mortum_shovel = registerItem("mortum_shovel", () -> new ItemModShovel(ToolStats.MORTUM_SHOVEL, RarityList.MORTUM)),
            divine_shovel = registerItem("divine_shovel", () -> new ItemModShovel(ToolStats.DIVINE_SHOVEL, RarityList.DIVINE)),
            dream_shovel = registerItem("dream_shovel", () -> new ItemModShovel(ToolStats.DREAM_SHOVEL)),
            apalachia_blade = registerItem("apalachia_blade", () -> new ItemModSword(RarityList.APALACHIA, ToolStats.APALACHIA_BLADE)),
            aquatic_dagger = registerItem("aquatic_dagger", () -> new ItemModSword(ToolStats.AQUA_DAGGER)),
            aquatic_maul = registerItem("aquatic_maul", () -> new ItemModSword(ToolStats.AQUA_MAUL)),
            aquatic_trident = registerItem("aquatic_trident", () -> new ItemModSword(ToolStats.AQUA_TRIDENT)),
            aquaton = registerItem("aquaton", () -> new ItemModSword(ToolStats.AQUATON)),
            aquatooth_maul = registerItem("aquatooth_maul", () -> new ItemModSword(ToolStats.AQUATOOTH_MAUL)),
            aquatooth_sword = registerItem("aquatooth_sword", () -> new ItemModSword(ToolStats.AQUATOOTH_SWORD)),
            arlemite_stabber = registerItem("arlemite_stabber", () -> new ItemModSword(ToolStats.ARLEMITE_STABBER)),
            bedrock_maul = registerItem("bedrock_maul", () -> new ItemModSword(ToolStats.BEDROCK_MAUL, new Item.Properties().fireResistant())),
            bedrock_sword = registerItem("bedrock_sword", () -> new ItemModSword(ToolStats.BEDROCK_SWORD, new Item.Properties().fireResistant())),
            bloodgem_sword = registerItem("bloodgem_sword", () -> new ItemModSword(ToolStats.BLOODGEM_SWORD)),
            soulfire_sword = registerItem("soulfire_sword", () -> new ItemModSword(ToolStats.SOULFIRE_SWORD)),
            corrupted_maul = registerItem("corrupted_maul", () -> new ItemModSword(ToolStats.CORRUPTED_MAUL)),
            crabclaw_maul = registerItem("crabclaw_maul", () -> new ItemModSword(ToolStats.CRABCLAW_MAUL)),
            cyclopsian_sword = registerItem("cyclopsian_sword", () -> new ItemModSword(ToolStats.CYCLOPSIAN_SWORD)),
            death_bringer = registerItem("death_bringer", () -> new ItemModSword(ToolStats.DEATH_BRINGER)),
            blue_divine_sword = registerItem("blue_divine_sword", () -> new ItemModSword(RarityList.BLUE, ToolStats.DIVINE_SWORD)),
            divine_sword = registerItem("divine_sword", () -> new ItemModSword(RarityList.DIVINE, ToolStats.DIVINE_SWORD)),
            gray_divine_sword = registerItem("gray_divine_sword", () -> new ItemModSword(RarityList.DARK, ToolStats.DIVINE_SWORD)),
            green_divine_sword = registerItem("green_divine_sword", () -> new ItemModSword(RarityList.GREEN, ToolStats.DIVINE_SWORD)),
            red_divine_sword = registerItem("red_divine_sword", () -> new ItemModSword(RarityList.RED, ToolStats.DIVINE_SWORD)),
            yellow_divine_sword = registerItem("yellow_divine_sword", () -> new ItemModSword(RarityList.YELLOW, ToolStats.DIVINE_SWORD)),
            armor_pouch = registerItem("armor_pouch", () -> new ItemArmorPouch(ChatFormatting.WHITE)),
            blue_armor_pouch = registerItem("blue_armor_pouch", () -> new ItemArmorPouch(ChatFormatting.BLUE)),
            gray_armor_pouch = registerItem("gray_armor_pouch", () -> new ItemArmorPouch(ChatFormatting.GRAY)),
            green_armor_pouch = registerItem("green_armor_pouch", () -> new ItemArmorPouch(ChatFormatting.GREEN)),
            red_armor_pouch = registerItem("red_armor_pouch", () -> new ItemArmorPouch(ChatFormatting.RED)),
            yellow_armor_pouch = registerItem("yellow_armor_pouch", () -> new ItemArmorPouch(ChatFormatting.YELLOW)),
            dual_claw = registerItem("dual_claw", () -> new ItemModSword(ToolStats.DUAL_CLAW)),
            eden_blade = registerItem("eden_blade", () -> new ItemModSword(RarityList.EDEN, ToolStats.EDEN_BLADE)),
            black_ender_sword = registerItem("black_ender_sword", () -> new ItemModSword(RarityList.DARK, ToolStats.ENDER_SWORD)),
            blue_ender_sword = registerItem("blue_ender_sword", () -> new ItemModSword(RarityList.BLUE, ToolStats.ENDER_SWORD)),
            ender_sword = registerItem("ender_sword", () -> new ItemModSword(RarityList.ENDER, ToolStats.ENDER_SWORD)),
            green_ender_sword = registerItem("green_ender_sword", () -> new ItemModSword(RarityList.GREEN, ToolStats.ENDER_SWORD)),
            red_ender_sword = registerItem("red_ender_sword", () -> new ItemModSword(RarityList.RED, ToolStats.ENDER_SWORD)),
            yellow_ender_sword = registerItem("yellow_ender_sword", () -> new ItemModSword(RarityList.YELLOW, ToolStats.ENDER_SWORD)),
            fury_maul = registerItem("fury_maul", () -> new ItemModSword(ToolStats.FURY_MAUL)),
            halite_blade = registerItem("halite_blade", () -> new ItemModSword(RarityList.HALITE, ToolStats.HALITE_BLADE)),
            livicia_sword = registerItem("livicia_sword", () -> new ItemModSword(ToolStats.LIVICIA_SWORD)),
            mortum_blade = registerItem("mortum_blade", () -> new ItemModSword(RarityList.MORTUM, ToolStats.MORTUM_BLADE)),
            ocean_knife = registerItem("ocean_knife", () -> new ItemModSword(ToolStats.OCEAN_KNIFE)),
            realmite_sword = registerItem("realmite_sword", () -> new ItemModSword(ToolStats.REALMITE_SWORD)),
            rupee_rapier = registerItem("rupee_rapier", () -> new ItemModSword(ToolStats.RUPEE_RAPIER)),
            sandslash = registerItem("sandslash", () -> new ItemModSword(ToolStats.SANDSLASH)),
            scorching_sword = registerItem("scorching_sword", () -> new ItemModSword(ToolStats.SCORCHING_SWORD)),
            shark_sword = registerItem("shark_sword", () -> new ItemModSword(ToolStats.SHARK_SWORD)),
            skythern_blade = registerItem("skythern_blade", () -> new ItemModSword(RarityList.SKYTHERN, ToolStats.SKYTHERN_BLADE)),
            slime_sword = registerItem("slime_sword", () -> new ItemModSword(ToolStats.SLIME_SWORD)),
            terran_dagger = registerItem("terran_dagger", () -> new ItemModSword(ToolStats.TERRAN_DAGGER)),
            terran_knife = registerItem("terran_knife", () -> new ItemModSword(ToolStats.TERRAN_KNIFE)),
            terran_maul = registerItem("terran_maul", () -> new ItemModSword(ToolStats.TERRAN_MAUL)),
            wildwood_blade = registerItem("wildwood_blade", () -> new ItemModSword(RarityList.WILDWOOD, ToolStats.WILDWOOD_BLADE)),
            apalachia_shickaxe = registerItem("apalachia_shickaxe", () -> new ItemShickaxe(RarityList.APALACHIA, ToolStats.APALACHIA_SHICKAXE)),
            arlemite_shickaxe = registerItem("arlemite_shickaxe", () -> new ItemShickaxe(ToolStats.ARLEMITE_SHICKAXE)),
            corrupted_shickaxe = registerItem("corrupted_shickaxe", () -> new ItemShickaxe(ToolStats.CORRUPTED_SHICKAXE)),
            divine_shickaxe = registerItem("divine_shickaxe", () -> new ItemShickaxe(RarityList.DIVINE, ToolStats.DIVINE_SHICKAXE)),
            eden_shickaxe = registerItem("eden_shickaxe", () -> new ItemShickaxe(RarityList.EDEN, ToolStats.EDEN_SHICKAXE)),
            halite_shickaxe = registerItem("halite_shickaxe", () -> new ItemShickaxe(RarityList.HALITE, ToolStats.HALITE_SHICKAXE)),
            mortum_shickaxe = registerItem("mortum_shickaxe", () -> new ItemShickaxe(RarityList.MORTUM, ToolStats.MORTUM_SHICKAXE)),
            rupee_shickaxe = registerItem("rupee_shickaxe", () -> new ItemShickaxe(ToolStats.RUPEE_SHICKAXE)),
            skythern_shickaxe = registerItem("skythern_shickaxe", () -> new ItemShickaxe(RarityList.SKYTHERN, ToolStats.SKYTHERN_SHICKAXE)),
            terran_shickaxe = registerItem("terran_shickaxe", () -> new ItemShickaxe(ToolStats.TERRAN_SHICKAXE)),
            wildwood_shickaxe = registerItem("wildwood_shickaxe", () -> new ItemShickaxe(RarityList.WILDWOOD, ToolStats.WILDWOOD_SHICKAXE)),
            apalachia_phaser = registerItem("apalachia_phaser", () -> new ItemModRanged(RarityList.APALACHIA, BulletType.APALACHIA_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            bowhead_cannon = registerItem("bowhead_cannon", () -> new ItemModRanged(BulletType.BOWHEAD_CANNON_SHOT, () -> SoundRegistry.GHAST_CANNON.get(), new ResourceLocation("cactus"), 1000, 12)),
            crabclaw_cannon = registerItem("crabclaw_cannon", () -> new ItemModRanged(BulletType.CRABCLAW_CANNON_SHOT, () -> SoundRegistry.GHAST_CANNON.get(), new ResourceLocation("cactus"), 1000, 12)),
            cyclopsian_staff = registerItem("cyclopsian_staff", () -> new ItemModRanged(BulletType.CYCLOPSIAN_STAFF_SHOT, () -> SoundRegistry.STAFF.get(), 600, 0)),
            eden_phaser = registerItem("eden_phaser", () -> new ItemModRanged(RarityList.EDEN, BulletType.EDEN_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            fractite_cannon = registerItem("fractite_cannon", () -> new ItemModRanged(BulletType.FRACTITE_CANNON_SHOT, () -> SoundRegistry.FRACTITE_CANNON.get(), new ResourceLocation(MODID, "ice_shards"), 10000, 0)),
            frost_cannon = registerItem("frost_cannon", () -> new ItemModRanged(BulletType.FROST_CANNON_SHOT, () -> SoundRegistry.FROST_CANNON.get(), new ResourceLocation("snowball"), 15000, 0)),
            frostclaw_cannon = registerItem("frostclaw_cannon", () -> new ItemModRanged(BulletType.FROSTCLAW_CANNON_SHOT, () -> SoundRegistry.FROSTCLAW_CANNON.get(), new ResourceLocation("cactus"), 10000, 0)),
            ghast_cannon = registerItem("ghast_cannon", () -> new ItemModRanged(BulletType.GHAST_CANNON_SHOT, () -> SoundRegistry.GHAST_CANNON.get(), 100, 20)),
            golden_fury = registerItem("golden_fury", () -> new ItemModRanged(BulletType.GOLDEN_FURY_SHOT, () -> SoundRegistry.BLITZ.get(), new ResourceLocation("gold_nugget"), -1, 0)),
            halite_phaser = registerItem("halite_phaser", () -> new ItemModRanged(RarityList.HALITE, BulletType.HALITE_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            maelstrom = registerItem("maelstrom", () -> new ItemModRanged(BulletType.MAELSTROM_SHOT, () -> SoundRegistry.GHAST_CANNON.get(), 100, 0)),
            mortum_phaser = registerItem("mortum_phaser", () -> new ItemModRanged(RarityList.MORTUM, BulletType.MORTUM_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            skythern_phaser = registerItem("skythern_phaser", () -> new ItemModRanged(RarityList.SKYTHERN, BulletType.SKYTHERN_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            wildwood_phaser = registerItem("wildwood_phaser", () -> new ItemModRanged( RarityList.WILDWOOD, BulletType.WILDWOOD_PHASER_SHOT, () -> SoundRegistry.PHASER.get(), 3000, 12)),
            aqua_torch = registerItem("aqua_torch", () -> new StandingAndWallBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "aqua_torch")), ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "aqua_wall_torch")), new Item.Properties(), Direction.EAST)),
            arcanium_torch = registerItem("arcanium_torch", () -> new StandingAndWallBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "arcanium_torch")), ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "arcanium_wall_torch")), new Item.Properties(), Direction.EAST)),
            eden_torch = registerItem("eden_torch", () -> new StandingAndWallBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "eden_torch")), ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "eden_wall_torch")), new Item.Properties(), Direction.EAST)),
            skeleton_torch = registerItem("skeleton_torch", () -> new StandingAndWallBlockItem(ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "skeleton_torch")), ForgeRegistries.BLOCKS.getValue(new ResourceLocation(DivineRPG.MODID, "skeleton_wall_torch")), new Item.Properties(), Direction.EAST)),
            raw_seng_meat = registerItem("raw_seng_meat", () -> new ItemModFood(FoodList.RAW_SENG_MEAT)),
            seng_steak = registerItem("seng_steak", () -> new ItemModFood(FoodList.COOKED_SENG_STEAK)),
            seng_fur = registerItem("seng_fur", () -> new ItemMod());

    //Armour
    public static final RegistryObject<Item>
            angelic_helmet = registerItem("angelic_helmet", () -> new ItemDivineArmor(ArmorStats.ANGELIC, EquipmentSlot.HEAD, angelicInfo)),
            angelic_chestplate = registerItem("angelic_chestplate", () -> new ItemDivineArmor(ArmorStats.ANGELIC, EquipmentSlot.CHEST, angelicInfo)),
            angelic_leggings = registerItem("angelic_leggings", () -> new ItemDivineArmor(ArmorStats.ANGELIC, EquipmentSlot.LEGS, angelicInfo)),
            angelic_boots = registerItem("angelic_boots", () -> new ItemDivineArmor(ArmorStats.ANGELIC, EquipmentSlot.FEET, angelicInfo)),

    apalachia_helmet = registerItem("apalachia_helmet", () -> new ItemDivineArmor(ArmorStats.APALACHIA, EquipmentSlot.HEAD, apInfo)),
            apalachia_chestplate = registerItem("apalachia_chestplate", () -> new ItemDivineArmor(ArmorStats.APALACHIA, EquipmentSlot.CHEST, apInfo)),
            apalachia_leggings = registerItem("apalachia_leggings", () -> new ItemDivineArmor(ArmorStats.APALACHIA, EquipmentSlot.LEGS, apInfo)),
            apalachia_boots = registerItem("apalachia_boots", () -> new ItemDivineArmor(ArmorStats.APALACHIA, EquipmentSlot.FEET, apInfo)),

    aquastrive_helmet = registerItem("aquastrive_helmet", () -> new ItemDivineArmor(ArmorStats.AQUASTRIVE, EquipmentSlot.HEAD, aquastriveInfo)),
            aquastrive_chestplate = registerItem("aquastrive_chestplate", () -> new ItemDivineArmor(ArmorStats.AQUASTRIVE, EquipmentSlot.CHEST, aquastriveInfo)),
            aquastrive_leggings = registerItem("aquastrive_leggings", () -> new ItemDivineArmor(ArmorStats.AQUASTRIVE, EquipmentSlot.LEGS, aquastriveInfo)),
            aquastrive_boots = registerItem("aquastrive_boots", () -> new ItemDivineArmor(ArmorStats.AQUASTRIVE, EquipmentSlot.FEET, aquastriveInfo)),

    arlemite_helmet = registerItem("arlemite_helmet", () -> new ItemDivineArmor(ArmorStats.ARLEMITE, EquipmentSlot.HEAD, arlemiteInfo)),
            arlemite_chestplate = registerItem("arlemite_chestplate", () -> new ItemDivineArmor(ArmorStats.ARLEMITE, EquipmentSlot.CHEST, arlemiteInfo)),
            arlemite_leggings = registerItem("arlemite_leggings", () -> new ItemDivineArmor(ArmorStats.ARLEMITE, EquipmentSlot.LEGS, arlemiteInfo)),
            arlemite_boots = registerItem("arlemite_boots", () -> new ItemDivineArmor(ArmorStats.ARLEMITE, EquipmentSlot.FEET, arlemiteInfo)),

    awakened_halite_helmet = registerItem("awakened_halite_helmet", () -> new ItemDivineArmor(ArmorStats.AWAKENED_HALITE, EquipmentSlot.HEAD, awakened_halInfo)),
            awakened_halite_chestplate = registerItem("awakened_halite_chestplate", () -> new ItemDivineArmor(ArmorStats.AWAKENED_HALITE, EquipmentSlot.CHEST, awakened_halInfo)),
            awakened_halite_leggings = registerItem("awakened_halite_leggings", () -> new ItemDivineArmor(ArmorStats.AWAKENED_HALITE, EquipmentSlot.LEGS, awakened_halInfo)),
            awakened_halite_boots = registerItem("awakened_halite_boots", () -> new ItemDivineArmor(ArmorStats.AWAKENED_HALITE, EquipmentSlot.FEET, awakened_halInfo)),

    bedrock_helmet = registerItem("bedrock_helmet", () -> new ItemDivineArmor(ArmorStats.BEDROCK, EquipmentSlot.HEAD, bedrockInfo, new Item.Properties().fireResistant())),
            bedrock_chestplate = registerItem("bedrock_chestplate", () -> new ItemDivineArmor(ArmorStats.BEDROCK, EquipmentSlot.CHEST, bedrockInfo, new Item.Properties().fireResistant())),
            bedrock_leggings = registerItem("bedrock_leggings", () -> new ItemDivineArmor(ArmorStats.BEDROCK, EquipmentSlot.LEGS, bedrockInfo, new Item.Properties().fireResistant())),
            bedrock_boots = registerItem("bedrock_boots", () -> new ItemDivineArmor(ArmorStats.BEDROCK, EquipmentSlot.FEET, bedrockInfo, new Item.Properties().fireResistant())),

    blue_ender_helmet = registerItem("blue_ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            blue_ender_chestplate = registerItem("blue_ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            blue_ender_leggings = registerItem("blue_ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            blue_ender_boots = registerItem("blue_ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    blue_rupee_helmet = registerItem("blue_rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            blue_rupee_chestplate = registerItem("blue_rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            blue_rupee_leggings = registerItem("blue_rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            blue_rupee_boots = registerItem("blue_rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    corrupted_helmet = registerItem("corrupted_helmet", () -> new ItemDivineArmor(ArmorStats.CORRUPTED, EquipmentSlot.HEAD, corruptedInfo)),
            corrupted_chestplate = registerItem("corrupted_chestplate", () -> new ItemDivineArmor(ArmorStats.CORRUPTED, EquipmentSlot.CHEST, corruptedInfo)),
            corrupted_leggings = registerItem("corrupted_leggings", () -> new ItemDivineArmor(ArmorStats.CORRUPTED, EquipmentSlot.LEGS, corruptedInfo)),
            corrupted_boots = registerItem("corrupted_boots", () -> new ItemDivineArmor(ArmorStats.CORRUPTED, EquipmentSlot.FEET, corruptedInfo)),

    divine_helmet = registerItem("divine_helmet", () -> new ItemDivineArmor(ArmorStats.DIVINE, EquipmentSlot.HEAD, divineInfo)),
            divine_chestplate = registerItem("divine_chestplate", () -> new ItemDivineArmor(ArmorStats.DIVINE, EquipmentSlot.CHEST, divineInfo)),
            divine_leggings = registerItem("divine_leggings", () -> new ItemDivineArmor(ArmorStats.DIVINE, EquipmentSlot.LEGS, divineInfo)),
            divine_boots = registerItem("divine_boots", () -> new ItemDivineArmor(ArmorStats.DIVINE, EquipmentSlot.FEET, divineInfo)),

    eden_helmet = registerItem("eden_helmet", () -> new ItemDivineArmor(ArmorStats.EDEN, EquipmentSlot.HEAD, edenInfo)),
            eden_chestplate = registerItem("eden_chestplate", () -> new ItemDivineArmor(ArmorStats.EDEN, EquipmentSlot.CHEST, edenInfo)),
            eden_leggings = registerItem("eden_leggings", () -> new ItemDivineArmor(ArmorStats.EDEN, EquipmentSlot.LEGS, edenInfo)),
            eden_boots = registerItem("eden_boots", () -> new ItemDivineArmor(ArmorStats.EDEN, EquipmentSlot.FEET, edenInfo)),

    elite_realmite_helmet = registerItem("elite_realmite_helmet", () -> new ItemDivineArmor(ArmorStats.ELITE_REALMITE, EquipmentSlot.HEAD, eliteRealmiteInfo)),
            elite_realmite_chestplate = registerItem("elite_realmite_chestplate", () -> new ItemDivineArmor(ArmorStats.ELITE_REALMITE, EquipmentSlot.CHEST, eliteRealmiteInfo)),
            elite_realmite_leggings = registerItem("elite_realmite_leggings", () -> new ItemDivineArmor(ArmorStats.ELITE_REALMITE, EquipmentSlot.LEGS, eliteRealmiteInfo)),
            elite_realmite_boots = registerItem("elite_realmite_boots", () -> new ItemDivineArmor(ArmorStats.ELITE_REALMITE, EquipmentSlot.FEET, eliteRealmiteInfo)),

    ender_helmet = registerItem("ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            ender_chestplate = registerItem("ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            ender_leggings = registerItem("ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            ender_boots = registerItem("ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    frozen_helmet = registerItem("frozen_helmet", () -> new ItemDivineArmor(ArmorStats.FROZEN, EquipmentSlot.HEAD, frozenInfo)),
            frozen_chestplate = registerItem("frozen_chestplate", () -> new ItemDivineArmor(ArmorStats.FROZEN, EquipmentSlot.CHEST, frozenInfo)),
            frozen_leggings = registerItem("frozen_leggings", () -> new ItemDivineArmor(ArmorStats.FROZEN, EquipmentSlot.LEGS, frozenInfo)),
            frozen_boots = registerItem("frozen_boots", () -> new ItemDivineArmor(ArmorStats.FROZEN, EquipmentSlot.FEET, frozenInfo)),

    gray_ender_helmet = registerItem("gray_ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            gray_ender_chestplate = registerItem("gray_ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            gray_ender_leggings = registerItem("gray_ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            gray_ender_boots = registerItem("gray_ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    rupee_helmet = registerItem("rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            rupee_chestplate = registerItem("rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            rupee_leggings = registerItem("rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            rupee_boots = registerItem("rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    green_ender_helmet = registerItem("green_ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            green_ender_chestplate = registerItem("green_ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            green_ender_leggings = registerItem("green_ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            green_ender_boots = registerItem("green_ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    gray_rupee_helmet = registerItem("gray_rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            gray_rupee_chestplate = registerItem("gray_rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            gray_rupee_leggings = registerItem("gray_rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            gray_rupee_boots = registerItem("gray_rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    green_rupee_helmet = registerItem("green_rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            green_rupee_chestplate = registerItem("green_rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            green_rupee_leggings = registerItem("green_rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            green_rupee_boots = registerItem("green_rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    halite_helmet = registerItem("halite_helmet", () -> new ItemDivineArmor(ArmorStats.HALITE, EquipmentSlot.HEAD, halInfo)),
            halite_chestplate = registerItem("halite_chestplate", () -> new ItemDivineArmor(ArmorStats.HALITE, EquipmentSlot.CHEST, halInfo)),
            halite_leggings = registerItem("halite_leggings", () -> new ItemDivineArmor(ArmorStats.HALITE, EquipmentSlot.LEGS, halInfo)),
            halite_boots = registerItem("halite_boots", () -> new ItemDivineArmor(ArmorStats.HALITE, EquipmentSlot.FEET, halInfo)),

    inferno_helmet = registerItem("inferno_helmet", () -> new ItemDivineArmor(ArmorStats.INFERNO, EquipmentSlot.HEAD, infernoInfo, new Item.Properties().fireResistant())),
            inferno_chestplate = registerItem("inferno_chestplate", () -> new ItemDivineArmor(ArmorStats.INFERNO, EquipmentSlot.CHEST, infernoInfo, new Item.Properties().fireResistant())),
            inferno_leggings = registerItem("inferno_leggings", () -> new ItemDivineArmor(ArmorStats.INFERNO, EquipmentSlot.LEGS, infernoInfo, new Item.Properties().fireResistant())),
            inferno_boots = registerItem("inferno_boots", () -> new ItemDivineArmor(ArmorStats.INFERNO, EquipmentSlot.FEET, infernoInfo, new Item.Properties().fireResistant())),

    jack_o_man_helmet = registerItem("jack_o_man_helmet", () -> new ItemDivineArmor(ArmorStats.JACK_O_MAN, EquipmentSlot.HEAD, jackomanInfo)),
            jack_o_man_chestplate = registerItem("jack_o_man_chestplate", () -> new ItemDivineArmor(ArmorStats.JACK_O_MAN, EquipmentSlot.CHEST, jackomanInfo)),
            jack_o_man_leggings = registerItem("jack_o_man_leggings", () -> new ItemDivineArmor(ArmorStats.JACK_O_MAN, EquipmentSlot.LEGS, jackomanInfo)),
            jack_o_man_boots = registerItem("jack_o_man_boots", () -> new ItemDivineArmor(ArmorStats.JACK_O_MAN, EquipmentSlot.FEET, jackomanInfo)),

    jungle_helmet = registerItem("jungle_helmet", () -> new ItemDivineArmor(ArmorStats.JUNGLE, EquipmentSlot.HEAD, jungleInfo)),
            jungle_chestplate = registerItem("jungle_chestplate", () -> new ItemDivineArmor(ArmorStats.JUNGLE, EquipmentSlot.CHEST, jungleInfo)),
            jungle_leggings = registerItem("jungle_leggings", () -> new ItemDivineArmor(ArmorStats.JUNGLE, EquipmentSlot.LEGS, jungleInfo)),
            jungle_boots = registerItem("jungle_boots", () -> new ItemDivineArmor(ArmorStats.JUNGLE, EquipmentSlot.FEET, jungleInfo)),

    korma_helmet = registerItem("korma_helmet", () -> new ItemDivineArmor(ArmorStats.KORMA, EquipmentSlot.HEAD, kormInfo)),
            korma_chestplate = registerItem("korma_chestplate", () -> new ItemDivineArmor(ArmorStats.KORMA, EquipmentSlot.CHEST, kormInfo)),
            korma_leggings = registerItem("korma_leggings", () -> new ItemDivineArmor(ArmorStats.KORMA, EquipmentSlot.LEGS, kormInfo)),
            korma_boots = registerItem("korma_boots", () -> new ItemDivineArmor(ArmorStats.KORMA, EquipmentSlot.FEET, kormInfo)),

    kraken_helmet = registerItem("kraken_helmet", () -> new ItemDivineArmor(ArmorStats.KRAKEN, EquipmentSlot.HEAD, krakenInfo)),
            kraken_chestplate = registerItem("kraken_chestplate", () -> new ItemDivineArmor(ArmorStats.KRAKEN, EquipmentSlot.CHEST, krakenInfo)),
            kraken_leggings = registerItem("kraken_leggings", () -> new ItemDivineArmor(ArmorStats.KRAKEN, EquipmentSlot.LEGS, krakenInfo)),
            kraken_boots = registerItem("kraken_boots", () -> new ItemDivineArmor(ArmorStats.KRAKEN, EquipmentSlot.FEET, krakenInfo)),

    mortum_helmet = registerItem("mortum_helmet", () -> new ItemDivineArmor(ArmorStats.MORTUM, EquipmentSlot.HEAD, mortInfo)),
            mortum_chestplate = registerItem("mortum_chestplate", () -> new ItemDivineArmor(ArmorStats.MORTUM, EquipmentSlot.CHEST, mortInfo)),
            mortum_leggings = registerItem("mortum_leggings", () -> new ItemDivineArmor(ArmorStats.MORTUM, EquipmentSlot.LEGS, mortInfo)),
            mortum_boots = registerItem("mortum_boots", () -> new ItemDivineArmor(ArmorStats.MORTUM, EquipmentSlot.FEET, mortInfo)),

    realmite_helmet = registerItem("realmite_helmet", () -> new ItemDivineArmor(ArmorStats.REALMITE, EquipmentSlot.HEAD)),
            realmite_chestplate = registerItem("realmite_chestplate", () -> new ItemDivineArmor(ArmorStats.REALMITE, EquipmentSlot.CHEST)),
            realmite_leggings = registerItem("realmite_leggings", () -> new ItemDivineArmor(ArmorStats.REALMITE, EquipmentSlot.LEGS)),
            realmite_boots = registerItem("realmite_boots", () -> new ItemDivineArmor(ArmorStats.REALMITE, EquipmentSlot.FEET)),

    red_ender_helmet = registerItem("red_ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            red_ender_chestplate = registerItem("red_ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            red_ender_leggings = registerItem("red_ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            red_ender_boots = registerItem("red_ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    red_rupee_helmet = registerItem("red_rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            red_rupee_chestplate = registerItem("red_rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            red_rupee_leggings = registerItem("red_rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            red_rupee_boots = registerItem("red_rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    seng_fur_helmet = registerItem("seng_fur_helmet", () -> new ItemDivineArmor(ArmorStats.SENG_FUR, EquipmentSlot.HEAD, sengFurInfo)),
            seng_fur_chestplate = registerItem("seng_fur_chestplate", () -> new ItemDivineArmor(ArmorStats.SENG_FUR, EquipmentSlot.CHEST, sengFurInfo)),
            seng_fur_leggings = registerItem("seng_fur_leggings", () -> new ItemDivineArmor(ArmorStats.SENG_FUR, EquipmentSlot.LEGS, sengFurInfo)),
            seng_fur_boots = registerItem("seng_fur_boots", () -> new ItemDivineArmor(ArmorStats.SENG_FUR, EquipmentSlot.FEET, sengFurInfo)),

    shadow_helmet = registerItem("shadow_helmet", () -> new ItemDivineArmor(ArmorStats.SHADOW, EquipmentSlot.HEAD, shadowInfo)),
            shadow_chestplate = registerItem("shadow_chestplate", () -> new ItemDivineArmor(ArmorStats.SHADOW, EquipmentSlot.CHEST, shadowInfo)),
            shadow_leggings = registerItem("shadow_leggings", () -> new ItemDivineArmor(ArmorStats.SHADOW, EquipmentSlot.LEGS, shadowInfo)),
            shadow_boots = registerItem("shadow_boots", () -> new ItemDivineArmor(ArmorStats.SHADOW, EquipmentSlot.FEET, shadowInfo)),

    skeleman_helmet = registerItem("skeleman_helmet", () -> new ItemDivineArmor(ArmorStats.SKELEMAN, EquipmentSlot.HEAD, skelemanInfo)),
            skeleman_chestplate = registerItem("skeleman_chestplate", () -> new ItemDivineArmor(ArmorStats.SKELEMAN, EquipmentSlot.CHEST, skelemanInfo)),
            skeleman_leggings = registerItem("skeleman_leggings", () -> new ItemDivineArmor(ArmorStats.SKELEMAN, EquipmentSlot.LEGS, skelemanInfo)),
            skeleman_boots = registerItem("skeleman_boots", () -> new ItemDivineArmor(ArmorStats.SKELEMAN, EquipmentSlot.FEET, skelemanInfo)),

    skythern_helmet = registerItem("skythern_helmet", () -> new ItemDivineArmor(ArmorStats.SKYTHERN, EquipmentSlot.HEAD, skyInfo)),
            skythern_chestplate = registerItem("skythern_chestplate", () -> new ItemDivineArmor(ArmorStats.SKYTHERN, EquipmentSlot.CHEST, skyInfo)),
            skythern_leggings = registerItem("skythern_leggings", () -> new ItemDivineArmor(ArmorStats.SKYTHERN, EquipmentSlot.LEGS, skyInfo)),
            skythern_boots = registerItem("skythern_boots", () -> new ItemDivineArmor(ArmorStats.SKYTHERN, EquipmentSlot.FEET, skyInfo)),

    terran_helmet = registerItem("terran_helmet", () -> new ItemDivineArmor(ArmorStats.TERRAN, EquipmentSlot.HEAD, terranInfo)),
            terran_chestplate = registerItem("terran_chestplate", () -> new ItemDivineArmor(ArmorStats.TERRAN, EquipmentSlot.CHEST, terranInfo)),
            terran_leggings = registerItem("terran_leggings", () -> new ItemDivineArmor(ArmorStats.TERRAN, EquipmentSlot.LEGS, terranInfo)),
            terran_boots = registerItem("terran_boots", () -> new ItemDivineArmor(ArmorStats.TERRAN, EquipmentSlot.FEET, terranInfo)),

    torridite_helmet = registerItem("torridite_helmet", () -> new ItemDivineArmor(ArmorStats.TORRIDITE, EquipmentSlot.HEAD, torriditeInfo, new Item.Properties().fireResistant())),
            torridite_chestplate = registerItem("torridite_chestplate", () -> new ItemDivineArmor(ArmorStats.TORRIDITE, EquipmentSlot.CHEST, torriditeInfo, new Item.Properties().fireResistant())),
            torridite_leggings = registerItem("torridite_leggings", () -> new ItemDivineArmor(ArmorStats.TORRIDITE, EquipmentSlot.LEGS, torriditeInfo, new Item.Properties().fireResistant())),
            torridite_boots = registerItem("torridite_boots", () -> new ItemDivineArmor(ArmorStats.TORRIDITE, EquipmentSlot.FEET, torriditeInfo, new Item.Properties().fireResistant())),

    vemos_helmet = registerItem("vemos_helmet", () -> new ItemDivineArmor(ArmorStats.VEMOS, EquipmentSlot.HEAD, vemInfo)),
            vemos_chestplate = registerItem("vemos_chestplate", () -> new ItemDivineArmor(ArmorStats.VEMOS, EquipmentSlot.CHEST, vemInfo)),
            vemos_leggings = registerItem("vemos_leggings", () -> new ItemDivineArmor(ArmorStats.VEMOS, EquipmentSlot.LEGS, vemInfo)),
            vemos_boots = registerItem("vemos_boots", () -> new ItemDivineArmor(ArmorStats.VEMOS, EquipmentSlot.FEET, vemInfo)),

    wildwood_helmet = registerItem("wildwood_helmet", () -> new ItemDivineArmor(ArmorStats.WILDWOOD, EquipmentSlot.HEAD, wildInfo)),
            wildwood_chestplate = registerItem("wildwood_chestplate", () -> new ItemDivineArmor(ArmorStats.WILDWOOD, EquipmentSlot.CHEST, wildInfo)),
            wildwood_leggings = registerItem("wildwood_leggings", () -> new ItemDivineArmor(ArmorStats.WILDWOOD, EquipmentSlot.LEGS, wildInfo)),
            wildwood_boots = registerItem("wildwood_boots", () -> new ItemDivineArmor(ArmorStats.WILDWOOD, EquipmentSlot.FEET, wildInfo)),

    wither_reaper_helmet = registerItem("wither_reaper_helmet", () -> new ItemDivineArmor(ArmorStats.WITHER_REAPER, EquipmentSlot.HEAD, witherReaperInfo)),
            wither_reaper_chestplate = registerItem("wither_reaper_chestplate", () -> new ItemDivineArmor(ArmorStats.WITHER_REAPER, EquipmentSlot.CHEST, witherReaperInfo)),
            wither_reaper_leggings = registerItem("wither_reaper_leggings", () -> new ItemDivineArmor(ArmorStats.WITHER_REAPER, EquipmentSlot.LEGS, witherReaperInfo)),
            wither_reaper_boots = registerItem("wither_reaper_boots", () -> new ItemDivineArmor(ArmorStats.WITHER_REAPER, EquipmentSlot.FEET, witherReaperInfo)),

    yellow_ender_helmet = registerItem("yellow_ender_helmet", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.HEAD, enderInfo)),
            yellow_ender_chestplate = registerItem("yellow_ender_chestplate", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.CHEST, enderInfo)),
            yellow_ender_leggings = registerItem("yellow_ender_leggings", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.LEGS, enderInfo)),
            yellow_ender_boots = registerItem("yellow_ender_boots", () -> new ItemDivineArmor(ArmorStats.ENDER, EquipmentSlot.FEET, enderInfo)),

    yellow_rupee_helmet = registerItem("yellow_rupee_helmet", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.HEAD, rupeeInfo)),
            yellow_rupee_chestplate = registerItem("yellow_rupee_chestplate", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.CHEST, rupeeInfo)),
            yellow_rupee_leggings = registerItem("yellow_rupee_leggings", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.LEGS, rupeeInfo)),
            yellow_rupee_boots = registerItem("yellow_rupee_boots", () -> new ItemDivineArmor(ArmorStats.RUPEE, EquipmentSlot.FEET, rupeeInfo)),

    degraded_helmet = registerItem("degraded_helmet", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.HEAD, basicHelmInfo)),
            degraded_hood = registerItem("degraded_hood", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.HEAD, basicHoodInfo)),
            degraded_mask = registerItem("degraded_mask", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.HEAD, basicMaskInfo)),
            degraded_chestplate = registerItem("degraded_chestplate", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.CHEST, new ArmorInfo())),
            degraded_leggings = registerItem("degraded_leggings", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.LEGS, new ArmorInfo())),
            degraded_boots = registerItem("degraded_boots", () -> new ItemDivineArmor(ArmorStats.DEGRADED, EquipmentSlot.FEET, new ArmorInfo())),

    demonized_helmet = registerItem("demonized_helmet", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.HEAD, demonizedHelmInfo)),
            demonized_hood = registerItem("demonized_hood", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.HEAD, demonizedHoodInfo)),
            demonized_mask = registerItem("demonized_mask", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.HEAD, demonizedMaskInfo)),
            demonized_chestplate = registerItem("demonized_chestplate", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.CHEST, new ArmorInfo())),
            demonized_leggings = registerItem("demonized_leggings", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.LEGS, new ArmorInfo())),
            demonized_boots = registerItem("demonized_boots", () -> new ItemDivineArmor(ArmorStats.DEMONIZED, EquipmentSlot.FEET, new ArmorInfo())),

    finished_helmet = registerItem("finished_helmet", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.HEAD)),
            finished_hood = registerItem("finished_hood", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.HEAD)),
            finished_mask = registerItem("finished_mask", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.HEAD)),
            finished_chestplate = registerItem("finished_chestplate", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.CHEST)),
            finished_leggings = registerItem("finished_leggings", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.LEGS)),
            finished_boots = registerItem("finished_boots", () -> new ItemDivineArmor(ArmorStats.FINISHED, EquipmentSlot.FEET)),

    glistening_helmet = registerItem("glistening_helmet", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.HEAD, glisteningHelmInfo)),
            glistening_hood = registerItem("glistening_hood", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.HEAD, glisteningHoodInfo)),
            glistening_mask = registerItem("glistening_mask", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.HEAD, glisteningMaskInfo)),
            glistening_chestplate = registerItem("glistening_chestplate", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.CHEST, new ArmorInfo())),
            glistening_leggings = registerItem("glistening_leggings", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.LEGS, new ArmorInfo())),
            glistening_boots = registerItem("glistening_boots", () -> new ItemDivineArmor(ArmorStats.GLISTENING, EquipmentSlot.FEET, new ArmorInfo())),

    tormented_helmet = registerItem("tormented_helmet", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.HEAD, tormentedHelmInfo)),
            tormented_hood = registerItem("tormented_hood", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.HEAD, tormentedHoodInfo)),
            tormented_mask = registerItem("tormented_mask", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.HEAD, tormentedMaskInfo)),
            tormented_chestplate = registerItem("tormented_chestplate", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.CHEST, new ArmorInfo())),
            tormented_leggings = registerItem("tormented_leggings", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.LEGS, new ArmorInfo())),
            tormented_boots = registerItem("tormented_boots", () -> new ItemDivineArmor(ArmorStats.TORMENTED, EquipmentSlot.FEET, new ArmorInfo()));

    public static MutableComponent getArmorAbility(String keyPart, Object... params) {
        String id = String.format("tooltip.armor_info.%s", keyPart);

        return params == null || params.length < 1
                ? MutableComponent.create(new TranslatableContents(id))
                : MutableComponent.create(new TranslatableContents(id, params));
    }

    private static <T extends Item> RegistryObject<T> registerItem(String registryId, Supplier<T> item) {
        return ITEMS.register(registryId, item);
    }
}