package divinerpg.registries;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.storage.loot.LootTable;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

import static divinerpg.DivineRPG.MODID;

public class LootTableRegistry {
    private static final Set<ResourceKey<LootTable>> LOCATIONS = new HashSet<>();
    private static final Set<ResourceKey<LootTable>> IMMUTABLE_LOCATIONS = Collections.unmodifiableSet(LOCATIONS);

    public static final ResourceKey<LootTable> AMETHYST_GEODE = register("chests/overworld/amethyst_geode");
    public static final ResourceKey<LootTable> ANCIENT_TOMB = register("chests/overworld/ancient_tomb");
    public static final ResourceKey<LootTable> LIVESTOCK_MERCHANT_HUT = register("chests/overworld/livestock_merchant_hut");
    public static final ResourceKey<LootTable> ICEIKA_DUNGEON = register("chests/iceika/dungeon");
    public static final ResourceKey<LootTable> ICEIKA_HUT = register("chests/iceika/hut");
    public static final ResourceKey<LootTable> GROGLIN_VILLAGE = register("chests/iceika/groglin_village");
    public static final ResourceKey<LootTable> GRUZZORLUG_VILLAGE = register("chests/iceika/gruzzorlug_village");
    public static final ResourceKey<LootTable> BANQUET_HALL = register("chests/arcana/banquet_hall");
    public static final ResourceKey<LootTable> UTILITY_HALLWAY = register("chests/arcana/utility_hallway");
    public static final ResourceKey<LootTable> EDEN_HUT = register("chests/twilight/eden/hut");
    public static final ResourceKey<LootTable> SKYTHERN_HUT = register("chests/twilight/skythern/hut");
    public static final ResourceKey<LootTable> WILDWOOD_HUT = register("chests/twilight/wildwood/hut");
    public static final ResourceKey<LootTable> CRYPT = register("chests/vethea/crypt");
    public static final ResourceKey<LootTable> KAROS_MADHOUSE = register("chests/vethea/karos_madhouse");
    public static final ResourceKey<LootTable> QUADROTIC_POST = register("chests/vethea/quadrotic_post");
    public static final ResourceKey<LootTable> RAGLOK_CHAMBER = register("chests/vethea/raglok_chamber");
    public static final ResourceKey<LootTable> TEMPLE_BOTTOM = register("chests/vethea/temple_bottom");
    public static final ResourceKey<LootTable> TEMPLE_MIDDLE = register("chests/vethea/temple_middle");
    public static final ResourceKey<LootTable> TEMPLE_TOP = register("chests/vethea/temple_top");
    public static final ResourceKey<LootTable> WRECK_HALL = register("chests/vethea/wreck_hall");
    public static final ResourceKey<LootTable> ANCIENT_ENTITY = register("entities/ancient_entity");
    public static final ResourceKey<LootTable> THE_WATCHER = register("entities/the_watcher");
    public static final ResourceKey<LootTable> KING_OF_SCORCHERS = register("entities/king_of_scorchers");
    public static final ResourceKey<LootTable> KITRA = register("entities/kitra");
    public static final ResourceKey<LootTable> AYERACO = register("entities/ayeraco");
    public static final ResourceKey<LootTable> DRAMIX = register("entities/dramix");
    public static final ResourceKey<LootTable> PARASECTA = register("entities/parasecta");
    public static final ResourceKey<LootTable> SUNSTORM = register("entities/sunstorm");
    public static final ResourceKey<LootTable> TERMASECT = register("entities/termasect");
    public static final ResourceKey<LootTable> ETERNAL_ARCHER = register("entities/eternal_archer");
    public static final ResourceKey<LootTable> EXPERIENCED_CORI = register("entities/experienced_cori");
    public static final ResourceKey<LootTable> VAMACHERON = register("entities/vamacheron");
    public static final ResourceKey<LootTable> KAROT = register("entities/karot");
    public static final ResourceKey<LootTable> TWILIGHT_DEMON = register("entities/twilight_demon");
    public static final ResourceKey<LootTable> DENSOS = register("entities/densos");
    public static final ResourceKey<LootTable> REYVOR = register("entities/reyvor");
    public static final ResourceKey<LootTable> SOUL_FIEND = register("entities/soul_fiend");
    public static final ResourceKey<LootTable> HIVE_QUEEN = register("entities/hive_queen");
    public static final ResourceKey<LootTable> KAROS = register("entities/karos");
    public static final ResourceKey<LootTable> LADY_LUNA = register("entities/lady_luna");
    public static final ResourceKey<LootTable> QUADRO = register("entities/quadro");
    public static final ResourceKey<LootTable> RAGLOK = register("entities/raglok");
    public static final ResourceKey<LootTable> WRECK = register("entities/wreck");
    public static final ResourceKey<LootTable> SNAPPER = register("entities/snapper");
    public static final ResourceKey<LootTable> EHU = register("entities/ehu");
    public static final ResourceKey<LootTable> HUSK = register("entities/husk");
    public static final ResourceKey<LootTable> BROWN_GRIZZLE = register("entities/brown_grizzle");
    public static final ResourceKey<LootTable> WHITE_GRIZZLE = register("entities/white_grizzle");
    public static final ResourceKey<LootTable> STONE_GOLEM = register("entities/stone_golem");
    public static final ResourceKey<LootTable> SMELTER = register("entities/smelter");
    public static final ResourceKey<LootTable> LIVESTOCK_MERCHANT = register("entities/livestock_merchant");
    public static final ResourceKey<LootTable> JACK_O_MAN = register("entities/jack_o_man");
    public static final ResourceKey<LootTable> CYCLOPS = register("entities/cyclops");
    public static final ResourceKey<LootTable> KOBBLIN = register("entities/kobblin");
    public static final ResourceKey<LootTable> PUMPKIN_SPIDER = register("entities/pumpkin_spider");
    public static final ResourceKey<LootTable> JUNGLE_BAT = register("entities/jungle_bat");
    public static final ResourceKey<LootTable> JUNGLE_SPIDER = register("entities/jungle_spider");
    public static final ResourceKey<LootTable> JUNGLE_DRAMCRYX = register("entities/jungle_dramcryx");
    public static final ResourceKey<LootTable> SAGUARO_WORM = register("entities/saguaro_worm");
    public static final ResourceKey<LootTable> DESERT_CRAWLER = register("entities/desert_crawler");
    public static final ResourceKey<LootTable> ARID_WARRIOR = register("entities/arid_warrior");
    public static final ResourceKey<LootTable> GLACON = register("entities/glacon");
    public static final ResourceKey<LootTable> FROST = register("entities/frost");
    public static final ResourceKey<LootTable> CRAB = register("entities/crab");
    public static final ResourceKey<LootTable> KING_CRAB = register("entities/king_crab");
    public static final ResourceKey<LootTable> AEQUOREA = register("entities/aequorea");
    public static final ResourceKey<LootTable> SHARK = register("entities/shark");
    public static final ResourceKey<LootTable> WHALE = register("entities/whale");
    public static final ResourceKey<LootTable> LIOPLEURODON = register("entities/liopleurodon");
    public static final ResourceKey<LootTable> DIAMOND_DAVE = register("entities/diamond_dave");
    public static final ResourceKey<LootTable> RAINBOUR = register("entities/rainbour");
    public static final ResourceKey<LootTable> MINER = register("entities/miner");
    public static final ResourceKey<LootTable> ROTATICK = register("entities/rotatick");
    public static final ResourceKey<LootTable> CAVE_CRAWLER = register("entities/cave_crawler");
    public static final ResourceKey<LootTable> CAVECLOPS = register("entities/caveclops");
    public static final ResourceKey<LootTable> THE_EYE = register("entities/the_eye");
    public static final ResourceKey<LootTable> ENTHRALLED_DRAMCRYX = register("entities/enthralled_dramcryx");
    public static final ResourceKey<LootTable> THE_GRUE = register("entities/the_grue");
    public static final ResourceKey<LootTable> HELL_PIG = register("entities/hell_pig");
    public static final ResourceKey<LootTable> HELL_SPIDER = register("entities/hell_spider");
    public static final ResourceKey<LootTable> WILDFIRE = register("entities/wildfire");
    public static final ResourceKey<LootTable> SCORCHER = register("entities/scorcher");
    public static final ResourceKey<LootTable> ENDER_SCROUNGE = register("entities/ender_scrounge");
    public static final ResourceKey<LootTable> ENDER_SPIDER = register("entities/ender_spider");
    public static final ResourceKey<LootTable> ENDER_WATCHER = register("entities/ender_watcher");
    public static final ResourceKey<LootTable> ENDER_TRIPLETS = register("entities/ender_triplets");
    public static final ResourceKey<LootTable> CAULDRON_FISH = register("entities/cauldron_fish");
    public static final ResourceKey<LootTable> PINK_GHOST_GLIDER = register("entities/pink_ghost_glider");
    public static final ResourceKey<LootTable> BLUBBERTUSK = register("entities/blubbertusk");
    public static final ResourceKey<LootTable> ROBBIN = register("entities/robbin");
    public static final ResourceKey<LootTable> SNOW_SKIPPER = register("entities/snow_skipper");
    public static final ResourceKey<LootTable> WOLPERTINGER = register("entities/wolpertinger");
    public static final ResourceKey<LootTable> DOLOSSAL = register("entities/dolossal");
    public static final ResourceKey<LootTable> MAMOTH = register("entities/mamoth");
    public static final ResourceKey<LootTable> WORKSHOP_MERCHANT = register("entities/workshop_merchant");
    public static final ResourceKey<LootTable> WORKSHOP_TINKERER = register("entities/workshop_tinkerer");
    public static final ResourceKey<LootTable> ROLLUM = register("entities/rollum");
    public static final ResourceKey<LootTable> PALE_ARCHER = register("entities/pale_archer");
    public static final ResourceKey<LootTable> FROZEN_FLESH = register("entities/frozen_flesh");
    public static final ResourceKey<LootTable> ALICANTO = register("entities/alicanto");
    public static final ResourceKey<LootTable> SENG = register("entities/seng");
    public static final ResourceKey<LootTable> SABEAR = register("entities/sabear");
    public static final ResourceKey<LootTable> HASTREUS = register("entities/hastreus");
    public static final ResourceKey<LootTable> GLACIDE = register("entities/glacide");
    public static final ResourceKey<LootTable> FRACTITE = register("entities/fractite");
    public static final ResourceKey<LootTable> GROGLIN_MERCHANT = register("entities/groglin_merchant");
    public static final ResourceKey<LootTable> GROGLIN_SHARLATAN = register("entities/groglin_sharlatan");
    public static final ResourceKey<LootTable> GROGLIN_HUNTER = register("entities/groglin_hunter");
    public static final ResourceKey<LootTable> GROGLIN_RANGER = register("entities/groglin_ranger");
    public static final ResourceKey<LootTable> GROGLIN_WARRIOR = register("entities/groglin_warrior");
    public static final ResourceKey<LootTable> GROGLIN_CHIEFTAIN = register("entities/groglin_chieftain");
    public static final ResourceKey<LootTable> GRUZZORLUG_MINER = register("entities/gruzzorlug_miner");
    public static final ResourceKey<LootTable> GRUZZORLUG_CANNONEER = register("entities/gruzzorlug_cannoneer");
    public static final ResourceKey<LootTable> GRUZZORLUG_COMMANDER = register("entities/gruzzorlug_commander");
    public static final ResourceKey<LootTable> GRUZZORLUG_SWORDSMAN = register("entities/gruzzorlug_swordsman");
    public static final ResourceKey<LootTable> GRUZZORLUG_KNIGHT = register("entities/gruzzorlug_knight");
    public static final ResourceKey<LootTable> GRUZZORLUG_GENERAL = register("entities/gruzzorlug_general");
    public static final ResourceKey<LootTable> CAPTAIN_MERIK = register("entities/captain_merik");
    public static final ResourceKey<LootTable> DATTICON = register("entities/datticon");
    public static final ResourceKey<LootTable> KAZARI = register("entities/kazari");
    public static final ResourceKey<LootTable> LEORNA = register("entities/leorna");
    public static final ResourceKey<LootTable> LORD_VATTICUS = register("entities/lord_vatticus");
    public static final ResourceKey<LootTable> WAR_GENERAL = register("entities/war_general");
    public static final ResourceKey<LootTable> ZELUS = register("entities/zelus");
    public static final ResourceKey<LootTable> FYRACRYX = register("entities/fyracryx");
    public static final ResourceKey<LootTable> GOLEM_OF_REJUVENATION = register("entities/golem_of_rejuvenation");
    public static final ResourceKey<LootTable> PARATIKU = register("entities/paratiku");
    public static final ResourceKey<LootTable> SEIMER = register("entities/seimer");
    public static final ResourceKey<LootTable> WRAITH = register("entities/wraith");
    public static final ResourceKey<LootTable> SKYRE = register("entities/skyre");
    public static final ResourceKey<LootTable> RAZORBACK = register("entities/razorback");
    public static final ResourceKey<LootTable> DEATH_HOUND = register("entities/death_hound");
    public static final ResourceKey<LootTable> DUNGEON_CONSTRUCTOR = register("entities/dungeon_constructor");
    public static final ResourceKey<LootTable> DUNGEON_PRISONER = register("entities/dungeon_prisoner");
    public static final ResourceKey<LootTable> DUNGEON_DEMON = register("entities/dungeon_demon");
    public static final ResourceKey<LootTable> ROAMER = register("entities/roamer");
    public static final ResourceKey<LootTable> DEATHCRYX = register("entities/deathcryx");
    public static final ResourceKey<LootTable> LIVING_STATUE = register("entities/living_statue");
    // --- Eden ---
    public static final ResourceKey<LootTable> GEM_FIN = register("entities/gem_fin");
    public static final ResourceKey<LootTable> GLINTHOP = register("entities/glinthop");
    public static final ResourceKey<LootTable> EDEN_TOMO = register("entities/tomo");
    public static final ResourceKey<LootTable> EDEN_CADILLION = register("entities/cadillion");
    public static final ResourceKey<LootTable> GREENFEET = register("entities/greenfeet");
    public static final ResourceKey<LootTable> MADIVEL = register("entities/madivel");
    public static final ResourceKey<LootTable> SUN_ARCHER = register("entities/sun_archer");
    public static final ResourceKey<LootTable> WEAK_CORI = register("entities/weak_cori");
    public static final ResourceKey<LootTable> MOON_WOLF = register("entities/moon_wolf");
    public static final ResourceKey<LootTable> WILDWOOD_TOMO = register("entities/wildwood_tomo");
    public static final ResourceKey<LootTable> WILDWOOD_CADILLION = register("entities/wildwood_cadillion");
    public static final ResourceKey<LootTable> EPIPHITE = register("entities/epiphite");
    public static final ResourceKey<LootTable> BEHEMOTH = register("entities/behemoth");
    public static final ResourceKey<LootTable> TERMID = register("entities/termid");
    public static final ResourceKey<LootTable> VEREK = register("entities/verek");
    public static final ResourceKey<LootTable> WILDWOOD_GOLEM = register("entities/wildwood_golem");
    public static final ResourceKey<LootTable> MAGE = register("entities/mage");
    public static final ResourceKey<LootTable> APALACHIA_TOMO = register("entities/apalachia_tomo");
    public static final ResourceKey<LootTable> APALACHIA_CADILLION = register("entities/apalachia_cadillion");
    public static final ResourceKey<LootTable> ENCHANTED_WARRIOR = register("entities/enchanted_warrior");
    public static final ResourceKey<LootTable> APALACHIA_GOLEM = register("entities/apalachia_golem");
    public static final ResourceKey<LootTable> ENCHANTED_ARCHER = register("entities/enchanted_archer");
    public static final ResourceKey<LootTable> SPELLBINDER = register("entities/spellbinder");
    public static final ResourceKey<LootTable> SAMEK = register("entities/samek");
    public static final ResourceKey<LootTable> SKYTHERN_FIEND = register("entities/skythern_fiend");
    public static final ResourceKey<LootTable> SKYTHERN_GOLEM = register("entities/skythern_golem");
    public static final ResourceKey<LootTable> MEGALITH = register("entities/megalith");
    public static final ResourceKey<LootTable> SKYTHERN_ARCHER = register("entities/skythern_archer");
    public static final ResourceKey<LootTable> MYSTIC = register("entities/mystic");
    public static final ResourceKey<LootTable> ADVANCED_CORI = register("entities/advanced_cori");
    public static final ResourceKey<LootTable> ANGRY_GLINTHOP = register("entities/angry_glinthop");
    public static final ResourceKey<LootTable> MORTUM_CADILLION = register("entities/mortum_cadillion");
    public static final ResourceKey<LootTable> SOUL_SPIDER = register("entities/soul_spider");
    public static final ResourceKey<LootTable> BASILISK = register("entities/basilisk");
    public static final ResourceKey<LootTable> DEMON_OF_DARKNESS = register("entities/demon_of_darkness");
    public static final ResourceKey<LootTable> SOUL_STEALER = register("entities/soul_stealer");
    public static final ResourceKey<LootTable> TWILIGHT_ARCHER = register("entities/twilight_archer");
    public static final ResourceKey<LootTable> SORCERER = register("entities/sorcerer");
    public static final ResourceKey<LootTable> THE_HUNGER = register("entities/the_hunger");
    public static final ResourceKey<LootTable> CRYPT_KEEPER = register("entities/crypt_keeper");
    public static final ResourceKey<LootTable> MYSTERIOUS_MAN_LAYER_1 = register("entities/mysterious_man_layer_1");
    public static final ResourceKey<LootTable> ACID_HAG = register("entities/acid_hag");
    public static final ResourceKey<LootTable> CYMESOID = register("entities/cymesoid");
    public static final ResourceKey<LootTable> DREAMWRECKER = register("entities/dreamwrecker");
    public static final ResourceKey<LootTable> DUO = register("entities/duo");
    public static final ResourceKey<LootTable> ENT = register("entities/ent");
    public static final ResourceKey<LootTable> LORGA = register("entities/lorga");
    public static final ResourceKey<LootTable> SHADAHIER = register("entities/shadahier");
    public static final ResourceKey<LootTable> HIVE_SOLDIER = register("entities/hive_soldier");
    public static final ResourceKey<LootTable> HOVER_STINGER = register("entities/hover_stinger");
    public static final ResourceKey<LootTable> TEMPLE_GUARDIAN = register("entities/temple_guardian");
    public static final ResourceKey<LootTable> MYSTERIOUS_MAN_LAYER_2 = register("entities/mysterious_man_layer_2");
    public static final ResourceKey<LootTable> BIPHRON = register("entities/biphron");
    public static final ResourceKey<LootTable> GORGOSION = register("entities/gorgosion");
    public static final ResourceKey<LootTable> INSECT_FOURTEEN = register("entities/insect_fourteen");
    public static final ResourceKey<LootTable> MANDRAGORA = register("entities/mandragora");
    public static final ResourceKey<LootTable> TWINS = register("entities/twins");
    public static final ResourceKey<LootTable> VERMENOUS = register("entities/vermenous");
    public static final ResourceKey<LootTable> MYSTERIOUS_MAN_LAYER_3 = register("entities/mysterious_man_layer_3");
    public static final ResourceKey<LootTable> BOHEMITE = register("entities/bohemite");
    public static final ResourceKey<LootTable> GALROID = register("entities/galroid");
    public static final ResourceKey<LootTable> KAZROTIC = register("entities/kazrotic");
    public static final ResourceKey<LootTable> LHEIVA = register("entities/lheiva");
    public static final ResourceKey<LootTable> LORGA_FLIGHT = register("entities/lorga_flight");
    public static final ResourceKey<LootTable> TOCAXIN = register("entities/tocaxin");
    public static final ResourceKey<LootTable> DISSIMENT = register("entities/dissiment");
    public static final ResourceKey<LootTable> HELIO = register("entities/helio");
    public static final ResourceKey<LootTable> VHRAAK = register("entities/vhraak");
    public static final ResourceKey<LootTable> FAKE_VHRAAK = register("entities/fake_vhraak");
    public static final ResourceKey<LootTable> ZONE = register("entities/zone");
    public static final ResourceKey<LootTable> ZORAGON = register("entities/zoragon");
    public static final ResourceKey<LootTable> PATCHOULI = register("patchouli");

    private static ResourceKey<LootTable> register(String path) {
        return register(ResourceKey.create(Registries.LOOT_TABLE, Identifier.fromNamespaceAndPath(MODID, path)));
    }

    private static ResourceKey<LootTable> register(ResourceKey<LootTable> key) {
        if (LOCATIONS.add(key)) {
            return key;
        }
        throw new IllegalArgumentException(key.registry().getPath() + " is already a registered built-in loot table");
    }

    public static Set<ResourceKey<LootTable>> all() {
        return IMMUTABLE_LOCATIONS;
    }
    public static void load() {}
}
