package divinerpg.enums;

import net.minecraft.tags.TagKey;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.Tags;

import static divinerpg.enums.ToolStats.SwordSpecial.*;
import static divinerpg.registries.TagRegistry.*;
import static net.minecraft.tags.BlockTags.*;

public enum ToolStats implements Tier {
    APALACHIA_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2540, -2.4F, 25, 22, CHUNKS_APALACHIA),
    AQUATON(INCORRECT_FOR_IRON_TOOL, 992, -2.4F, 6.5F, 10, INGOTS_AQUATIC),
    AQUATOOTH_MAUL(INCORRECT_FOR_IRON_TOOL, 1524, -2.7F, 10.5F, 10, TEETH_LIOPLEURODON),
    AQUATOOTH_SWORD(INCORRECT_FOR_IRON_TOOL, 1245, -2.4F, 7.5F, 10, TEETH_LIOPLEURODON),
    AQUA_DAGGER(INCORRECT_FOR_IRON_TOOL, 535, -2, 3.5F, 12, INGOTS_AQUATIC),
    AQUA_MAUL(INCORRECT_FOR_IRON_TOOL, 1058, -2.7F, 9.2F, 10, INGOTS_AQUATIC),
    AQUA_TRIDENT(INCORRECT_FOR_IRON_TOOL, 843, -2.4F, 6, 10, INGOTS_AQUATIC),
    ARCANITE_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2048, -2.4F, 6, 15, GEMS_ARCANIUM, ARCANA_DAMAGE, 8, 0),
    ARCANIUM_SABER(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5, ARCANA_DAMAGE, 7, 0),
    ARLEMITE_STABBER(INCORRECT_FOR_DIAMOND_TOOL, 1535, -2.4F, 5, 10, INGOTS_ARLEMITE),
    BEDROCK_MAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.7F, 11.5F),
    BEDROCK_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 8),
    BLOODGEM_SWORD(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5.2F),
    BOWHEAD_ANCHOR(INCORRECT_FOR_IRON_TOOL, 768, -3, 8, 15, FINS_WHALE),
    CORRUPTED_MAUL(INCORRECT_FOR_NETHERITE_TOOL, 2948, -2.7F, 11.1F, 15, GEMS_CORRUPTED),
    CRABCLAW_MAUL(INCORRECT_FOR_IRON_TOOL, 1025, -2.7F, 6.1F, 13, CLAWS_CRAB),
    CRAB_ANCHOR(INCORRECT_FOR_IRON_TOOL, 384, -3, 6, 15, CLAWS_CRAB),
    CYCLOPSIAN_SWORD(INCORRECT_FOR_IRON_TOOL, 300, -2.4F, 4, 14, EYES_CYCLOPS),
    DEATH_BRINGER(INCORRECT_FOR_NETHERITE_TOOL, 1545, -2.4F, 7.3F, 15, GEMS_CORRUPTED),
    DIVINE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13),
    DUAL_CLAW(INCORRECT_FOR_IRON_TOOL, 822, -2.3F, 5.2F, 10, CLAWS_CRAB),
    EDEN_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2124, -2.4F, 17, 22, CHUNKS_EDEN),
    ENDERICE(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13, SLOW, 1, 3),
    ENDER_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 2556, -2.4F, 12, 10, GEMS_ENDER),
    FLAMING_FURY(INCORRECT_FOR_NETHERITE_TOOL, 3025, -2.3F, 10, 16, GEMS_MOLTEN, FLAME, 0, 15),
    FROSSIVENCE(INCORRECT_FOR_WOODEN_TOOL, 270, -2.4F, -1, 5, SNOWFLAKES, HEAL, 0, 0),
    FROSTKING_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1521, -2.4F, 6.5F, 13, SNOWFLAKES),
    FROST_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1226, -2.4F, 5.1F, 10, GEMS_ICE, SLOW, 1, 3),
    FROZEN_MAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.7F, 12.5F, SLOW, 1, 3),
    FURY_MAUL(INCORRECT_FOR_NETHERITE_TOOL, 3127, -2.8F, 14, 15, Tags.Items.GEMS_DIAMOND),
    GLACIAL_BLADE(INCORRECT_FOR_DIAMOND_TOOL, 1232, -2.3F, 11, 13, SNOWFLAKES, SLOW, 4, 2),
    GLACIER_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1021, -2.6F, 7, 13, SNOWFLAKES, SLOW, 1, 3),
    HALITE_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 3187, -2.4F, 34, 22, CHUNKS_MORTUM),
    ICICLE_BANE(INCORRECT_FOR_DIAMOND_TOOL, 1622, -2.5F, 6, 13, SNOWFLAKES, SLOW, 1, 3),
    ICICLE_DAGGER(INCORRECT_FOR_NETHERITE_TOOL, 4, -2, 20, 13, null),
    ICINE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 14, SLOW, 1, 3),
    INFERNO_SWORD(INCORRECT_FOR_IRON_TOOL, -2.4F, 5.2F, FLAME, 0, 12),
    JUNGLE_RAPIER(INCORRECT_FOR_DIAMOND_TOOL, 1425, -2.4F, 6, 12, GEMS_JUNGLE, POISON, 1, 4),
    LIOPLEURODON_ANCHOR(INCORRECT_FOR_IRON_TOOL, 960, -3, 9, 15, TEETH_LIOPLEURODON),
    LIVICIA_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 3223, -2.4F, 15.5F, 16, GEMS_SHADOW),
    MASSIVENCE(INCORRECT_FOR_WOODEN_TOOL, 60, -2.4F, -1, 5, GEMS_BLOODGEM, HEAL, 0, 0),
    MOLTEN_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1297, -2.4F, 5.4F, 10, GEMS_MOLTEN, FLAME, 0, 5),
    MORTUM_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2922, -2.4F, 31, 22, CHUNKS_MORTUM),
    PALAVENCE(INCORRECT_FOR_WOODEN_TOOL, 60, -2.4F, -1, 5, INGOTS_REALMITE, HEAL, 0, 0),
    POISON_SABER(INCORRECT_FOR_DIAMOND_TOOL, 1315, -2.4F, 6.5F, 15, GEMS_JUNGLE, POISON, 1, 5),
    REALMITE_SWORD(INCORRECT_FOR_IRON_TOOL, 325, -2.4F, 4.5F, 14, INGOTS_REALMITE),
    REALMITE_MAUL(INCORRECT_FOR_IRON_TOOL, 225, -2.7F, 5.5F, 14, INGOTS_REALMITE),
    RUPEE_RAPIER(INCORRECT_FOR_DIAMOND_TOOL, 1634, -2.4F, 5.5F, 14, INGOTS_RUPEE),
    SABEAR_SABRE(INCORRECT_FOR_IRON_TOOL, 982, -2.3F, 4.4F, 15, TEETH_SABEAR),
    SANDSLASH(INCORRECT_FOR_NETHERITE_TOOL, 100, -2.4F, 16, 15, GEMS_DIVINE),
    SCORCHING_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 1212, -2.4F, 6.2F, 15, POWDERS_PURPLE_BLAZE),
    SHADOW_SABER(INCORRECT_FOR_DIAMOND_TOOL, -2.2F, 10, SPEED, 1, 5),
    SHARK_ANCHOR(INCORRECT_FOR_IRON_TOOL, 576, -3, 7, 15, FINS_SHARK),
    SHARK_SWORD(INCORRECT_FOR_IRON_TOOL, 627, -2.4F, 5.5F, 10, INGOTS_AQUATIC),
    SKYTHERN_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2783, -2.4F, 29, 22, CHUNKS_SKYTHERN),
    SLIME_SWORD(INCORRECT_FOR_IRON_TOOL, 739, -2.6F, 6.5F, 10, Tags.Items.GEMS_DIAMOND),
    SNOWSLASH(INCORRECT_FOR_NETHERITE_TOOL, 150, -2.4F, 17, 15, SNOWFLAKES, SLOW, 1, 3),
    SOULFIRE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 1623, -2.4F, 7, 15, GEMS_SOULFIRE),
    STORM_SWORD(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5, LIGHTNING, 0, 0),
    TERRAN_DAGGER(INCORRECT_FOR_DIAMOND_TOOL, 425, -2, 3.4F, 12, GEMS_TERRAN),TERRAN_MAUL(INCORRECT_FOR_DIAMOND_TOOL, 1476, -2.7F, 7.4F, 10, GEMS_TERRAN),
    WILDWOOD_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2342, -2.4F, 21, 22, CHUNKS_WILDWOOD),

    //Knives
    OCEAN_KNIFE(INCORRECT_FOR_IRON_TOOL, 678, 7, 5.4F, 10, INGOTS_AQUATIC),
    TERRAN_KNIFE(INCORRECT_FOR_DIAMOND_TOOL, 1257, 8, 5.1F, 10, GEMS_TERRAN),
    JUNGLE_KNIFE(INCORRECT_FOR_DIAMOND_TOOL, 1292, 8, 5.2F, 10, GEMS_JUNGLE, POISON, 1, 3),

    //Shickaxes
    ARLEMITE_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2535, 8, 3.2F, 10, INGOTS_ARLEMITE),
    TERRAN_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2586, 8, 3.3F, 10, GEMS_TERRAN),
    TERRAN_SHIFTER(INCORRECT_FOR_DIAMOND_TOOL, 1724, 8, 3.3F, 10, GEMS_TERRAN),
    RUPEE_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2634, 8, 3.5F, 14, INGOTS_RUPEE),
    CORRUPTED_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3065, 10, 5, 15, GEMS_CORRUPTED),
    DIVINE_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 7),
    EDEN_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3124, 15, 9, 22, CHUNKS_EDEN),
    WILDWOOD_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3342, 20, 11, 22, CHUNKS_WILDWOOD),
    APALACHIA_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3540, 25, 12, 22, CHUNKS_APALACHIA),
    SKYTHERN_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3783, 30, 14, 22, CHUNKS_SKYTHERN),
    MORTUM_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3922, 35, 15, 22, CHUNKS_MORTUM),
    HALITE_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 40, 16),

    //Axes
    REALMITE_AXE(INCORRECT_FOR_IRON_TOOL, 325, 7, 8, 14, INGOTS_REALMITE),
    ARLEMITE_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 8, 10, INGOTS_ARLEMITE),
    TERRAN_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 8.2F, 10, GEMS_TERRAN),
    RUPEE_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 8.5F, 14, INGOTS_RUPEE),
    CORRUPTED_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 10.3F, 15, GEMS_CORRUPTED),
    BEDROCK_AXE(INCORRECT_FOR_NETHERITE_TOOL, 11, 11),
    DIVINE_AXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 16.5F),
    EDEN_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 21, 22, CHUNKS_EDEN),
    WILDWOOD_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 25, 22, CHUNKS_WILDWOOD),
    APALACHIA_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 29, 22, CHUNKS_APALACHIA),
    SKYTHERN_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 34, 22, CHUNKS_SKYTHERN),
    MORTUM_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 36, 22, CHUNKS_MORTUM),
    DREAM_AXE(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 8, 5, null),

    //Pickaxes
    REALMITE_PICKAXE(INCORRECT_FOR_IRON_TOOL, 325, 7, 3.5F, 14, INGOTS_REALMITE),
    OXDRITE_PICKAXE(INCORRECT_FOR_IRON_TOOL, 347, 7, 3.5F, 14, INGOTS_OXDRITE),
    ARLEMITE_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 4, 10, INGOTS_ARLEMITE),
    TERRAN_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 4.1F, 10, GEMS_TERRAN),
    RUPEE_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 4.5F, 14, INGOTS_RUPEE),
    CORRUPTED_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 5.5F, 15, GEMS_CORRUPTED),
    BEDROCK_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 11, 6),
    DIVINE_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 7),
    EDEN_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 8, 22, CHUNKS_EDEN),
    WILDWOOD_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 9, 22, CHUNKS_WILDWOOD),
    APALACHIA_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 10, 22, CHUNKS_APALACHIA),
    SKYTHERN_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 11, 22, CHUNKS_SKYTHERN),
    MORTUM_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 12, 22, CHUNKS_MORTUM),
    DREAM_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 3.5F, 5, null),

    //Shovels
    REALMITE_SHOVEL(INCORRECT_FOR_IRON_TOOL, 325, 7, 4, 14, INGOTS_REALMITE),
    ARLEMITE_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 4.5F, 10, INGOTS_ARLEMITE),
    TERRAN_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 4.7F, 10, GEMS_TERRAN),
    RUPEE_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 5, 14, INGOTS_RUPEE),
    CORRUPTED_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 6, 15, GEMS_CORRUPTED),
    BEDROCK_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 11, 6.5F),
    DIVINE_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 13, 7.5F),
    EDEN_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 8.5F, 22, CHUNKS_EDEN),
    WILDWOOD_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 9.5F, 22, CHUNKS_WILDWOOD),
    APALACHIA_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 10.5F, 22, CHUNKS_APALACHIA),
    SKYTHERN_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 11.5F, 22, CHUNKS_SKYTHERN),
    MORTUM_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 12.5F, 22, CHUNKS_MORTUM),
    DREAM_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 4, 5, null),

    //Hoes
    REALMITE_HOE(INCORRECT_FOR_IRON_TOOL, 325, 7, 0, 14, INGOTS_REALMITE),
    ARLEMITE_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 0, 10, INGOTS_ARLEMITE),
    TERRAN_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 0, 10, GEMS_TERRAN),
    RUPEE_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 0, 14, INGOTS_RUPEE),
    CORRUPTED_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, .5F, 15, GEMS_CORRUPTED),
    BEDROCK_HOE(INCORRECT_FOR_NETHERITE_TOOL, 11, .5F),
    DIVINE_HOE(INCORRECT_FOR_NETHERITE_TOOL, 13, 1),
    EDEN_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 2, 22, CHUNKS_EDEN),
    WILDWOOD_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 2, 22, CHUNKS_WILDWOOD),
    APALACHIA_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 2, 22, CHUNKS_APALACHIA),
    SKYTHERN_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 2, 22, CHUNKS_SKYTHERN),
    MORTUM_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 2, 22, CHUNKS_MORTUM),

    //Vethea
    //Hammers
    TEAKER_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 4),
    AMTHIRMIS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 6),
    DARVEN_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 10),
    CERMILE_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13),
    PARDIMAL_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 17),
    QUADROTIC_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 22),
    KAROS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 26),
    HELIOSIS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 31),
    ARKSIANE_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 37),
    EVERLIGHT(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 40),
    KAROS_ROCKMAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 42),

    //Backswords
    TEAKER_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 2),
    AMTHIRMIS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 4),
    DARVEN_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 7),
    CERMILE_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 11),
    PARDIMAL_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 14),
    QUADROTIC_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 18),
    KAROS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 20),
    HELIOSIS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 27),
    ARKSIANE_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 35),

    //Claws
    TEAKER_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 1),
    AMTHIRMIS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 3),
    DARVEN_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 5),
    CERMILE_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 6),
    PARDIMAL_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 10),
    QUADROTIC_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 12),
    KAROS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 17),
    HELIOSIS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 24),
    ARKSIANE_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 33),
    EVERBRIGHT(INCORRECT_FOR_NETHERITE_TOOL, -2, 40);

    private final Ingredient repairMaterial;
    private final SwordSpecial swordSpecial;
    public int effectPower, effectSec;
    private final float attackDamage;
    private final float efficiency;
    private final int enchantability;
    private final TagKey<Block> incorrectBlocksForDrops;
    private final int maxUses;
    //No specials
    ToolStats(TagKey<Block> harvestLevelIn, int maxUsesIn, float efficiencyIn, float attackDamageIn, int enchantabilityIn, TagKey<Item> repairMaterialIn) {
        incorrectBlocksForDrops = harvestLevelIn;
        maxUses = maxUsesIn;
        efficiency = efficiencyIn;
        attackDamage = attackDamageIn;
        enchantability = enchantabilityIn;
        repairMaterial = repairMaterialIn == null ? Ingredient.EMPTY : Ingredient.of(repairMaterialIn);
        swordSpecial = NONE;
    }
    //No specials, unbreakable
    ToolStats(TagKey<Block> harvestLevel, float efficiency, float attackDamage) {this(harvestLevel, 0, efficiency, attackDamage, 5, null);}
    //Specials, power, seconds
    ToolStats(TagKey<Block> harvestLevelIn, int maxUsesIn, float efficiencyIn, float attackDamageIn, int enchantabilityIn, TagKey<Item> repairMaterialIn, SwordSpecial special, int power, int seconds) {
        incorrectBlocksForDrops = harvestLevelIn;
        maxUses = maxUsesIn;
        efficiency = efficiencyIn;
        attackDamage = attackDamageIn;
        enchantability = enchantabilityIn;
        repairMaterial = repairMaterialIn == null ? Ingredient.EMPTY : Ingredient.of(repairMaterialIn);
        swordSpecial = special;
        effectPower = power;
        effectSec = seconds;
    }
    //Specials, power, seconds, unbreakable
    ToolStats(TagKey<Block> harvestLevel, float efficiency, float attackDamage, SwordSpecial special, int power, int seconds) {
        this(harvestLevel, 0, efficiency, attackDamage, 5, null, special, power, seconds);
    }
    @Override public int getUses() {return maxUses;}
    @Override public float getSpeed() {return efficiency;}
    @Override public float getAttackDamageBonus() {return attackDamage;}
    @Override public TagKey<Block> getIncorrectBlocksForDrops() {return this.incorrectBlocksForDrops;}
    @Override public int getEnchantmentValue() {return enchantability;}
    @Override public Ingredient getRepairIngredient() {return repairMaterial;}
    public SwordSpecial getSwordSpecial() {return swordSpecial;}
    public enum SwordSpecial {NONE, FLAME, WITHER, EXPLODE, SLOW, NAUSEA, BLIND, POISON, LIGHTNING, HEAL, SPEED, ARCANA_DAMAGE}
}