package divinerpg.enums;

import net.minecraft.tags.TagKey;
import net.minecraft.world.item.*;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.level.block.Block;

import static divinerpg.enums.ToolStats.SwordSpecial.*;
import static divinerpg.registries.TagRegistry.*;
import static net.minecraft.tags.BlockTags.*;

public enum ToolStats implements Tier {
    APALACHIA_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2540, -2.4F, 25, 22, REPAIRS_EQUIPMENT_APALACHIA),
    AQUATON(INCORRECT_FOR_IRON_TOOL, 992, -2.4F, 6.5F, 10, REPAIRS_EQUIPMENT_AQUATIC),
    AQUATOOTH_MAUL(INCORRECT_FOR_IRON_TOOL, 1524, -2.7F, 10.5F, 10, REPAIRS_EQUIPMENT_LIOPLEURODON),
    AQUATOOTH_SWORD(INCORRECT_FOR_IRON_TOOL, 1245, -2.4F, 7.5F, 10, REPAIRS_EQUIPMENT_LIOPLEURODON),
    AQUA_DAGGER(INCORRECT_FOR_IRON_TOOL, 535, -2, 3.5F, 12, REPAIRS_EQUIPMENT_AQUATIC),
    AQUA_MAUL(INCORRECT_FOR_IRON_TOOL, 1058, -2.7F, 9.2F, 10, REPAIRS_EQUIPMENT_AQUATIC),
    AQUA_TRIDENT(INCORRECT_FOR_IRON_TOOL, 843, -2.4F, 6, 10, REPAIRS_EQUIPMENT_AQUATIC),
    ARCANITE_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2048, -2.4F, 6, 15, REPAIRS_EQUIPMENT_ARCANIUM, ARCANA_DAMAGE, 8, 0),
    ARCANIUM_SABER(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5, 5, REPAIRS_EQUIPMENT_ARCANIUM, ARCANA_DAMAGE, 7, 0),
    ARLEMITE_STABBER(INCORRECT_FOR_DIAMOND_TOOL, 1535, -2.4F, 5, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    BEDROCK_MAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.7F, 11.5F, 5, REPAIRS_EQUIPMENT_BEDROCK),
    BEDROCK_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 8, 5, REPAIRS_EQUIPMENT_BEDROCK),
    BLOODGEM_SWORD(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5.2F, 5, REPAIRS_EQUIPMENT_BLOODGEM),
    BOWHEAD_ANCHOR(INCORRECT_FOR_IRON_TOOL, 768, -3, 8, 15, REPAIRS_EQUIPMENT_WHALE),
    CORRUPTED_MAUL(INCORRECT_FOR_NETHERITE_TOOL, 2948, -2.7F, 11.1F, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    CRABCLAW_MAUL(INCORRECT_FOR_IRON_TOOL, 1025, -2.7F, 6.1F, 13, REPAIRS_EQUIPMENT_CRAB),
    CRAB_ANCHOR(INCORRECT_FOR_IRON_TOOL, 384, -3, 6, 15, REPAIRS_EQUIPMENT_CRAB),
    CYCLOPSIAN_SWORD(INCORRECT_FOR_IRON_TOOL, 300, -2.4F, 4, 14, REPAIRS_EQUIPMENT_CYCLOPS),
    DEATH_BRINGER(INCORRECT_FOR_NETHERITE_TOOL, 1545, -2.4F, 7.3F, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    DIVINE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13, 5, REPAIRS_EQUIPMENT_DIVINE),
    DUAL_CLAW(INCORRECT_FOR_IRON_TOOL, 822, -2.3F, 5.2F, 10, REPAIRS_EQUIPMENT_CRAB),
    EDEN_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2124, -2.4F, 17, 22, REPAIRS_EQUIPMENT_EDEN),
    ENDERICE(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13, 5, REPAIRS_EQUIPMENT_SNOWFLAKE , SLOW, 1, 3),
    ENDER_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 2556, -2.4F, 12, 10, REPAIRS_EQUIPMENT_ENDER),
    FLAMING_FURY(INCORRECT_FOR_NETHERITE_TOOL, 3025, -2.3F, 10, 16, REPAIRS_EQUIPMENT_MOLTEN, FLAME, 0, 15),
    FROSSIVENCE(INCORRECT_FOR_WOODEN_TOOL, 270, -2.4F, -1, 5, REPAIRS_EQUIPMENT_SNOWFLAKE, HEAL, 0, 0),
    FROSTKING_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1521, -2.4F, 6.5F, 13, REPAIRS_EQUIPMENT_SNOWFLAKE),
    FROST_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1226, -2.4F, 5.1F, 10, REPAIRS_EQUIPMENT_ICE, SLOW, 1, 3),
    FROZEN_MAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.7F, 12.5F, 5, REPAIRS_EQUIPMENT_SNOWFLAKE, SLOW, 1, 3),
    FURY_MAUL(INCORRECT_FOR_NETHERITE_TOOL, 3127, -2.8F, 14, 15, REPAIRS_EQUIPMENT_BEDROCK),
    GLACIAL_BLADE(INCORRECT_FOR_DIAMOND_TOOL, 1232, -2.3F, 11, 13, REPAIRS_EQUIPMENT_ICE, SLOW, 4, 2),
    GLACIER_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1021, -2.6F, 7, 13, REPAIRS_EQUIPMENT_SNOWFLAKE, SLOW, 1, 3),
    HALITE_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 3187, -2.4F, 34, 22, REPAIRS_EQUIPMENT_HALITE),
    ICICLE_BANE(INCORRECT_FOR_DIAMOND_TOOL, 1622, -2.5F, 6, 13, REPAIRS_EQUIPMENT_SNOWFLAKE, SLOW, 1, 3),
    ICICLE_DAGGER(INCORRECT_FOR_NETHERITE_TOOL, 4, -2, 20, 13, null),
    ICINE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 14, 5, REPAIRS_EQUIPMENT_SNOWFLAKE, SLOW, 1, 3),
    INFERNO_SWORD(INCORRECT_FOR_IRON_TOOL, -2.4F, 5.2F, 5, REPAIRS_EQUIPMENT_BLAZE, FLAME, 0, 12),
    JUNGLE_RAPIER(INCORRECT_FOR_DIAMOND_TOOL, 1425, -2.4F, 6, 12, REPAIRS_EQUIPMENT_JUNGLE, POISON, 1, 4),
    LIOPLEURODON_ANCHOR(INCORRECT_FOR_IRON_TOOL, 960, -3, 9, 15, REPAIRS_EQUIPMENT_LIOPLEURODON),
    LIVICIA_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 3223, -2.4F, 15.5F, 16, REPAIRS_EQUIPMENT_EXPENSIVE_SHADOW),
    MASSIVENCE(INCORRECT_FOR_WOODEN_TOOL, 60, -2.4F, -1, 5, REPAIRS_EQUIPMENT_BLOODGEM, HEAL, 0, 0),
    MOLTEN_SWORD(INCORRECT_FOR_DIAMOND_TOOL, 1297, -2.4F, 5.4F, 10, REPAIRS_EQUIPMENT_MOLTEN, FLAME, 0, 5),
    MORTUM_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2922, -2.4F, 31, 22, REPAIRS_EQUIPMENT_MORTUM),
    PALAVENCE(INCORRECT_FOR_WOODEN_TOOL, 60, -2.4F, -1, 5, REPAIRS_EQUIPMENT_REALMITE, HEAL, 0, 0),
    POISON_SABER(INCORRECT_FOR_DIAMOND_TOOL, 1315, -2.4F, 6.5F, 15, REPAIRS_EQUIPMENT_JUNGLE, POISON, 1, 5),
    REALMITE_SWORD(INCORRECT_FOR_IRON_TOOL, 325, -2.4F, 4.5F, 14, REPAIRS_EQUIPMENT_REALMITE),
    REALMITE_MAUL(INCORRECT_FOR_IRON_TOOL, 225, -2.7F, 5.5F, 14, REPAIRS_EQUIPMENT_REALMITE),
    RUPEE_RAPIER(INCORRECT_FOR_DIAMOND_TOOL, 1634, -2.4F, 5.5F, 14, REPAIRS_EQUIPMENT_RUPEE),
    SABEAR_SABRE(INCORRECT_FOR_IRON_TOOL, 982, -2.3F, 4.4F, 15, REPAIRS_EQUIPMENT_SABEAR_TEETH),
    SANDSLASH(INCORRECT_FOR_NETHERITE_TOOL, 100, -2.4F, 16, 15, REPAIRS_EQUIPMENT_DIVINE),
    SCORCHING_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 1212, -2.4F, 6.2F, 15, REPAIRS_EQUIPMENT_PURPLE_BLAZE),
    SHADOW_SABER(INCORRECT_FOR_DIAMOND_TOOL, -2.2F, 10, 5, REPAIRS_EQUIPMENT_EXPENSIVE_SHADOW, SPEED, 1, 5),
    SHARK_ANCHOR(INCORRECT_FOR_IRON_TOOL, 576, -3, 7, 15, REPAIRS_EQUIPMENT_SHARK),
    SHARK_SWORD(INCORRECT_FOR_IRON_TOOL, 627, -2.4F, 5.5F, 10, REPAIRS_EQUIPMENT_AQUATIC),
    SKYTHERN_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2783, -2.4F, 29, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    SLIME_SWORD(INCORRECT_FOR_IRON_TOOL, 739, -2.6F, 6.5F, 10, REPAIRS_EQUIPMENT_DIAMOND),
    SNOWSLASH(INCORRECT_FOR_NETHERITE_TOOL, 150, -2.4F, 17, 15, REPAIRS_EQUIPMENT_SNOWFLAKE, SLOW, 1, 3),
    SOULFIRE_SWORD(INCORRECT_FOR_NETHERITE_TOOL, 1623, -2.4F, 7, 15, REPAIRS_EQUIPMENT_SOULFIRE),
    STORM_SWORD(INCORRECT_FOR_DIAMOND_TOOL, -2.4F, 5, 5, REPAIRS_EQUIPMENT_ARCANIUM, LIGHTNING, 0, 0),
    TERRAN_DAGGER(INCORRECT_FOR_DIAMOND_TOOL, 425, -2, 3.4F, 12, REPAIRS_EQUIPMENT_TERRAN),
    TERRAN_MAUL(INCORRECT_FOR_DIAMOND_TOOL, 1476, -2.7F, 7.4F, 10, REPAIRS_EQUIPMENT_TERRAN),
    WILDWOOD_BLADE(INCORRECT_FOR_NETHERITE_TOOL, 2342, -2.4F, 21, 22, REPAIRS_EQUIPMENT_WILDWOOD),

    //Knives
    OCEAN_KNIFE(INCORRECT_FOR_IRON_TOOL, 678, 7, 5.4F, 10, REPAIRS_EQUIPMENT_AQUATIC),
    TERRAN_KNIFE(INCORRECT_FOR_DIAMOND_TOOL, 1257, 8, 5.1F, 10, REPAIRS_EQUIPMENT_TERRAN),
    JUNGLE_KNIFE(INCORRECT_FOR_DIAMOND_TOOL, 1292, 8, 5.2F, 10, REPAIRS_EQUIPMENT_JUNGLE, POISON, 1, 3),

    //Bows
    HUNTER_BOW(1125, 72000, 1.2F, 1, REPAIRS_EQUIPMENT_JUNGLE),
    SHADOW_BOW(1225, 36000, 1, 1, REPAIRS_EQUIPMENT_SHADOW),
    ICICLE_BOW(1456, 24000, 1, 1, REPAIRS_EQUIPMENT_SNOWFLAKE),
    INFERNO_BOW(72000, 1, 1, REPAIRS_EQUIPMENT_MOLTEN),
    SOULFIRE_BOW(72000, 1.5F, 1, REPAIRS_EQUIPMENT_SOULFIRE),
    SNOWSTORM_BOW(72000, 1.7F, 1, REPAIRS_EQUIPMENT_SNOWFLAKE),
    ENDER_BOW(72000, 1.2F, 1, REPAIRS_EQUIPMENT_ENDER),
    EDEN_BOW(1517, 72000, 1.3F, 1, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_BOW(1624, 36000, 1.4F, 1, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_BOW(1778, 72000, 1.5F, 2, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_BOW(1879, 36000, 1.6F, 2, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_BOW(1990, 72000, 1.7F, 3, REPAIRS_EQUIPMENT_MORTUM),
    HALITE_BOW(2114, 36000, 1.8F, 3, REPAIRS_EQUIPMENT_HALITE),
    TWILIGHT_BOW(2376, 14400, 1.9F, 4, REPAIRS_EQUIPMENT_TWILIGHT),
    TEAKER_BOW(72000, .9F, 1, REPAIRS_EQUIPMENT_TEAKER),
    AMTHIRMIS_BOW(72000, 1, 1, REPAIRS_EQUIPMENT_AMTHIRMIS),
    DARVEN_BOW(72000, 1.1F, 1, REPAIRS_EQUIPMENT_DARVEN),
    CERMILE_BOW(72000, 1.2F, 1, REPAIRS_EQUIPMENT_CERMILE),
    PARDIMAL_BOW(72000, 1.3F, 1, REPAIRS_EQUIPMENT_PARDIMAL),
    QUADROTIC_BOW(72000, 1.4F, 1, REPAIRS_EQUIPMENT_QUADROTIC),
    KAROS_BOW(72000, 1.5F, 1, REPAIRS_EQUIPMENT_KAROS),
    HELIOSIS_BOW(72000, 1.6F, 1, REPAIRS_EQUIPMENT_HELIOSIS),
    ARKSIANE_BOW(72000, 1.7F, 1, REPAIRS_EQUIPMENT_ARKSIANE),
    EVERFRIGHT(72000, 1.8F, 1, REPAIRS_EQUIPMENT_EVER),

    //Shickaxes
    ARLEMITE_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2535, 8, 3.2F, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    TERRAN_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2586, 8, 3.3F, 10, REPAIRS_EQUIPMENT_TERRAN),
    TERRAN_SHIFTER(INCORRECT_FOR_DIAMOND_TOOL, 1724, 8, 3.3F, 10, REPAIRS_EQUIPMENT_TERRAN),
    RUPEE_SHICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 2634, 8, 3.5F, 14, REPAIRS_EQUIPMENT_RUPEE),
    CORRUPTED_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3065, 10, 5, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    DIVINE_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 7, 5, REPAIRS_EQUIPMENT_DIVINE),
    EDEN_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3124, 15, 9, 22, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3342, 20, 11, 22, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3540, 25, 12, 22, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3783, 30, 14, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 3922, 35, 15, 22, REPAIRS_EQUIPMENT_MORTUM),
    HALITE_SHICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 40, 16, 10, REPAIRS_EQUIPMENT_HALITE),

    //Axes
    REALMITE_AXE(INCORRECT_FOR_IRON_TOOL, 325, 7, 8, 14, REPAIRS_EQUIPMENT_REALMITE),
    ARLEMITE_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 8, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    TERRAN_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 8.2F, 10, REPAIRS_EQUIPMENT_TERRAN),
    RUPEE_AXE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 8.5F, 14, REPAIRS_EQUIPMENT_RUPEE),
    CORRUPTED_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 10.3F, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    BEDROCK_AXE(INCORRECT_FOR_NETHERITE_TOOL, 11, 11, 5, REPAIRS_EQUIPMENT_BEDROCK),
    DIVINE_AXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 16.5F, 5, REPAIRS_EQUIPMENT_DIVINE),
    EDEN_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 21, 22, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 25, 22, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 29, 22, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 34, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_AXE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 36, 22, REPAIRS_EQUIPMENT_MORTUM),
    DREAM_AXE(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 8, 5, REPAIRS_EQUIPMENT_DREAM),

    //Pickaxes
    REALMITE_PICKAXE(INCORRECT_FOR_IRON_TOOL, 325, 7, 3.5F, 14, REPAIRS_EQUIPMENT_REALMITE),
    OXDRITE_PICKAXE(INCORRECT_FOR_IRON_TOOL, 347, 7, 3.5F, 14, REPAIRS_EQUIPMENT_OXDRITE),
    ARLEMITE_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 4, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    TERRAN_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 4.1F, 10, REPAIRS_EQUIPMENT_TERRAN),
    RUPEE_PICKAXE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 4.5F, 14, REPAIRS_EQUIPMENT_RUPEE),
    CORRUPTED_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 5.5F, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    BEDROCK_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 11, 6, 5, REPAIRS_EQUIPMENT_BEDROCK),
    DIVINE_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 13, 7, 5, REPAIRS_EQUIPMENT_DIVINE),
    EDEN_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 8, 22, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 9, 22, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 10, 22, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 11, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 12, 22, REPAIRS_EQUIPMENT_MORTUM),
    DREAM_PICKAXE(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 3.5F, 5, REPAIRS_EQUIPMENT_DREAM),

    //Shovels
    REALMITE_SHOVEL(INCORRECT_FOR_IRON_TOOL, 325, 7, 4, 14, REPAIRS_EQUIPMENT_REALMITE),
    ARLEMITE_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 4.5F, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    TERRAN_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 4.7F, 10, REPAIRS_EQUIPMENT_TERRAN),
    RUPEE_SHOVEL(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 5, 14, REPAIRS_EQUIPMENT_RUPEE),
    CORRUPTED_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, 6, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    BEDROCK_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 11, 6.5F, 5, REPAIRS_EQUIPMENT_BEDROCK),
    DIVINE_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 13, 7.5F, 5, REPAIRS_EQUIPMENT_DIVINE),
    EDEN_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 8.5F, 22, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 9.5F, 22, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 10.5F, 22, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 11.5F, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 12.5F, 22, REPAIRS_EQUIPMENT_MORTUM),
    DREAM_SHOVEL(INCORRECT_FOR_NETHERITE_TOOL, 513, 8, 4, 5, REPAIRS_EQUIPMENT_DREAM),

    //Hoes
    REALMITE_HOE(INCORRECT_FOR_IRON_TOOL, 325, 7, 0, 14, REPAIRS_EQUIPMENT_REALMITE),
    ARLEMITE_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1535, 8, 0, 10, REPAIRS_EQUIPMENT_ARLEMITE),
    TERRAN_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1586, 8, 0, 10, REPAIRS_EQUIPMENT_TERRAN),
    RUPEE_HOE(INCORRECT_FOR_DIAMOND_TOOL, 1634, 8, 0, 14, REPAIRS_EQUIPMENT_RUPEE),
    CORRUPTED_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2065, 10, .5F, 15, REPAIRS_EQUIPMENT_CORRUPTED),
    BEDROCK_HOE(INCORRECT_FOR_NETHERITE_TOOL, 11, .5F, 5, REPAIRS_EQUIPMENT_BEDROCK),
    DIVINE_HOE(INCORRECT_FOR_NETHERITE_TOOL, 13, 1, 5, REPAIRS_EQUIPMENT_DIVINE),
    EDEN_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2124, 15, 2, 22, REPAIRS_EQUIPMENT_EDEN),
    WILDWOOD_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2342, 20, 2, 22, REPAIRS_EQUIPMENT_WILDWOOD),
    APALACHIA_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2540, 25, 2, 22, REPAIRS_EQUIPMENT_APALACHIA),
    SKYTHERN_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2783, 30, 2, 22, REPAIRS_EQUIPMENT_SKYTHERN),
    MORTUM_HOE(INCORRECT_FOR_NETHERITE_TOOL, 2922, 35, 2, 22, REPAIRS_EQUIPMENT_MORTUM),

    //Vethea
    //Hammers
    TEAKER_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 4, 6, REPAIRS_EQUIPMENT_TEAKER),
    AMTHIRMIS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 6, 7, REPAIRS_EQUIPMENT_AMTHIRMIS),
    DARVEN_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 10, 8, REPAIRS_EQUIPMENT_DARVEN),
    CERMILE_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 13, 9, REPAIRS_EQUIPMENT_CERMILE),
    PARDIMAL_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 17, 10, REPAIRS_EQUIPMENT_PARDIMAL),
    QUADROTIC_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 22, 11, REPAIRS_EQUIPMENT_QUADROTIC),
    KAROS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 26, 12, REPAIRS_EQUIPMENT_KAROS),
    HELIOSIS_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 31, 13, REPAIRS_EQUIPMENT_HELIOSIS),
    ARKSIANE_HAMMER(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 37, 14, REPAIRS_EQUIPMENT_ARKSIANE),
    EVERLIGHT(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 40, 15, REPAIRS_EQUIPMENT_EVER),
    KAROS_ROCKMAUL(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 42, 15, null),

    //Backswords
    TEAKER_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 2, 6, REPAIRS_EQUIPMENT_TEAKER),
    AMTHIRMIS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 4, 7, REPAIRS_EQUIPMENT_AMTHIRMIS),
    DARVEN_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 7, 8, REPAIRS_EQUIPMENT_DARVEN),
    CERMILE_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 11, 9, REPAIRS_EQUIPMENT_CERMILE),
    PARDIMAL_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 14, 10, REPAIRS_EQUIPMENT_PARDIMAL),
    QUADROTIC_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 18, 11, REPAIRS_EQUIPMENT_QUADROTIC),
    KAROS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 20, 12, REPAIRS_EQUIPMENT_KAROS),
    HELIOSIS_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 27, 13, REPAIRS_EQUIPMENT_HELIOSIS),
    ARKSIANE_BACKSWORD(INCORRECT_FOR_NETHERITE_TOOL, -2.4F, 35, 14, REPAIRS_EQUIPMENT_ARKSIANE),

    //Claws
    TEAKER_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 1, 6, REPAIRS_EQUIPMENT_TEAKER),
    AMTHIRMIS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 3, 7, REPAIRS_EQUIPMENT_AMTHIRMIS),
    DARVEN_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 5, 8, REPAIRS_EQUIPMENT_DARVEN),
    CERMILE_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 6, 9, REPAIRS_EQUIPMENT_CERMILE),
    PARDIMAL_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 10, 10, REPAIRS_EQUIPMENT_PARDIMAL),
    QUADROTIC_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 12, 11, REPAIRS_EQUIPMENT_QUADROTIC),
    KAROS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 17, 12, REPAIRS_EQUIPMENT_KAROS),
    HELIOSIS_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 24, 13, REPAIRS_EQUIPMENT_HELIOSIS),
    ARKSIANE_CLAW(INCORRECT_FOR_NETHERITE_TOOL, -2, 33, 14, REPAIRS_EQUIPMENT_ARKSIANE),
    EVERBRIGHT(INCORRECT_FOR_NETHERITE_TOOL, -2, 40, 15, REPAIRS_EQUIPMENT_EVER);

    public final Ingredient repairMaterial;
    private final SwordSpecial swordSpecial;
    public int effectPower, effectSec, useDuration;
    private final float attackDamage, efficiency;
    private final int enchantability, maxUses;
    private final TagKey<Block> incorrectBlocksForDrops;
    //No specials
    ToolStats(TagKey<Block> harvestLevelIn, int maxUsesIn, float efficiencyIn, float attackDamageIn, int enchantabilityIn, TagKey<Item> repairMaterialIn) {
        incorrectBlocksForDrops = harvestLevelIn;
        maxUses = maxUsesIn;
        efficiency = efficiencyIn;
        attackDamage = attackDamageIn;
        enchantability = enchantabilityIn;
        repairMaterial = repairMaterialIn == null ? Ingredient.EMPTY : Ingredient.of(repairMaterialIn);
        swordSpecial = NONE;
    }
    //No specials, unbreakable
    ToolStats(TagKey<Block> harvestLevel, float efficiency, float attackDamage, int enchantability, TagKey<Item> repairMaterial) {
        this(harvestLevel, 0, efficiency, attackDamage, enchantability, repairMaterial);
    }
    //Specials, power, seconds
    ToolStats(TagKey<Block> harvestLevelIn, int maxUsesIn, float efficiencyIn, float attackDamageIn, int enchantabilityIn, TagKey<Item> repairMaterialIn, SwordSpecial special, int power, int seconds) {
        incorrectBlocksForDrops = harvestLevelIn;
        maxUses = maxUsesIn;
        efficiency = efficiencyIn;
        attackDamage = attackDamageIn;
        enchantability = enchantabilityIn;
        repairMaterial = repairMaterialIn == null ? Ingredient.EMPTY : Ingredient.of(repairMaterialIn);
        swordSpecial = special;
        effectPower = power;
        effectSec = seconds;
    }
    //Specials, power, seconds, unbreakable
    ToolStats(TagKey<Block> harvestLevel, float efficiency, float attackDamage, int enchantability, TagKey<Item> repairMaterial, SwordSpecial special, int power, int seconds) {
        this(harvestLevel, 0, efficiency, attackDamage, enchantability, repairMaterial, special, power, seconds);
    }
    //Bows
    ToolStats(int maxUsesIn, int useDurationIn, float speedScale, int enchantabilityIn, TagKey<Item> repairMaterialIn) {
        incorrectBlocksForDrops = INCORRECT_FOR_WOODEN_TOOL;
        maxUses = maxUsesIn;
        useDuration = useDurationIn;
        efficiency = speedScale;
        attackDamage = 0;
        enchantability = enchantabilityIn;
        repairMaterial = repairMaterialIn == null ? Ingredient.EMPTY : Ingredient.of(repairMaterialIn);
        swordSpecial = NONE;
    }
    //Bows, unbreakable
    ToolStats(int useDuration, float speedScale, int enchantability, TagKey<Item> repairMaterial) {
        this(0, useDuration, speedScale, enchantability, repairMaterial);
    }
    @Override public int getUses() {return maxUses;}
    @Override public float getSpeed() {return efficiency;}
    public float getUseDuration() {return useDuration;}
    @Override public float getAttackDamageBonus() {return attackDamage;}
    @Override public TagKey<Block> getIncorrectBlocksForDrops() {return this.incorrectBlocksForDrops;}
    @Override public int getEnchantmentValue() {return enchantability;}
    @Override public Ingredient getRepairIngredient() {return repairMaterial;}
    public SwordSpecial getSwordSpecial() {return swordSpecial;}
    public enum SwordSpecial {NONE, FLAME, WITHER, EXPLODE, SLOW, NAUSEA, BLIND, POISON, LIGHTNING, HEAL, SPEED, ARCANA_DAMAGE}
}