modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
displayURL="${mod_url}"
logoFile="${mod_logo}"
updateJSONURL="${mod_update_json}"

[[mixins]]
modid = "divinerpg"
config = "divinerpg.mixins.json"

[[dependencies.divinerpg]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.divinerpg]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"