package net.divinerpg.helper.entity;

import net.divinerpg.entity.vethea.EntityAcidHag;
import net.divinerpg.entity.vethea.EntityBiphron;
import net.divinerpg.entity.vethea.EntityBohemite;
import net.divinerpg.entity.vethea.EntityCryptKeeper;
import net.divinerpg.entity.vethea.EntityCymesoid;
import net.divinerpg.entity.vethea.EntityDissiment;
import net.divinerpg.entity.vethea.EntityDreamwrecker;
import net.divinerpg.entity.vethea.EntityDuo;
import net.divinerpg.entity.vethea.EntityEhu;
import net.divinerpg.entity.vethea.EntityEndiku;
import net.divinerpg.entity.vethea.EntityEnt;
import net.divinerpg.entity.vethea.EntityGalroid;
import net.divinerpg.entity.vethea.EntityGorgosion;
import net.divinerpg.entity.vethea.EntityHelio;
import net.divinerpg.entity.vethea.EntityHiveQueen;
import net.divinerpg.entity.vethea.EntityHiveSoldier;
import net.divinerpg.entity.vethea.EntityHoverStinger;
import net.divinerpg.entity.vethea.EntityHungerHungry;
import net.divinerpg.entity.vethea.EntityHusk;
import net.divinerpg.entity.vethea.EntityKaros;
import net.divinerpg.entity.vethea.EntityKazrotic;
import net.divinerpg.entity.vethea.EntityLadyLuna;
import net.divinerpg.entity.vethea.EntityLheiva;
import net.divinerpg.entity.vethea.EntityLorga;
import net.divinerpg.entity.vethea.EntityLorgaFlight;
import net.divinerpg.entity.vethea.EntityMandragora;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer1;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer2;
import net.divinerpg.entity.vethea.EntityMysteriousManLayer3;
import net.divinerpg.entity.vethea.EntityQuadro;
import net.divinerpg.entity.vethea.EntityRaglok;
import net.divinerpg.entity.vethea.EntityShadahier;
import net.divinerpg.entity.vethea.EntityStoneGolem;
import net.divinerpg.entity.vethea.EntityTempleGuardian;
import net.divinerpg.entity.vethea.EntityTocaxin;
import net.divinerpg.entity.vethea.EntityTwins;
import net.divinerpg.entity.vethea.EntityVermenous;
import net.divinerpg.entity.vethea.EntityVhraak;
import net.divinerpg.entity.vethea.EntityWreck;
import net.divinerpg.entity.vethea.EntityZone;
import net.divinerpg.entity.vethea.EntityZoragon;
import net.divinerpg.entity.vethea.projectile.EntityAmthirmisDisk;
import net.divinerpg.entity.vethea.projectile.EntityArksianeDisk;
import net.divinerpg.entity.vethea.projectile.EntityBouncingProjectile;
import net.divinerpg.entity.vethea.projectile.EntityCermileDisk;
import net.divinerpg.entity.vethea.projectile.EntityDarvenDisk;
import net.divinerpg.entity.vethea.projectile.EntityDissimentShot;
import net.divinerpg.entity.vethea.projectile.EntityEvernightProjectile;
import net.divinerpg.entity.vethea.projectile.EntityEversightProjectile;
import net.divinerpg.entity.vethea.projectile.EntityHeliosisDisk;
import net.divinerpg.entity.vethea.projectile.EntityKarosDisk;
import net.divinerpg.entity.vethea.projectile.EntityKazroticShot;
import net.divinerpg.entity.vethea.projectile.EntityMandragoraProjectile;
import net.divinerpg.entity.vethea.projectile.EntityPardimalDisk;
import net.divinerpg.entity.vethea.projectile.EntityQuadroticDisk;
import net.divinerpg.entity.vethea.projectile.EntityRaglokBomb;
import net.divinerpg.entity.vethea.projectile.EntityTeakerDisk;
import net.divinerpg.entity.vethea.projectile.EntityVetheanCannonEversight;
import net.divinerpg.entity.vethea.projectile.EntityVetheanCannonShot;
import net.divinerpg.entity.vethea.projectile.EntityWreckExplosiveShot;
import net.divinerpg.entity.vethea.projectile.EntityZoragonBomb;
import net.divinerpg.helper.Util;

public class VetheaEntityRegistry {

	public static void init(){
		Util.registerProjectile(EntityAmthirmisDisk.class, "Amthirmis Disk");
		Util.registerProjectile(EntityArksianeDisk.class, "Arksiane Disk");
		Util.registerProjectile(EntityCermileDisk.class, "Cermile Disk");
		Util.registerProjectile(EntityDarvenDisk.class, "Darven Disk");
		Util.registerProjectile(EntityHeliosisDisk.class, "Heliosis Disk");
		Util.registerProjectile(EntityKarosDisk.class, "Karos Disk");
		Util.registerProjectile(EntityPardimalDisk.class, "Pardimal Disk");
		Util.registerProjectile(EntityQuadroticDisk.class, "Quadrotic Disk");
		Util.registerProjectile(EntityTeakerDisk.class, "Teaker Disk");
		Util.registerProjectile(EntityBouncingProjectile.class, "Staff");
		Util.registerProjectile(EntityEvernightProjectile.class, "Evernight");
		Util.registerProjectile(EntityVetheanCannonShot.class, "Cannon");
		Util.registerProjectile(EntityVetheanCannonEversight.class, "Cannon Eversight");
		Util.registerProjectile(EntityEversightProjectile.class, "Eversight");
		Util.registerProjectile(EntityDissimentShot.class, "Dissiment Shot");
		Util.registerProjectile(EntityKazroticShot.class, "Kazrotic Shot");
		Util.registerProjectile(EntityMandragoraProjectile.class, "Mandragora Shot");
		Util.registerProjectile(EntityRaglokBomb.class, "Raglok Bomb");
		Util.registerProjectile(EntityWreckExplosiveShot.class, "Wreck Explosive Shot");
		Util.registerProjectile(EntityZoragonBomb.class, "Zoragon Bomb");

		Util.registerDivineRPGMob(EntityVermenous.class, "Vermenous", Util.mobID++);
        Util.registerDivineRPGMob(EntityEnt.class, "Ent", Util.mobID++);
        Util.registerDivineRPGMob(EntityCymesoid.class, "Cymesoid", Util.mobID++);
        Util.registerDivineRPGMob(EntityDreamwrecker.class, "Dream Wrecker", Util.mobID++);
        Util.registerDivineRPGMob(EntityTocaxin.class, "Tocaxin", Util.mobID++);
        Util.registerDivineRPGMob(EntityShadahier.class, "Shadahier", Util.mobID++);
        Util.registerDivineRPGMob(EntityAcidHag.class, "Acid Hag", Util.mobID++);
        Util.registerDivineRPGMob(EntityKazrotic.class, "Kazrotic", Util.mobID++);
        Util.registerDivineRPGMob(EntityHelio.class, "Helio", Util.mobID++);
        Util.registerDivineRPGMob(EntityGorgosion.class, "Gorgosion", Util.mobID++);
        Util.registerDivineRPGMob(EntityHoverStinger.class, "Hoverstinger", Util.mobID++);
        Util.registerDivineRPGMob(EntityZone.class, "Zone", Util.mobID++);
        Util.registerDivineRPGMob(EntityZoragon.class, "Zoragon", Util.mobID++);
        Util.registerDivineRPGMob(EntityDissiment.class, "Dissiment", Util.mobID++);
        Util.registerDivineRPGMob(EntityVhraak.class, "Vhraak", Util.mobID++);
        Util.registerDivineRPGMob(EntityGalroid.class, "Galroid", Util.mobID++);
        Util.registerDivineRPGMob(EntityLadyLuna.class, "Lady Luna", Util.mobID++);
        Util.registerDivineRPGMob(EntityBohemite.class, "Bohemite", Util.mobID++);
        Util.registerDivineRPGMob(EntityWreck.class, "Wreck", Util.mobID++);
        Util.registerDivineRPGMob(EntityBiphron.class, "Biphron", Util.mobID++);
        Util.registerDivineRPGMob(EntityHiveQueen.class, "Hive Queen", Util.mobID++);
        Util.registerDivineRPGMob(EntityHiveSoldier.class, "hivesoldier", Util.mobID++);
        Util.registerDivineRPGMob(EntityLheiva.class, "lheiva", Util.mobID++);
        Util.registerDivineRPGMob(EntityMandragora.class, "mandragora", Util.mobID++);
        Util.registerDivineRPGMob(EntityTwins.class, "Twins", Util.mobID++);
        Util.registerDivineRPGMob(EntityKaros.class, "Karos", Util.mobID++);
        Util.registerDivineRPGMob(EntityRaglok.class, "Raglok", Util.mobID++);
        Util.registerDivineRPGMob(EntityQuadro.class, "Quadro", Util.mobID++);
        Util.registerDivineRPGMob(EntityDuo.class, "Duo", Util.mobID++);
        Util.registerDivineRPGMob(EntityEndiku.class, "Endiku", Util.mobID++);
        Util.registerDivineRPGMob(EntityLorga.class, "Lorga", Util.mobID++);
        Util.registerDivineRPGMob(EntityLorgaFlight.class, "Lorga Flight", Util.mobID++);
        Util.registerDivineRPGMob(EntityMysteriousManLayer1.class, "Mysterious Man 1", Util.mobID++);
        Util.registerDivineRPGMob(EntityMysteriousManLayer2.class, "Mysterious Man 2", Util.mobID++);
        Util.registerDivineRPGMob(EntityMysteriousManLayer3.class, "Mysterious Man 3", Util.mobID++);
        Util.registerDivineRPGMob(EntityHungerHungry.class, "Hunger Hungry", Util.mobID++);
        Util.registerDivineRPGMob(EntityCryptKeeper.class, "Crypt Keeper", Util.mobID++);
        Util.registerDivineRPGMob(EntityTempleGuardian.class, "Temple Guardian", Util.mobID++);
        Util.registerDivineRPGMob(EntityEhu.class, "Ehu", Util.mobID++);
        Util.registerDivineRPGMob(EntityStoneGolem.class, "Stone Golem", Util.mobID++);
        Util.registerDivineRPGMob(EntityHusk.class, "Husk", Util.mobID++);
	}
}