package divinerpg.registry;

import divinerpg.api.Reference;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = Reference.MODID)
public final class ModSounds {

    public static final SoundEvent ALICANTO = createEvent("alicanto");
    public static final SoundEvent ALICANTO_HURT = createEvent("alicanto_hurt");
    public static final SoundEvent ARCANIUM_SABER = createEvent("arcanium_saber");
    public static final SoundEvent ARCHER = createEvent("archer");
    public static final SoundEvent ARID_WARRIOR = createEvent("arid_warrior");
    public static final SoundEvent ARID_WARRIOR_HURT = createEvent("arid_warrior_hurt");
    public static final SoundEvent AYERACO = createEvent("ayeraco");
    public static final SoundEvent AYERACO_HALF_HEALTH = createEvent("ayeraco_half_health");
    public static final SoundEvent AYERACO_HURT = createEvent("ayeraco_hurt");
    public static final SoundEvent AYERACO_PILLAR = createEvent("ayeraco_pillar");
    public static final SoundEvent AYERACO_SPAWN = createEvent("ayeraco_spawn");
    public static final SoundEvent AYERACO_TELEPORT = createEvent("ayeraco_teleport");
    public static final SoundEvent BLITZ = createEvent("blitz");
    public static final SoundEvent BUNNY = createEvent("bunny");
    public static final SoundEvent BUNNY_HURT = createEvent("bunny_hurt");
    public static final SoundEvent CADILLION = createEvent("cadillion");
    public static final SoundEvent CONSTRUCTOR_HURT = createEvent("constructor_hurt");
    public static final SoundEvent CONSTRUCTOR_PUNCH = createEvent("constructor_punch");
    public static final SoundEvent CORI = createEvent("cori");
    public static final SoundEvent CORI_HURT = createEvent("cori_hurt");
    public static final SoundEvent CORI_IDLE = createEvent("cori_idle");
    public static final SoundEvent CORI_SHOOT = createEvent("cori_shoot");
    public static final SoundEvent CRAB = createEvent("crab");
    public static final SoundEvent CRAB_HURT = createEvent("crab_hurt");
    public static final SoundEvent CRAWLER = createEvent("crawler");
    public static final SoundEvent CRAWLER_HURT = createEvent("crawler_hurt");
    public static final SoundEvent CROAK = createEvent("croak");
    public static final SoundEvent CYCLOPS = createEvent("cyclops");
    public static final SoundEvent CYCLOPS_HURT = createEvent("cyclops_hurt");
    public static final SoundEvent DEATHCRYX = createEvent("deathcryx");
    public static final SoundEvent DEATHCRYX_HURT = createEvent("deathcryx_hurt");
    public static final SoundEvent DEATH_HOUND = createEvent("death_hound");
    public static final SoundEvent DEATH_HOUND_HURT = createEvent("death_hound_hurt");
    public static final SoundEvent DEEP_LAUGH = createEvent("deep_laugh");
    public static final SoundEvent DEMON_OF_DARKNESS = createEvent("demon_of_darkness");
    public static final SoundEvent DENSOS = createEvent("densos");
    public static final SoundEvent DENSOS_HURT = createEvent("densos_hurt");
    public static final SoundEvent DIVINE_ACCUMULATOR = createEvent("divine_accumulator");
    public static final SoundEvent DRAMCRYX = createEvent("dramcryx");
    public static final SoundEvent DRAMCRYX_HURT = createEvent("dramcryx_hurt");
    public static final SoundEvent DRAMIX = createEvent("dramix");
    public static final SoundEvent DRAMIX_HURT = createEvent("dramix_hurt");
    public static final SoundEvent DUNGEON_PRISONER = createEvent("dungeon_prisoner");
    public static final SoundEvent DUNGEON_PRISONER_CHANGE = createEvent("dungeon_prisoner_change");
    public static final SoundEvent DUNGEON_PRISONER_HURT = createEvent("dungeon_prisoner_hurt");
    public static final SoundEvent ENDIKU = createEvent("endiku");
    public static final SoundEvent ENDIKU_HURT = createEvent("endiku_hurt");
    public static final SoundEvent FIREFLY = createEvent("firefly");
    public static final SoundEvent FRACTITE = createEvent("fractite");
    public static final SoundEvent FRACTITE_ATTACK = createEvent("fractite_attack");
    public static final SoundEvent FRACTITE_CANNON = createEvent("fractite_cannon");
    public static final SoundEvent FRACTITE_HURT = createEvent("fractite_hurt");
    public static final SoundEvent FROST = createEvent("frost");
    public static final SoundEvent FROSTCLAW_CANNON = createEvent("frostclaw_cannon");
    public static final SoundEvent FROSTY = createEvent("frosty");
    public static final SoundEvent FROSTY_HURT = createEvent("frosty_hurt");
    public static final SoundEvent FROST_CANNON = createEvent("frost_cannon");
    public static final SoundEvent GHAST_CANNON = createEvent("ghast_cannon");
    public static final SoundEvent GLACIDE = createEvent("glacide");
    public static final SoundEvent GLACIDE_HURT = createEvent("glacide_hurt");
    public static final SoundEvent GOLEM = createEvent("golem");
    public static final SoundEvent GRASS = createEvent("grass");
    public static final SoundEvent GRIZZLE = createEvent("grizzle");
    public static final SoundEvent GRIZZLE_HURT = createEvent("grizzle_hurt");
    public static final SoundEvent GROWL = createEvent("growl");
    public static final SoundEvent GROWL_HURT = createEvent("growl_hurt");
    public static final SoundEvent HASTREUS = createEvent("hastreus");
    public static final SoundEvent HASTREUS_HURT = createEvent("hastreus_hurt");
    public static final SoundEvent HEAL = createEvent("heal");
    public static final SoundEvent HELL_SPIDER = createEvent("hell_spider");
    public static final SoundEvent HERBOMANCER = createEvent("herbomancer");
    public static final SoundEvent HERBOMANCER_HURT = createEvent("herbomancer_hurt");
    public static final SoundEvent HIGH_HIT = createEvent("high_hit");
    public static final SoundEvent HISS = createEvent("hiss");
    public static final SoundEvent ICEMAN = createEvent("iceman");
    public static final SoundEvent ICEMAN_HURT = createEvent("iceman_hurt");
    public static final SoundEvent INSECT = createEvent("insect");
    public static final SoundEvent JACKOMAN = createEvent("jackoman");
    public static final SoundEvent JUNGLE_SPIDER = createEvent("jungle_spider");
    public static final SoundEvent KING_OF_SCORCHERS = createEvent("king_of_scorchers");
    public static final SoundEvent KING_OF_SCORCHERS_HURT = createEvent("king_of_scorchers_hurt");
    public static final SoundEvent KOBBLIN = createEvent("kobblin");
    public static final SoundEvent LA_VEKOR = createEvent("la_vekor");
    public static final SoundEvent LIOPLEURODON = createEvent("liopleurodon");
    public static final SoundEvent LIOPLEURODON_HURT = createEvent("liopleurodon_hurt");
    public static final SoundEvent LIVESTOCK_MERCHANT = createEvent("livestock_merchant");
    public static final SoundEvent LIVESTOCK_MERCHANT_HURT = createEvent("livestock_merchant_hurt");
    public static final SoundEvent MADIVEL = createEvent("madivel");
    public static final SoundEvent MADIVEL_HURT = createEvent("madivel_hurt");
    public static final SoundEvent MAGE_FIRE = createEvent("mage_fire");
    public static final SoundEvent MEGALITH = createEvent("megalith");
    public static final SoundEvent MEGALITH_HURT = createEvent("megalith_hurt");
    public static final SoundEvent MUCKY = createEvent("mucky");
    public static final SoundEvent NESRO = createEvent("nesro");
    public static final SoundEvent NESRO_HURT = createEvent("nesro_hurt");
    public static final SoundEvent OCEAN = createEvent("ocean");
    public static final SoundEvent PARASECTA = createEvent("parasecta");
    public static final SoundEvent PARASECTA_HURT = createEvent("parasecta_hurt");
    public static final SoundEvent PHASER = createEvent("phaser");
    public static final SoundEvent RAINBOUR = createEvent("rainbour");
    public static final SoundEvent RAINBOUR_HURT = createEvent("rainbour_hurt");
    public static final SoundEvent RAZORBACK = createEvent("razorback");
    public static final SoundEvent RAZORBACK_HURT = createEvent("razorback_hurt");
    public static final SoundEvent REFLECTOR = createEvent("reflector");
    public static final SoundEvent REYVOR = createEvent("reyvor");
    public static final SoundEvent REYVOR_HURT = createEvent("reyvor_hurt");
    public static final SoundEvent ROAMER = createEvent("roamer");
    public static final SoundEvent ROAMER_HURT = createEvent("roamer_hurt");
    public static final SoundEvent ROAR = createEvent("roar");
    public static final SoundEvent ROLLUM = createEvent("rollum");
    public static final SoundEvent ROLLUM_HURT = createEvent("rollum_hurt");
    public static final SoundEvent ROTATICK = createEvent("rotatick");
    public static final SoundEvent ROTATICK_HURT = createEvent("rotatick_hurt");
    public static final SoundEvent SAGUARO_WORM = createEvent("saguaro_worm");
    public static final SoundEvent SCORCHER = createEvent("scorcher");
    public static final SoundEvent SERENADE = createEvent("serenade");
    public static final SoundEvent SHADOW_SABER = createEvent("shadow_saber");
    public static final SoundEvent SHARK = createEvent("shark");
    public static final SoundEvent SHARK_HURT = createEvent("shark_hurt");
    public static final SoundEvent SOUND_OF_CAROLS = createEvent("sound_of_carols");
    public static final SoundEvent SOUND_OF_MUSIC = createEvent("sound_of_music");
    public static final SoundEvent SPARKLER = createEvent("sparkler");
    public static final SoundEvent STAFF = createEvent("staff");
    public static final SoundEvent STARLIGHT = createEvent("starlight");
    public static final SoundEvent THE_EYE = createEvent("the_eye");
    public static final SoundEvent THE_EYE_HURT = createEvent("the_eye_hurt");
    public static final SoundEvent VEREK = createEvent("verek");
    public static final SoundEvent VEREK_HURT = createEvent("verek_hurt");
    public static final SoundEvent WHALE = createEvent("whale");
    public static final SoundEvent WHALE_HURT = createEvent("whale_hurt");
    public static final SoundEvent WILDFIRE = createEvent("wildfire");
    public static final SoundEvent WILDFIRE_HURT = createEvent("wildfire_hurt");
    public static final SoundEvent WRAITH = createEvent("wraith");
    public static final SoundEvent WRAITH_HURT = createEvent("wraith_hurt");

    public static final SoundEvent ICEIKA_MUSIC = createEvent("iceika_music");

    private static SoundEvent createEvent(String sound) {
        ResourceLocation soundLocation = new ResourceLocation(Reference.MODID, sound);
        return new SoundEvent(soundLocation).setRegistryName(soundLocation);
    }

    @SubscribeEvent
    public static void registerSounds(RegistryEvent.Register<SoundEvent> evt) {
        evt.getRegistry().register(ALICANTO);
        evt.getRegistry().register(ALICANTO_HURT);
        evt.getRegistry().register(ARCANIUM_SABER);
        evt.getRegistry().register(ARCHER);
        evt.getRegistry().register(ARID_WARRIOR);
        evt.getRegistry().register(ARID_WARRIOR_HURT);
        evt.getRegistry().register(AYERACO);
        evt.getRegistry().register(AYERACO_HALF_HEALTH);
        evt.getRegistry().register(AYERACO_HURT);
        evt.getRegistry().register(AYERACO_PILLAR);
        evt.getRegistry().register(AYERACO_SPAWN);
        evt.getRegistry().register(AYERACO_TELEPORT);
        evt.getRegistry().register(BLITZ);
        evt.getRegistry().register(BUNNY);
        evt.getRegistry().register(BUNNY_HURT);
        evt.getRegistry().register(CADILLION);
        evt.getRegistry().register(CONSTRUCTOR_HURT);
        evt.getRegistry().register(CONSTRUCTOR_PUNCH);
        evt.getRegistry().register(CORI);
        evt.getRegistry().register(CORI_HURT);
        evt.getRegistry().register(CORI_IDLE);
        evt.getRegistry().register(CORI_SHOOT);
        evt.getRegistry().register(CRAB);
        evt.getRegistry().register(CRAB_HURT);
        evt.getRegistry().register(CRAWLER);
        evt.getRegistry().register(CRAWLER_HURT);
        evt.getRegistry().register(CROAK);
        evt.getRegistry().register(CYCLOPS);
        evt.getRegistry().register(CYCLOPS_HURT);
        evt.getRegistry().register(DEATHCRYX);
        evt.getRegistry().register(DEATHCRYX_HURT);
        evt.getRegistry().register(DEATH_HOUND);
        evt.getRegistry().register(DEATH_HOUND_HURT);
        evt.getRegistry().register(DEEP_LAUGH);
        evt.getRegistry().register(DEMON_OF_DARKNESS);
        evt.getRegistry().register(DENSOS);
        evt.getRegistry().register(DENSOS_HURT);
        evt.getRegistry().register(DIVINE_ACCUMULATOR);
        evt.getRegistry().register(DRAMCRYX);
        evt.getRegistry().register(DRAMCRYX_HURT);
        evt.getRegistry().register(DRAMIX);
        evt.getRegistry().register(DRAMIX_HURT);
        evt.getRegistry().register(DUNGEON_PRISONER);
        evt.getRegistry().register(DUNGEON_PRISONER_CHANGE);
        evt.getRegistry().register(DUNGEON_PRISONER_HURT);
        evt.getRegistry().register(ENDIKU);
        evt.getRegistry().register(ENDIKU_HURT);
        evt.getRegistry().register(FIREFLY);
        evt.getRegistry().register(FRACTITE);
        evt.getRegistry().register(FRACTITE_ATTACK);
        evt.getRegistry().register(FRACTITE_CANNON);
        evt.getRegistry().register(FRACTITE_HURT);
        evt.getRegistry().register(FROST);
        evt.getRegistry().register(FROSTCLAW_CANNON);
        evt.getRegistry().register(FROSTY);
        evt.getRegistry().register(FROSTY_HURT);
        evt.getRegistry().register(FROST_CANNON);
        evt.getRegistry().register(GHAST_CANNON);
        evt.getRegistry().register(GLACIDE);
        evt.getRegistry().register(GLACIDE_HURT);
        evt.getRegistry().register(GOLEM);
        evt.getRegistry().register(GRASS);
        evt.getRegistry().register(GRIZZLE);
        evt.getRegistry().register(GRIZZLE_HURT);
        evt.getRegistry().register(GROWL);
        evt.getRegistry().register(GROWL_HURT);
        evt.getRegistry().register(HASTREUS);
        evt.getRegistry().register(HASTREUS_HURT);
        evt.getRegistry().register(HEAL);
        evt.getRegistry().register(HELL_SPIDER);
        evt.getRegistry().register(HERBOMANCER);
        evt.getRegistry().register(HERBOMANCER_HURT);
        evt.getRegistry().register(HIGH_HIT);
        evt.getRegistry().register(HISS);
        evt.getRegistry().register(ICEMAN);
        evt.getRegistry().register(ICEMAN_HURT);
        evt.getRegistry().register(INSECT);
        evt.getRegistry().register(JACKOMAN);
        evt.getRegistry().register(JUNGLE_SPIDER);
        evt.getRegistry().register(KING_OF_SCORCHERS);
        evt.getRegistry().register(KING_OF_SCORCHERS_HURT);
        evt.getRegistry().register(KOBBLIN);
        evt.getRegistry().register(LA_VEKOR);
        evt.getRegistry().register(LIOPLEURODON);
        evt.getRegistry().register(LIOPLEURODON_HURT);
        evt.getRegistry().register(LIVESTOCK_MERCHANT);
        evt.getRegistry().register(LIVESTOCK_MERCHANT_HURT);
        evt.getRegistry().register(MADIVEL);
        evt.getRegistry().register(MADIVEL_HURT);
        evt.getRegistry().register(MAGE_FIRE);
        evt.getRegistry().register(MEGALITH);
        evt.getRegistry().register(MEGALITH_HURT);
        evt.getRegistry().register(MUCKY);
        evt.getRegistry().register(NESRO);
        evt.getRegistry().register(NESRO_HURT);
        evt.getRegistry().register(OCEAN);
        evt.getRegistry().register(PARASECTA);
        evt.getRegistry().register(PARASECTA_HURT);
        evt.getRegistry().register(PHASER);
        evt.getRegistry().register(RAINBOUR);
        evt.getRegistry().register(RAINBOUR_HURT);
        evt.getRegistry().register(RAZORBACK);
        evt.getRegistry().register(RAZORBACK_HURT);
        evt.getRegistry().register(REFLECTOR);
        evt.getRegistry().register(REYVOR);
        evt.getRegistry().register(REYVOR_HURT);
        evt.getRegistry().register(ROAMER);
        evt.getRegistry().register(ROAMER_HURT);
        evt.getRegistry().register(ROAR);
        evt.getRegistry().register(ROLLUM);
        evt.getRegistry().register(ROLLUM_HURT);
        evt.getRegistry().register(ROTATICK);
        evt.getRegistry().register(ROTATICK_HURT);
        evt.getRegistry().register(SAGUARO_WORM);
        evt.getRegistry().register(SCORCHER);
        evt.getRegistry().register(SERENADE);
        evt.getRegistry().register(SHADOW_SABER);
        evt.getRegistry().register(SHARK);
        evt.getRegistry().register(SHARK_HURT);
        evt.getRegistry().register(SOUND_OF_CAROLS);
        evt.getRegistry().register(SOUND_OF_MUSIC);
        evt.getRegistry().register(SPARKLER);
        evt.getRegistry().register(STAFF);
        evt.getRegistry().register(STARLIGHT);
        evt.getRegistry().register(THE_EYE);
        evt.getRegistry().register(THE_EYE_HURT);
        evt.getRegistry().register(VEREK);
        evt.getRegistry().register(VEREK_HURT);
        evt.getRegistry().register(WHALE);
        evt.getRegistry().register(WHALE_HURT);
        evt.getRegistry().register(WILDFIRE);
        evt.getRegistry().register(WILDFIRE_HURT);
        evt.getRegistry().register(WRAITH);
        evt.getRegistry().register(WRAITH_HURT);
        evt.getRegistry().register(ICEIKA_MUSIC);
    }
}
