package net.divinerpg.dimensions.vethea.all;
import net.divinerpg.dimensions.vethea.IVetheanStructure;
import net.divinerpg.dimensions.vethea.VetheaChunk;
import net.divinerpg.utils.blocks.VetheaBlocks;

public class Lamp1 implements IVetheanStructure
{
	public void generate(VetheaChunk chunk, int i, int j, int k) {
		chunk.setBlock(i + 1, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 1, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 1, j + 2, k + 0, VetheaBlocks.dreamLamp);
		chunk.setBlock(i + 1, j + 2, k + 5, VetheaBlocks.dreamLamp);
		chunk.setBlock(i + 1, j + 3, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 1, j + 3, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 1, j + 4, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 1, j + 4, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 2, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 2, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 2, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 2, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 3, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 3, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 3, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 3, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 4, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 4, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 4, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 2, j + 4, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 0, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 1, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 1, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 2, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 2, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 3, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 3, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 4, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 4, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 5, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 3, j + 5, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 0, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 1, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 1, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 2, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 2, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 3, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 3, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 4, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 4, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 5, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 4, j + 5, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 2, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 2, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 2, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 2, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 3, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 3, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 3, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 3, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 4, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 4, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 4, k + 4, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 5, j + 4, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 0, k + 2, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 0, k + 3, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 2, k + 0, VetheaBlocks.dreamLamp);
		chunk.setBlock(i + 6, j + 3, k + 0, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 3, k + 5, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 4, k + 1, VetheaBlocks.darkEverstone);
		chunk.setBlock(i + 6, j + 4, k + 4, VetheaBlocks.darkEverstone);
	}
}